import {
  createReportApi,
  type AIAnalysisResult,
  type CreateReportParams,
  type CreateReportTemplateParams,
  type GenerateReportResponse,
  type NotificationConfig,
  type NotificationResult,
  type NotificationType,
  type Report,
  type ReportFormat,
  type ReportSection,
  type ReportStatus,
  type ReportTemplate,
  type ReportTemplateConfig,
  type SectionFormat,
  type SectionSource,
  type SectionType,
  type SectionValidation,
  type StepFilter,
  type UpdateReportTemplateParams,
  type ValidationFailAction,
  type ValidationResult,
} from '@ops/user-core';
import apiClient from '@/shared/api/http/client';

export type {
  AIAnalysisResult,
  CreateReportParams,
  CreateReportTemplateParams,
  GenerateReportResponse,
  NotificationConfig,
  NotificationResult,
  NotificationType,
  Report,
  ReportFormat,
  ReportSection,
  ReportStatus,
  ReportTemplate,
  ReportTemplateConfig,
  SectionFormat,
  SectionSource,
  SectionType,
  SectionValidation,
  StepFilter,
  UpdateReportTemplateParams,
  ValidationFailAction,
  ValidationResult,
};

export const reportApi = createReportApi(apiClient);
