const EXECUTION_STATUS = {
  DRAFT: 'draft',
  QUEUED: 'queued',
  RUNNING: 'running',
  WAITING_INPUT: 'waiting_input',
  PENDING_APPROVAL: 'pending_approval',
  HUMAN_CONTROL: 'human_control',
  PAUSED: 'paused',
  SUCCEEDED: 'succeeded',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
  ROLLED_BACK: 'rolled_back',
} as const;

const APPROVAL_STATUS = {
  PENDING: 'pending',
} as const;

const EXECUTION_EVENT_TYPE = {
  EXECUTION_STATUS_CHANGED: 'execution.status_changed',
  EXECUTION_INPUT_SUBMITTED: 'execution.input_submitted',
  RUNTIME_ALLOCATED: 'runtime.allocated',
  STEP_STARTED: 'step.started',
  STEP_SUCCEEDED: 'step.succeeded',
  STEP_FAILED: 'step.failed',
  STEP_WAITING_INPUT: 'step.waiting_input',
} as const;

export const CONTROL_PLANE_EXECUTION_STATUS = {
  QUEUED: EXECUTION_STATUS.QUEUED,
  RUNNING: EXECUTION_STATUS.RUNNING,
  WAITING_INPUT: EXECUTION_STATUS.WAITING_INPUT,
  PENDING_APPROVAL: EXECUTION_STATUS.PENDING_APPROVAL,
  HUMAN_CONTROL: EXECUTION_STATUS.HUMAN_CONTROL,
  SUCCEEDED: EXECUTION_STATUS.SUCCEEDED,
  FAILED: EXECUTION_STATUS.FAILED,
  CANCELLED: EXECUTION_STATUS.CANCELLED,
} as const;

export type ControlPlaneExecutionStatus =
  (typeof CONTROL_PLANE_EXECUTION_STATUS)[keyof typeof CONTROL_PLANE_EXECUTION_STATUS];

export type TerminalControlPlaneExecutionStatus =
  | typeof CONTROL_PLANE_EXECUTION_STATUS.SUCCEEDED
  | typeof CONTROL_PLANE_EXECUTION_STATUS.FAILED
  | typeof CONTROL_PLANE_EXECUTION_STATUS.CANCELLED;

export const CONTROL_PLANE_APPROVAL_STATUS = {
  PENDING: APPROVAL_STATUS.PENDING,
} as const;

export type ControlPlaneApprovalStatus =
  (typeof CONTROL_PLANE_APPROVAL_STATUS)[keyof typeof CONTROL_PLANE_APPROVAL_STATUS];

export const CONTROL_PLANE_EVENT_TYPE = {
  EXECUTION_STATUS_CHANGED: EXECUTION_EVENT_TYPE.EXECUTION_STATUS_CHANGED,
  EXECUTION_INPUT_SUBMITTED: EXECUTION_EVENT_TYPE.EXECUTION_INPUT_SUBMITTED,
  RUNTIME_ALLOCATED: EXECUTION_EVENT_TYPE.RUNTIME_ALLOCATED,
  STEP_STARTED: EXECUTION_EVENT_TYPE.STEP_STARTED,
  STEP_SUCCEEDED: EXECUTION_EVENT_TYPE.STEP_SUCCEEDED,
  STEP_FAILED: EXECUTION_EVENT_TYPE.STEP_FAILED,
  STEP_WAITING_INPUT: EXECUTION_EVENT_TYPE.STEP_WAITING_INPUT,
} as const;

export const LEGACY_CONTROL_PLANE_EVENT_TYPE = {
  EXECUTION_WAITING_INPUT: 'execution.waiting_input',
} as const;

export type ControlPlaneEventType =
  (typeof CONTROL_PLANE_EVENT_TYPE)[keyof typeof CONTROL_PLANE_EVENT_TYPE];

export const TERMINAL_CONTROL_PLANE_EXECUTION_STATUSES: TerminalControlPlaneExecutionStatus[] = [
  CONTROL_PLANE_EXECUTION_STATUS.SUCCEEDED,
  CONTROL_PLANE_EXECUTION_STATUS.FAILED,
  CONTROL_PLANE_EXECUTION_STATUS.CANCELLED,
];

export const isTerminalControlPlaneExecutionStatus = (
  status: string
): status is TerminalControlPlaneExecutionStatus =>
  TERMINAL_CONTROL_PLANE_EXECUTION_STATUSES.includes(status as TerminalControlPlaneExecutionStatus);
