export const LLM_OPERATION_ERROR_CODES = {
  NOT_FOUND: 'LLM_OPERATION_NOT_FOUND',
  VERSION_NOT_FOUND: 'LLM_OPERATION_VERSION_NOT_FOUND',
  DIGEST_MISMATCH: 'LLM_OPERATION_DIGEST_MISMATCH',
  NOT_ACTIVE: 'LLM_OPERATION_NOT_ACTIVE',
  ATTESTATION_INVALID: 'LLM_OPERATION_ATTESTATION_INVALID',
  INVALID_STATE_TRANSITION: 'LLM_OPERATION_INVALID_STATE_TRANSITION',
  ACTIVATION_FAILED: 'LLM_OPERATION_ACTIVATION_FAILED',
  LEGACY_REGISTRY_FALLBACK: 'LLM_OPERATION_LEGACY_REGISTRY_FALLBACK',
  CONCURRENT_MODIFICATION: 'LLM_OPERATION_CONCURRENT_MODIFICATION',
  INPUT_SCHEMA_VIOLATION: 'INPUT_SCHEMA_VIOLATION',
  OUTPUT_PARSE_FAILED: 'OUTPUT_PARSE_FAILED',
  OUTPUT_SCHEMA_VIOLATION: 'OUTPUT_SCHEMA_VIOLATION',
  TOOL_CALL_FORBIDDEN: 'TOOL_CALL_FORBIDDEN',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  INVALID_OPERATION_CONFIG: 'INVALID_OPERATION_CONFIG',
  VALIDATION_FAILED: 'LLM_OPERATION_VALIDATION_FAILED',
  REPAIR_EXHAUSTED: 'REPAIR_EXHAUSTED',
} as const;

export type LlmOperationErrorCode = typeof LLM_OPERATION_ERROR_CODES[keyof typeof LLM_OPERATION_ERROR_CODES];

export class LlmOperationError extends Error {
  public readonly code: LlmOperationErrorCode;
  public readonly details?: Record<string, unknown>;

  constructor(code: LlmOperationErrorCode, message: string, details?: Record<string, unknown>) {
    super(message);
    this.code = code;
    this.details = details;
    this.name = 'LlmOperationError';
  }
}
