-- Generated by docker/scripts/export-initial-data.sh
-- Source database: ops
-- Generated at: 2026-07-08 18:44:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- PostgreSQL database dump
--

\restrict HH2zliS3J0GbFf5dHSwUcfxRyG3W7r1BHJFcToeBVhitv9aXGNHFoaJIn8biKeC

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: activities; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: organizations; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: execution_flow_templates; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: identity_provider_configs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users (id, username, password_hash, email, role, ldap_dn, ad_sid, external_id, active_org_id, is_active, last_login_at, created_at, updated_at) VALUES ('5654953e-1b01-4094-bb29-b28f61d3f6a6', 'admin', '$2a$06$Kr448OJGWw1qt9R6HvtJYuHPIRj0GkxSMvr10HId.yI4O5E4BXVhS', 'admin@example.com', 'admin', NULL, NULL, NULL, NULL, true, NULL, '2026-07-08 10:44:43.235447+00', '2026-07-08 10:44:43.235447+00');


--
-- Data for Name: org_memberships; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.roles (id, name, description, permissions, is_system, created_at, updated_at) VALUES ('1e703640-4753-4163-a9d8-e97bbffa1c32', 'admin', '系统管理员', '{"all_skills": true}', true, '2026-07-08 10:44:43.230966+00', '2026-07-08 10:44:43.230966+00');
INSERT INTO public.roles (id, name, description, permissions, is_system, created_at, updated_at) VALUES ('7c3053d4-4b60-4a32-860c-11796013455d', 'employee', '普通员工', '{}', true, '2026-07-08 10:44:43.230966+00', '2026-07-08 10:44:43.230966+00');
INSERT INTO public.roles (id, name, description, permissions, is_system, created_at, updated_at) VALUES ('6cca2c82-73dc-4874-8474-0bc7938b8512', 'agent', '自动化代理', '{"replay_stop": true, "agent_create": true, "replay_start": true}', true, '2026-07-08 10:44:43.230966+00', '2026-07-08 10:44:43.230966+00');


--
-- Data for Name: org_role_bindings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: skill_configs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: skill_permissions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: skill_tool_bindings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: teams; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: team_memberships; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: temporal_workflows; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: tool_catalogs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.user_roles (user_id, role_id, assigned_at, assigned_by) VALUES ('5654953e-1b01-4094-bb29-b28f61d3f6a6', '1e703640-4753-4163-a9d8-e97bbffa1c32', '2026-07-08 10:44:43.24128+00', NULL);


--
-- PostgreSQL database dump complete
--

\unrestrict HH2zliS3J0GbFf5dHSwUcfxRyG3W7r1BHJFcToeBVhitv9aXGNHFoaJIn8biKeC

