import type { RoutingPolicySnapshotV1 } from './routing-policy.types';

/**
 * Audited baseline policy. Product names live here rather than in planners,
 * matchers, or topology code. Runtime policy patches may only add aliases.
 */
export const BUILTIN_ROUTING_POLICY: Omit<RoutingPolicySnapshotV1, 'digest'> = {
  schemaVersion: 'routing-policy/v1',
  version: 'builtin-2026-08-25',
  source: 'builtin',
  signals: {
    sequential: ['然后', '并且', '接着', '之后', '再', '最后', '以及', '并且对', '并'],
    processing: [
      '总结',
      '提炼',
      '翻译',
      '提取',
      '改写',
      '归纳',
      '分析',
      '推送',
      '通知',
      '发送',
      'bark',
      '拆分',
      '拆页',
      '分割',
      '合并',
      '拼接',
    ],
    generation: [
      '建议',
      '推荐',
      '解释',
      '说明',
      '评价',
      '评估',
      '判断',
      '对比',
      '比较',
      '拟定',
      '撰写',
      '写一',
      '写个',
      '写篇',
      '起草',
      '生成文案',
      '头脑风暴',
      '见解',
      '看法',
      '观点',
      '想法',
      '思考',
      '怎么看',
      '怎么想',
      '如何看',
      '如何理解',
      '有道理',
      '道理',
      '点评',
      '评析',
      '回答',
      '解答',
      '问答',
      '创作',
      'advice',
      'recommend',
      'explain',
      'draft',
      'compose',
      'brainstorm',
      'opinion',
    ],
    documentSource: [
      'pdf',
      '附件',
      '文档',
      'word',
      'docx',
      'ppt',
      'pptx',
      '文稿',
      '幻灯片',
      '讲义',
      '演示文稿',
      '文件',
      'document',
    ],
    webSource: ['网页', '网站', 'url', 'http', 'https'],
    artifact: [
      '输出 md',
      '输出md',
      '生成 md',
      '生成md',
      'md 文件',
      'md文件',
      'markdown 文件',
      'markdown文件',
      '输出文件',
      '生成文件',
      '保存为',
      '导出',
      '写到文件',
      '输出为',
      '生成 pdf',
      '生成pdf',
      '输出 pdf',
      '输出pdf',
      '导出 pdf',
      '导出pdf',
      '导出为 pdf',
      '导出为pdf',
      'pdf 文件',
      'pdf文件',
    ],
    search: [
      '搜索',
      'search',
      '查找',
      '查一下',
      '查询',
      '查看',
      '新闻',
      '最新',
      '查',
      'news',
      'latest',
      '检索',
      'doc',
      'workspace',
      'rag',
      '天气',
      '怎么样',
      '如何',
      '行情',
    ],
    summarize: ['总结', '摘要', '归纳', '概括', '汇总', '提炼', 'summarize', 'summary'],
    markdown: ['markdown', 'md', '文件', '文档', '报告'],
    uncoveredAction: [
      '推送',
      '通知',
      'bark',
      '发给',
      '发邮件',
      '发送邮件',
      '回复邮件',
      '发信',
      'webhook',
    ],
  },
  terminalActions: {
    bark: ['bark', 'bark推送'],
    email: ['邮件', 'email', 'e-mail'],
    sms: ['短信', 'sms'],
    markdown: ['markdown', '.md', '写入文档', '保存文档'],
    pdf: ['pdf', '导出pdf'],
  },
  capabilityRoles: {
    search: ['search', '搜索', 'explorer', 'workspace.explorer', '工作空间', '文档探索', '查询', 'query', '天气'],
    markdownWriter: ['markdown', '写'],
    documentExtractor: ['content-extractor', 'pdf', '内容提取'],
    webExtractor: ['打开网页', '网页正文', '网页内容', 'web extract', 'browser extract'],
    notifier: ['bark', '推送', '通知', 'notification', 'internal-message', '消息推送', '发信', '发送'],
  },
  intentNormalization: {
    equivalences: [
      { canonical: '查', aliases: ['查看', '查询', '获取'] },
      { canonical: '总结', aliases: ['给出总结', '进行总结', '汇总'] },
    ],
    stopWords: ['最后', '然后', '并且', '通过', '使用', '一下', '当前', '并', '用', '的'],
  },
};
