import {
  getBrowserWorkerUrl,
  getCarboneExternalUrl,
  getCarboneServiceUrl,
} from '../../config/service-endpoints';
import {
  extractBrowserActivityPlaceholders,
  normalizeBrowserActivitySteps,
} from './temporal-workflow-browser.helpers';
import type { ActivityDsl } from './temporal-workflow.types';

type NormalizedInputParam = { key: string; value: string; required: boolean };

type NormalizeInputParamsFn = (
  inputParams: Array<{ key?: string; value?: string; required?: boolean }> | Record<string, string> | undefined,
) => NormalizedInputParam[];

function durationToSeconds(duration: string | undefined, fallbackSeconds = 300): number {
  const normalized = String(duration || '').trim();
  const match = normalized.match(/^(\d+)\s*([smhd])$/i);
  if (!match) {
    return fallbackSeconds;
  }

  const value = Number(match[1]);
  const unit = match[2].toLowerCase();
  switch (unit) {
    case 'm':
      return value * 60;
    case 'h':
      return value * 60 * 60;
    case 'd':
      return value * 60 * 60 * 24;
    case 's':
    default:
      return value;
  }
}

export function buildDeterministicCarboneActivityCode(args: {
  activityDef: ActivityDsl['activities'][number];
  normalizeInputParams: NormalizeInputParamsFn;
}): string | null {
  const { activityDef, normalizeInputParams } = args;
  if (activityDef.handler !== 'carbone') {
    return null;
  }

  const steps = Array.isArray(activityDef.config?.steps) ? activityDef.config.steps : [];
  const carboneStep = steps.find((step: Record<string, any>) => step?.type === 'carbone');
  if (!carboneStep) {
    return null;
  }

  const inputParams = normalizeInputParams(carboneStep.inputParams);
  const renderAssignments = inputParams.map((param) => {
    const defaultValue = param.value || '';
    return `        ${JSON.stringify(param.key)}: _value(${JSON.stringify(param.key)}, ${JSON.stringify(defaultValue)}),`;
  });

  const requiredParams = inputParams.filter((param) => param.required).map((param) => param.key);
  const internalBaseExpr = activityDef.config?.internalBaseUrl
    ? JSON.stringify(String(activityDef.config.internalBaseUrl))
    : `(os.getenv("CARBONE_SERVICE_URL") or ${JSON.stringify(getCarboneServiceUrl())})`;
  const outputName = carboneStep.config?.outputName || '';
  const format = carboneStep.config?.format || 'docx';
  const templateId = carboneStep.config?.templateId || activityDef.config?.templateId || '';
  const skillId = carboneStep.config?.skillId || activityDef.config?.skillId || '';
  const defaultRequestTimeoutSeconds = durationToSeconds(activityDef.timeout, 300);

  return [
    'from typing import Any, Dict',
    '',
    'from temporalio import activity',
    'from temporalio.exceptions import ApplicationError',
    '',
    'import os',
    'import requests',
    '',
    `@activity.defn(name=${JSON.stringify(activityDef.fn)})`,
    `async def ${activityDef.fn}(input_data: Dict[str, Any]) -> Dict[str, Any]:`,
    '    if not isinstance(input_data, dict):',
    '        raise ApplicationError("input_data 必须是 dict", non_retryable=True)',
    '',
    '    def _value(key: str, default: str = "") -> str:',
    '        value = input_data.get(key, default)',
    '        if value is None:',
    '            return default',
    '        return str(value)',
    '',
    `    template_id = ${JSON.stringify(String(templateId))}`,
    `    skill_id = ${JSON.stringify(String(skillId))}`,
    `    output_format = ${JSON.stringify(String(format))}`,
    `    output_name = ${JSON.stringify(String(outputName))}`,
    '    request_timeout_seconds = input_data.get("requestTimeoutSeconds")',
    `    default_request_timeout_seconds = ${defaultRequestTimeoutSeconds}`,
    '    if request_timeout_seconds is None:',
    '        resolved_request_timeout_seconds = default_request_timeout_seconds',
    '    elif isinstance(request_timeout_seconds, bool) or not isinstance(request_timeout_seconds, (int, float)):',
    '        raise ApplicationError("requestTimeoutSeconds 参数必须是数字类型", non_retryable=True)',
    '    else:',
    '        resolved_request_timeout_seconds = float(request_timeout_seconds)',
    '    if resolved_request_timeout_seconds <= 0:',
    '        raise ApplicationError("requestTimeoutSeconds 参数必须大于 0", non_retryable=True)',
    '    render_data = {',
    ...renderAssignments,
    '    }',
    '',
    `    required_params = ${JSON.stringify(requiredParams)}`,
    '    missing_params = [key for key in required_params if not render_data.get(key, "").strip()]',
    '    if missing_params:',
    '        raise ApplicationError(f"缺少必需参数: {\', \'.join(missing_params)}", non_retryable=True)',
    '',
    '    def _normalize_base_url(value: Any) -> str:',
    '        normalized = str(value or "").strip()',
    '        while len(normalized) >= 2 and normalized[0] == normalized[-1] and normalized[0] in (\'"\', "\'", "`"):',
    '            normalized = normalized[1:-1].strip()',
    '        return normalized.rstrip("/")',
    '',
    `    external_base_url = _normalize_base_url(os.getenv("CARBONE_EXTERNAL_URL") or ${JSON.stringify(getCarboneExternalUrl())})`,
    '    if not template_id and not skill_id:',
    '        raise ApplicationError("templateId 或 skillId 至少需要提供一个", non_retryable=True)',
    '    payload = {',
    '        "data": render_data,',
    '        "outputFormat": output_format,',
    '    }',
    '    if template_id:',
    '        payload["templateId"] = template_id',
    '    if skill_id:',
    '        payload["skillId"] = skill_id',
    '    if output_name:',
    '        payload["outputName"] = output_name',
    '',
    '    def _prepare_render_payload(base_url: str) -> Dict[str, Any]:',
    '        standardize_url = base_url + "/studio/generate-render-data-with-skill"',
    '        standardize_payload = {',
    '            "simulatedData": render_data,',
    '            "outputFormat": output_format,',
    '        }',
    '        if template_id:',
    '            standardize_payload["templateId"] = template_id',
    '        if skill_id:',
    '            standardize_payload["skillId"] = skill_id',
    '        if output_name:',
    '            standardize_payload["outputName"] = output_name',
    '        try:',
    '            standardize_response = requests.post(',
    '                standardize_url,',
    '                json=standardize_payload,',
    '                timeout=resolved_request_timeout_seconds,',
    '            )',
    '            standardize_response.raise_for_status()',
    '            standardize_result = standardize_response.json()',
    '            render_resolved_request = standardize_result.get("renderResolvedRequest") if isinstance(standardize_result, dict) else None',
    '            if isinstance(render_resolved_request, dict) and isinstance(render_resolved_request.get("data"), dict):',
    '                return render_resolved_request',
    '        except requests.RequestException as exc:',
    '            activity.logger.warning("Carbone 标准数据生成失败，回退直渲染", extra={"error": str(exc), "standardizeUrl": standardize_url})',
    '        return payload',
    '',
    '    candidate_base_urls = []',
    `    configured_base_url = _normalize_base_url(${internalBaseExpr})`,
    '    if configured_base_url:',
    '        candidate_base_urls.append(configured_base_url)',
    `    default_base_url = _normalize_base_url(${JSON.stringify(getCarboneServiceUrl())})`,
    '    if default_base_url:',
    '        candidate_base_urls.append(default_base_url)',
    '    deduped_base_urls = []',
    '    for candidate in candidate_base_urls:',
    '        normalized_candidate = _normalize_base_url(candidate)',
    '        if normalized_candidate and normalized_candidate not in deduped_base_urls:',
    '            deduped_base_urls.append(normalized_candidate)',
    '',
    '    if not deduped_base_urls:',
    '        raise ApplicationError("未配置可用的 Carbone 服务地址", non_retryable=True)',
    '',
    '    last_error = None',
    '    render_result = None',
    '    resolved_payload = payload',
    '    for base_url in deduped_base_urls:',
    '        render_url = base_url + "/studio/render-resolved"',
    '        request_payload = _prepare_render_payload(base_url)',
    '        field_count = len(request_payload.get("data", {})) if isinstance(request_payload.get("data"), dict) else len(render_data)',
    '        activity.logger.info("开始调用 Carbone 渲染", extra={"templateId": template_id, "skillId": skill_id, "renderUrl": render_url, "requestTimeoutSeconds": resolved_request_timeout_seconds, "fieldCount": field_count})',
    '        try:',
    '            response = requests.post(render_url, json=request_payload, timeout=resolved_request_timeout_seconds)',
    '            response.raise_for_status()',
    '            activity.heartbeat("carbone_render_completed")',
    '            render_result = response.json()',
    '            resolved_payload = request_payload',
    '            break',
    '        except requests.RequestException as exc:',
    '            last_error = exc',
    '            activity.logger.error("Carbone 渲染失败，尝试下一个地址", extra={"error": str(exc), "renderUrl": render_url})',
    '',
    '    if render_result is None:',
    '        raise ApplicationError(f"Carbone 渲染失败: {str(last_error) if last_error else \'unknown error\'}", non_retryable=False)',
    '',
    '    download_url = render_result.get("downloadUrl")',
    '    if isinstance(download_url, str) and download_url.startswith("/"):',
    '        download_url = external_base_url + download_url',
    '    elif not isinstance(download_url, str) or not download_url.strip():',
    '        raise ApplicationError("Carbone 返回结果缺少 downloadUrl", non_retryable=True)',
    '',
    '    return {',
    '        "status": "rendered",',
    '        "templateId": resolved_payload.get("templateId") if isinstance(resolved_payload, dict) else template_id,',
    '        "skillId": resolved_payload.get("skillId") if isinstance(resolved_payload, dict) else skill_id,',
    '        "params_used": resolved_payload.get("data") if isinstance(resolved_payload, dict) else render_data,',
    '        "downloadUrl": download_url,',
    '        "fileName": render_result.get("fileName"),',
    '        "format": render_result.get("format", resolved_payload.get("outputFormat") if isinstance(resolved_payload, dict) else output_format),',
    '        "raw": render_result,',
    '    }',
    '',
  ].join('\n');
}

export function buildDeterministicBrowserActivityCode(args: {
  activityDef: ActivityDsl['activities'][number];
}): string | null {
  const { activityDef } = args;
  const steps = normalizeBrowserActivitySteps(activityDef.config?.steps);
  if (steps.length === 0) {
    return null;
  }

  const requiredParams = extractBrowserActivityPlaceholders(steps);
  const firstGotoStep = steps.find((step) => step.action === 'goto');
  const configuredInitialUrl = typeof firstGotoStep?.config?.url === 'string'
    ? firstGotoStep.config.url
    : '';
  const sessionLifecycle = activityDef.config?.sessionLifecycle && typeof activityDef.config.sessionLifecycle === 'object'
    ? activityDef.config.sessionLifecycle as { initializeSession?: boolean; cleanupSession?: boolean }
    : {};
  const initializeSession = sessionLifecycle.initializeSession !== false;
  const cleanupSession = sessionLifecycle.cleanupSession !== false;

  return [
    'from typing import Any, Dict',
    '',
    'from temporalio import activity',
    'from temporalio.exceptions import ApplicationError',
    '',
    'import os',
    'import re',
    'import uuid',
    'import requests',
    '',
    `@activity.defn(name=${JSON.stringify(activityDef.fn)})`,
    `async def ${activityDef.fn}(input_data: Dict[str, Any]) -> Dict[str, Any]:`,
    '    if not isinstance(input_data, dict):',
    '        raise ApplicationError("input_data 必须是 dict", non_retryable=True)',
    '',
    `    configured_steps = ${JSON.stringify(steps)}`,
    '    if not configured_steps:',
    '        raise ApplicationError("浏览器 Activity 缺少可执行步骤", non_retryable=True)',
    '',
    `    required_params = ${JSON.stringify(requiredParams)}`,
    `    browser_worker_base_url = (os.getenv("BROWSER_WORKER_URL") or ${JSON.stringify(getBrowserWorkerUrl())}).rstrip("/")`,
    '    requested_backend = str(input_data.get("backend") or os.getenv("BROWSER_EXECUTION_BACKEND") or "cli").strip() or "cli"',
    '    runtime_session_id = str(input_data.get("runtimeSessionId") or "").strip() or f"temporal-browser-{uuid.uuid4().hex}"',
    `    configured_initial_url = ${JSON.stringify(configuredInitialUrl)}`,
    `    initialize_session = ${initializeSession ? 'True' : 'False'}`,
    `    cleanup_session = ${cleanupSession ? 'True' : 'False'}`,
    '',
    '    def _stringify(value: Any) -> str:',
    '        if value is None:',
    '            return ""',
    '        if isinstance(value, bool):',
    '            return "true" if value else "false"',
    '        return str(value)',
    '',
    '    def _is_missing(value: Any) -> bool:',
    '        if value is None:',
    '            return True',
    '        if isinstance(value, str):',
    '            return not value.strip()',
    '        return False',
    '',
    '    def _resolve_text(template: str) -> str:',
    '        if not isinstance(template, str) or not template:',
    '            return ""',
    '',
    '        def _replace_braced(match: re.Match[str]) -> str:',
    '            key = str(match.group(1) or "").strip()',
    '            if not key:',
    '                return match.group(0)',
    '            value = input_data.get(key)',
    '            return match.group(0) if value is None else _stringify(value)',
    '',
    '        def _replace_dollar(match: re.Match[str]) -> str:',
    '            key = str(match.group(1) or "").strip()',
    '            if not key:',
    '                return match.group(0)',
    '            value = input_data.get(key)',
    '            return match.group(0) if value is None else _stringify(value)',
    '',
    '        rendered = re.sub(r"\\$\\{([^{}]+)\\}", _replace_dollar, template)',
    '        return re.sub(r"\\{([^{}]+)\\}", _replace_braced, rendered)',
    '',
    '    def _resolve_value(value: Any) -> Any:',
    '        if isinstance(value, str):',
    '            return _resolve_text(value)',
    '        if isinstance(value, list):',
    '            return [_resolve_value(item) for item in value]',
    '        if isinstance(value, dict):',
    '            return {str(key): _resolve_value(item) for key, item in value.items()}',
    '        return value',
    '',
    '    def _build_target_from_locator(locator: Any) -> str:',
    '        if not isinstance(locator, dict):',
    '            return ""',
    '        locator_type = _stringify(locator.get("type")).strip().lower()',
    '        locator_value = _stringify(locator.get("value")).strip()',
    '        if not locator_value:',
    '            return ""',
    '        if locator_type == "ref":',
    '            return locator_value',
    '        if locator_type == "role":',
    '            return f"role={locator_value}"',
    '        if locator_type == "text":',
    '            return f"text={locator_value}"',
    '        if locator_type == "test-id":',
    '            return f"[data-testid=\\"{locator_value}\\"]"',
    '        if locator_type == "xpath":',
    '            return f"xpath={locator_value}"',
    '        return locator_value',
    '',
    '    def _normalize_target(raw: Any) -> str:',
    '        target = _stringify(raw).strip()',
    '        if not target:',
    '            return ""',
    '        if re.match(r"^[a-zA-Z-]+\\[name=.*\\]$", target) and "=" not in target.split("[", 1)[0]:',
    '            return f"role={target}"',
    '        return target',
    '',
    '    def _is_retryable_error(message: str) -> bool:',
    '        if not isinstance(message, str) or not message.strip():',
    '            return False',
    '        return bool(re.search(r"does not match any elements|No element found|strict mode violation|timeout|timed out|net::|ECONNRESET|temporarily unavailable", message, re.IGNORECASE))',
    '',
    '    def _should_require_takeover(command: str, message: str) -> bool:',
    '        combined = f"{command} {message}" if command or message else ""',
    '        if re.search(r"captcha|mfa|2fa|verification|verify|human verification|验证码|二次认证", combined, re.IGNORECASE):',
    '            return True',
    '        if not isinstance(message, str) or not message.strip():',
    '            return False',
    '        if re.search(r"does not match any elements|No element found|strict mode violation", message, re.IGNORECASE):',
    '            return command in ("click", "fill", "type", "type_text", "press", "press_key", "click_result")',
    '        return False',
    '',
    '    missing_params = [key for key in required_params if _is_missing(input_data.get(key))]',
    '    if missing_params:',
    '        raise ApplicationError(f"缺少必需参数: {\', \'.join(missing_params)}", non_retryable=True)',
    '',
    '    def _build_command(step: Dict[str, Any]) -> Dict[str, Any]:',
    '        action = str(step.get("action") or "").strip()',
    '        config = _resolve_value(step.get("config") or {})',
    '        if action in ("goto", "navigate"):',
    '            url = _stringify(config.get("url") or config.get("target"))',
    '            if not url:',
    '                raise ApplicationError("浏览器步骤 goto 缺少 url", non_retryable=True)',
    '            return {"tool": "navigate", "params": {"url": url}}',
    '        if action in ("click", "hover"):',
    '            target = _build_target_from_locator(config.get("locator"))',
    '            if not target:',
    '                target = _normalize_target(config.get("selector"))',
    '            if not target:',
    '                target = _normalize_target(config.get("target"))',
    '            if not target:',
    '                target = _stringify(config.get("text"))',
    '            if not target:',
    '                raise ApplicationError("浏览器步骤 click 缺少 selector", non_retryable=True)',
    '            return {"tool": action, "params": {"target": target}}',
    '        if action in ("fill", "type", "type_text"):',
    '            target = _build_target_from_locator(config.get("locator"))',
    '            if not target:',
    '                target = _normalize_target(config.get("selector"))',
    '            if not target:',
    '                target = _normalize_target(config.get("target"))',
    '            if not target:',
    '                raise ApplicationError("浏览器步骤 fill 缺少 selector", non_retryable=True)',
    '            value = _stringify(config.get("value") or config.get("text") or config.get("query"))',
    '            return {"tool": action, "params": {"target": target, "value": value, "text": value}}',
    '        if action in ("press", "press_key"):',
    '            key = _stringify(config.get("key") or config.get("value"))',
    '            if not key:',
    '                raise ApplicationError("浏览器步骤 press 缺少按键值", non_retryable=True)',
    '            params = {"key": key}',
    '            target = _build_target_from_locator(config.get("locator"))',
    '            if not target:',
    '                target = _normalize_target(config.get("selector"))',
    '            if not target:',
    '                target = _normalize_target(config.get("target"))',
    '            if target:',
    '                params["target"] = target',
    '            return {"tool": "press_key", "params": params}',
    '        if action in ("search", "smart_search"):',
    '            query = _stringify(config.get("query") or config.get("text") or config.get("value"))',
    '            if not query:',
    '                raise ApplicationError("浏览器步骤 smart_search 缺少 query", non_retryable=True)',
    '            return {"tool": action, "params": {"query": query}}',
    '        if action == "click_result":',
    '            index = config.get("index")',
    '            if isinstance(index, str) and index.strip().isdigit():',
    '                index = int(index.strip())',
    '            if not isinstance(index, int) or index <= 0:',
    '                index = 1',
    '            return {"tool": "click_result", "params": {"index": index}}',
    '        if action == "waitForSelector":',
    '            selector = _stringify(config.get("selector"))',
    '            if not selector:',
    '                raise ApplicationError("浏览器步骤 waitForSelector 缺少 selector", non_retryable=True)',
    '            duration = config.get("timeoutMs") or config.get("duration")',
    '            if isinstance(duration, str) and duration.strip().isdigit():',
    '                duration = int(duration.strip())',
    '            if not isinstance(duration, int) or duration <= 0:',
    '                duration = 30000',
    '            return {"tool": "wait", "params": {"selector": selector, "duration": duration}}',
    '        if action in ("waitForTimeout", "wait"):',
    '            selector = _stringify(config.get("selector") or config.get("target"))',
    '            duration = config.get("timeoutMs") or config.get("duration")',
    '            if isinstance(duration, str) and duration.strip().isdigit():',
    '                duration = int(duration.strip())',
    '            if not isinstance(duration, int) or duration <= 0:',
    '                duration = 1000',
    '            params = {"duration": duration}',
    '            if selector:',
    '                params["selector"] = selector',
    '            return {"tool": "wait", "params": params}',
    '        if action in ("screenshot", "snapshot", "read_page", "get_text", "switch_latest_tab", "focus_latest_page"):',
    '            return {"tool": action, "params": {k: v for k, v in config.items() if k != "action"}}',
    '        raise ApplicationError(f"暂不支持的浏览器动作: {action}", non_retryable=True)',
    '',
    '    commands = [_build_command(step) for step in configured_steps]',
    '    initial_url = _resolve_text(_stringify(input_data.get("initialUrl")) or configured_initial_url)',
    '    backend_candidates = [requested_backend, "cli", "chrome-devtools"]',
    '    ordered_backends = []',
    '    for backend_name in backend_candidates:',
    '        normalized_backend = str(backend_name or "").strip()',
    '        if normalized_backend and normalized_backend not in ordered_backends:',
    '            ordered_backends.append(normalized_backend)',
    '',
    '    selected_backend = requested_backend',
    '    init_error_message = ""',
    '',
    '    try:',
    '        if initialize_session:',
    '            selected_backend = ""',
    '            for backend in ordered_backends:',
    '                init_payload: Dict[str, Any] = {',
    '                    "runtimeSessionId": runtime_session_id,',
    '                    "backend": backend,',
    '                    "sessionPreferences": {',
    '                        "mode": "agent",',
    '                        "enableCodegen": False,',
    '                        "headless": True,',
    '                    },',
    '                }',
    '                if initial_url:',
    '                    init_payload["initialUrl"] = initial_url',
    '',
    '                activity.logger.info("开始初始化浏览器执行会话", extra={"runtimeSessionId": runtime_session_id, "backend": backend, "commandCount": len(commands)})',
    '                try:',
    '                    init_response = requests.post(f"{browser_worker_base_url}/browser/init", json=init_payload, timeout=60)',
    '                    init_response.raise_for_status()',
    '                    candidate_result = init_response.json()',
    '                except requests.RequestException as exc:',
    '                    init_error_message = str(exc)',
    '                    activity.logger.warning("browser-worker 初始化请求失败，尝试下一个 backend", extra={"backend": backend, "error": init_error_message})',
    '                    continue',
    '',
    '                if bool(candidate_result.get("success")):',
    '                    selected_backend = backend',
    '                    break',
    '',
    '                init_error_message = str(candidate_result.get("message") or "unknown error")',
    '                activity.logger.warning("browser-worker 初始化失败，尝试下一个 backend", extra={"backend": backend, "error": init_error_message})',
    '',
    '            if not selected_backend:',
    '                raise ApplicationError(f"browser-worker 初始化失败: {init_error_message or \'unknown error\'}", non_retryable=False)',
    '',
    '            activity.heartbeat("browser_init_completed")',
    '',
    '        preserve_session = False',
    '        execute_payload = {',
    '            "runtimeSessionId": runtime_session_id,',
    '            "backend": selected_backend,',
    '            "commands": commands,',
    '            "includeArtifacts": False,',
    '            "includeSteps": True,',
    '        }',
    '        activity.logger.info("开始执行浏览器模板命令", extra={"runtimeSessionId": runtime_session_id, "backend": selected_backend})',
    '        try:',
    '            execute_response = requests.post(f"{browser_worker_base_url}/browser/execute", json=execute_payload, timeout=120)',
    '            execute_response.raise_for_status()',
    '            execute_result = execute_response.json()',
    '        except requests.RequestException as exc:',
    '            raise ApplicationError(f"browser-worker 执行失败: {exc}", non_retryable=False)',
    '',
    '        raw_results = execute_result.get("results") or []',
    '        if not isinstance(raw_results, list):',
    '            raw_results = []',
    '        failed_results = [item for item in raw_results if isinstance(item, dict) and str(item.get("status") or "").lower() == "error"]',
    '        summarized_results = []',
    '        artifact_refs = []',
    '        for item in raw_results:',
    '            if not isinstance(item, dict):',
    '                continue',
    '            summary = {',
    '                "status": item.get("status"),',
    '                "command": item.get("command"),',
    '                "message": item.get("message"),',
    '                "pageUrl": item.get("pageUrl"),',
    '                "pageTitle": item.get("pageTitle"),',
    '                "pageFingerprint": item.get("pageFingerprint"),',
    '            }',
    '            snapshot = item.get("snapshot")',
    '            if isinstance(snapshot, dict):',
    '                snapshot_id = snapshot.get("id")',
    '                snapshot_path = snapshot.get("path")',
    '                if (isinstance(snapshot_id, str) and snapshot_id) or (isinstance(snapshot_path, str) and snapshot_path):',
    '                    summary["snapshot"] = {}',
    '                    if isinstance(snapshot_id, str) and snapshot_id:',
    '                        summary["snapshot"]["id"] = snapshot_id',
    '                    if isinstance(snapshot_path, str) and snapshot_path:',
    '                        summary["snapshot"]["path"] = snapshot_path',
    '            data = item.get("data")',
    '            if isinstance(data, dict):',
    '                text_value = data.get("text")',
    '                if isinstance(text_value, str) and text_value:',
    '                    summary["data"] = {',
    '                        "text": text_value[:500],',
    '                    }',
    '                artifact_path = data.get("path") or data.get("screenshotPath")',
    '                if isinstance(artifact_path, str) and artifact_path:',
    '                    summary["artifact"] = {',
    '                        "path": artifact_path,',
    '                    }',
    '            snapshot_ref = summary.get("snapshot")',
    '            artifact_ref = summary.get("artifact")',
    '            if isinstance(snapshot_ref, dict) or isinstance(artifact_ref, dict):',
    '                artifact_record = {',
    '                    "command": summary.get("command"),',
    '                    "status": summary.get("status"),',
    '                }',
    '                if isinstance(snapshot_ref, dict):',
    '                    artifact_record["snapshot"] = snapshot_ref',
    '                if isinstance(artifact_ref, dict):',
    '                    artifact_record["artifact"] = artifact_ref',
    '                artifact_refs.append(artifact_record)',
    '            summarized_results.append(summary)',
    '',
    '        first_command = ""',
    '        first_message = ""',
    '        failure_message = ""',
    '        if failed_results:',
    '            first_error = failed_results[0]',
    '            first_command = str(first_error.get("command") or "unknown")',
    '            first_message = str(first_error.get("message") or "unknown error")',
    '            failure_message = f"browser-worker 执行失败: {execute_result.get(\'message\') or \'unknown error\'}; first_failed_command={first_command}; detail={first_message}"',
    '        elif not bool(execute_result.get("success")):',
    '            failure_message = f"browser-worker 执行失败: {execute_result.get(\'message\') or \'unknown error\'}"',
    '',
    '        if failure_message:',
    '            requires_takeover = _should_require_takeover(first_command, first_message or failure_message)',
    '            if requires_takeover:',
    '                preserve_session = True',
    '            return {',
    '                "status": "takeover_required" if requires_takeover else "failed",',
    '                "runtimeSessionId": runtime_session_id,',
    '                "backend": selected_backend,',
    '                "commandCount": len(commands),',
    '                "results": summarized_results,',
    '                "artifacts": artifact_refs,',
    '                "message": execute_result.get("message"),',
    '                "errorCode": "BROWSER_WORKER_EXECUTION_FAILED",',
    '                "errorMessage": failure_message,',
    '                "failedCommand": first_command or None,',
    '                "retryable": _is_retryable_error(first_message or failure_message),',
    '                "requiresTakeover": requires_takeover,',
    '                "takeoverReason": (f"浏览器页面未进入预期状态，无法继续执行 {first_command or \'当前步骤\'}" if requires_takeover else None),',
    '            }',
    '',
    '        activity.heartbeat("browser_execute_completed")',
    '        return {',
    '            "status": "completed",',
    '            "runtimeSessionId": runtime_session_id,',
    '            "backend": selected_backend,',
    '            "commandCount": len(commands),',
    '            "results": summarized_results,',
    '            "artifacts": artifact_refs,',
    '            "message": execute_result.get("message"),',
    '        }',
    '    finally:',
    '        if cleanup_session and not preserve_session:',
    '            activity.logger.info("清理浏览器会话资源", extra={"runtimeSessionId": runtime_session_id})',
    '            try:',
    '                requests.post(f"{browser_worker_base_url}/browser/reset", json={"runtimeSessionId": runtime_session_id}, timeout=30)',
    '            except Exception as exc:',
    '                activity.logger.warning("清理浏览器会话失败 (可能已自动释放)", extra={"runtimeSessionId": runtime_session_id, "error": str(exc)})',
    '',
  ].join('\n');
}
