#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$DOCKER_DIR")"
DOCKER_ENV_FILE="$DOCKER_DIR/.env"

OUTPUT_PATH="${1:-$REPO_ROOT/docker/sql/exports/platform-initial-data-$(date +%Y%m%d-%H%M%S).sql}"

EXPORT_TABLES=(
  "roles"
  "users"
  "user_roles"
  "organizations"
  "departments"
  "teams"
  "org_memberships"
  "team_memberships"
  "org_role_bindings"
  "identity_provider_configs"
  "execution_flow_templates"
  "skill_configs"
  "skill_permissions"
  "tool_catalogs"
  "skill_tool_bindings"
  "activities"
  "temporal_workflows"
)

log() {
  printf '[export-initial-data] %s\n' "$1"
}

load_db_params() {
  POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-ops-postgres}"
  POSTGRES_USER="${POSTGRES_USER:-ops}"
  POSTGRES_DB="${POSTGRES_DB:-ops}"

  if [[ -f "$DOCKER_ENV_FILE" ]]; then
    local pg_user pg_db
    pg_user="$(grep -E '^POSTGRES_USER=' "$DOCKER_ENV_FILE" 2>/dev/null | tail -1 | cut -d'=' -f2-)"
    pg_db="$(grep -E '^POSTGRES_DB=' "$DOCKER_ENV_FILE" 2>/dev/null | tail -1 | cut -d'=' -f2-)"
    pg_user="${pg_user%$'\r'}"
    pg_db="${pg_db%$'\r'}"
    pg_user="${pg_user%\"}"
    pg_user="${pg_user#\"}"
    pg_db="${pg_db%\"}"
    pg_db="${pg_db#\"}"
    [[ -n "$pg_user" ]] && POSTGRES_USER="$pg_user"
    [[ -n "$pg_db" ]] && POSTGRES_DB="$pg_db"
  fi
}

psql_query() {
  local query="$1"
  docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tAc "$query"
}

table_exists() {
  local table_name="$1"
  local count
  count="$(psql_query "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public' AND table_name='${table_name}'" 2>/dev/null || echo "0")"
  [[ "${count:-0}" -gt 0 ]]
}

build_pg_dump_table_args() {
  local table_name
  local -a table_args=()

  for table_name in "${EXPORT_TABLES[@]}"; do
    if table_exists "$table_name"; then
      table_args+=("--table=public.${table_name}")
    fi
  done

  if [[ ${#table_args[@]} -eq 0 ]]; then
    log "No exportable initial-data tables were found in the current database."
    return 1
  fi

  printf '%s\n' "${table_args[@]}"
}

main() {
  load_db_params

  if ! docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^${POSTGRES_CONTAINER}$"; then
    log "Postgres container '${POSTGRES_CONTAINER}' is not running."
    exit 1
  fi

  mkdir -p "$(dirname "$OUTPUT_PATH")"

  local -a PG_DUMP_TABLE_ARGS=()
  while IFS= read -r table_arg; do
    PG_DUMP_TABLE_ARGS+=("$table_arg")
  done < <(build_pg_dump_table_args)

  {
    printf -- '-- Generated by docker/scripts/export-initial-data.sh\n'
    printf -- '-- Source database: %s\n' "$POSTGRES_DB"
    printf -- '-- Generated at: %s\n\n' "$(date '+%Y-%m-%d %H:%M:%S')"
    printf 'SET statement_timeout = 0;\n'
    printf 'SET lock_timeout = 0;\n'
    printf 'SET idle_in_transaction_session_timeout = 0;\n'
    printf 'SET client_encoding = '\''UTF8'\'';\n'
    printf 'SET standard_conforming_strings = on;\n'
    printf '\n'
    docker exec "$POSTGRES_CONTAINER" pg_dump \
      -U "$POSTGRES_USER" \
      -d "$POSTGRES_DB" \
      --data-only \
      --column-inserts \
      --no-owner \
      --no-privileges \
      "${PG_DUMP_TABLE_ARGS[@]}"
  } > "$OUTPUT_PATH"

  log "Initial data exported to: $OUTPUT_PATH"
}

main
