export const buildExecutionDetailText = (isEnglish: boolean) => ({
  loading: isEnglish ? 'Loading execution...' : '正在加载执行详情...',
  loadFailed: isEnglish ? 'Failed to load execution' : '加载执行详情失败',
  notFound: isEnglish ? 'Execution not found' : '未找到执行记录',
  backToExecutions: isEnglish ? 'Back to Executions' : '返回执行列表',
  enterTakeoverMode: isEnglish ? 'Enter Takeover Mode' : '进入接管模式',
  details: isEnglish ? 'Execution Details' : '执行详情',
  idLabel: isEnglish ? 'ID' : '执行单 ID',
  takeoverRequired: isEnglish ? 'Human Takeover Required' : '需要人工接管',
  takeoverDescDefault: isEnglish
    ? 'The execution requires human intervention.'
    : '该执行需要人工介入处理。',
  takeoverApproveAndContinue: isEnglish ? 'Approve And Continue' : '同意并继续',
  takeoverApproveSuccess: isEnglish
    ? 'Human review accepted, execution resumed'
    : '已同意人工处理结果，执行继续中',
  takeoverApproveFailed: isEnglish ? 'Failed to continue execution' : '继续执行失败',
  approvalRequired: isEnglish ? 'Approval Required' : '需要审批',
  approvalWaiting: isEnglish ? 'Execution is waiting for approval' : '执行正在等待审批',
  approvalStatusPrefix: isEnglish ? 'Current approval status:' : '当前审批状态：',
  approvalDescDefault: isEnglish
    ? 'Review the execution details and decide whether it can continue.'
    : '请先查看执行详情，再决定是否允许继续执行。',
  approveAndContinue: isEnglish ? 'Approve And Continue' : '批准并继续执行',
  rejectExecution: isEnglish ? 'Reject Execution' : '拒绝执行',
  missingInputRequired: isEnglish ? 'Missing Input Required' : '需要补充输入',
  waitingInput: isEnglish ? 'Execution is waiting for additional input' : '执行正在等待补充输入',
  waitingInputDesc: isEnglish
    ? 'Fill in the missing parameters below to resume execution.'
    : '请填写下面缺失的参数后恢复执行。',
  invalidJson: isEnglish ? 'Invalid JSON input' : 'JSON 输入格式无效',
  submitAndResume: isEnglish ? 'Submit And Resume' : '提交并恢复执行',
  reset: isEnglish ? 'Reset' : '重置',
  status: isEnglish ? 'Status' : '状态',
  skillId: isEnglish ? 'Skill ID' : '技能标识',
  runtimeType: isEnglish ? 'Runtime Type' : '运行时类型',
  riskLevel: isEnglish ? 'Risk Level' : '风险等级',
  approvalStatus: isEnglish ? 'Approval Status' : '审批状态',
  createdBy: isEnglish ? 'Created By' : '创建人',
  createdAt: isEnglish ? 'Created At' : '创建时间',
  startedAt: isEnglish ? 'Started At' : '开始时间',
  endedAt: isEnglish ? 'Ended At' : '结束时间',
  failureReason: isEnglish ? 'Failure Reason' : '失败原因',
  failureCode: isEnglish ? 'Failure Code' : '失败代码',
  inputOutput: isEnglish ? 'Input & Output' : '输入与输出',
  input: isEnglish ? 'Input' : '输入',
  result: isEnglish ? 'Result' : '结果',
  stepsProgress: isEnglish ? 'Steps Progress' : '步骤进度',
  stepsDetails: isEnglish ? 'Steps Details' : '步骤详情',
  noSteps: isEnglish ? 'No steps recorded' : '暂无步骤记录',
  inputSubmitted: isEnglish ? 'Input submitted and execution resumed' : '输入已提交，执行已恢复',
  submitInputFailed: isEnglish ? 'Failed to submit input' : '提交输入失败',
  executionApproved: isEnglish ? 'Execution approved' : '执行已批准',
  approveFailed: isEnglish ? 'Failed to approve execution' : '批准执行失败',
  executionRejected: isEnglish ? 'Execution rejected' : '执行已拒绝',
  rejectFailed: isEnglish ? 'Failed to reject execution' : '拒绝执行失败',
  provideField: isEnglish ? 'Please provide' : '请输入',
  enterJsonString: isEnglish ? 'Enter JSON string' : '请输入 JSON 字符串',
  enterField: isEnglish ? 'Enter' : '请输入',
  source: isEnglish ? 'Source' : '来源',
  step: isEnglish ? 'Step' : '步骤',
  name: isEnglish ? 'Name' : '名称',
  type: isEnglish ? 'Type' : '类型',
  action: isEnglish ? 'Action' : '动作',
  error: isEnglish ? 'Error' : '错误',
  duration: isEnglish ? 'Duration' : '耗时',
  browserExecutionResult: isEnglish ? 'Browser Execution Result' : '浏览器执行结果',
  browserRuntimeInfo: isEnglish ? 'Browser Runtime Info' : '浏览器运行信息',
  browserSteps: isEnglish ? 'Browser Steps' : '浏览器步骤结果',
  browserStepOutput: isEnglish ? 'Step Output' : '步骤输出',
  browserSnapshotId: isEnglish ? 'Snapshot ID' : '快照 ID',
  browserTarget: isEnglish ? 'Target' : '目标',
  browserBackend: isEnglish ? 'Backend' : '执行后端',
  browserRuntimeSessionId: isEnglish ? 'Runtime Session' : '运行会话',
  browserStepCount: isEnglish ? 'Step Count' : '步骤数',
  browserFailedStep: isEnglish ? 'Failed Step' : '失败步骤',
  browserFailedAction: isEnglish ? 'Failed Action' : '失败动作',
  browserAuditEvidence: isEnglish ? 'Audit & Takeover Evidence' : '审计与接管证据',
  browserExecutionPlanVersion: isEnglish ? 'Plan Version' : '计划版本',
  browserDegradedMode: isEnglish ? 'Degraded Mode' : '退化模式',
  browserDegradeReason: isEnglish ? 'Degrade Reason' : '退化原因',
  browserCurrentStepId: isEnglish ? 'Current Step ID' : '当前步骤 ID',
  browserCurrentLoopIteration: isEnglish ? 'Loop Iteration' : '循环轮次',
  browserCurrentRiskLevel: isEnglish ? 'Current Risk' : '当前风险',
  browserRiskReason: isEnglish ? 'Risk Reason' : '风险原因',
  browserTakeoverReason: isEnglish ? 'Takeover Reason' : '接管原因',
  browserLastReadValue: isEnglish ? 'Last Read Value' : '最近读取值',
  browserLastBranchDecision: isEnglish ? 'Last Branch Decision' : '最近分支判断',
  browserTraceability: isEnglish ? 'Traceability' : '链路追踪',
  browserRecorderSessionId: isEnglish ? 'Recorder Session' : '录制会话',
  browserExportArtifactId: isEnglish ? 'Export Artifact' : '导出产物',
  browserReleaseId: isEnglish ? 'Release ID' : '发布版本',
  browserSkillDraftId: isEnglish ? 'Skill Draft' : '技能草稿',
  browserPublishedSkillId: isEnglish ? 'Published Skill' : '已发布技能',
  browserRuntimeExecutionId: isEnglish ? 'Runtime Execution' : '运行时执行 ID',
  browserNoOutput: isEnglish ? 'No structured output' : '暂无结构化输出',
  phaseTimeline: isEnglish ? 'Phase Timeline' : '阶段时间线',
  currentPhase: isEnglish ? 'Current Phase' : '当前阶段',
  currentActivity: isEnglish ? 'Current Activity' : '当前 Activity',
  activityProgress: isEnglish ? 'Activity Progress' : 'Activity 进度',
  activityKey: isEnglish ? 'Activity Key' : 'Activity Key',
  activityRetryOrResume: isEnglish ? 'Retry / Resume' : '重试 / 继续',
  activityTakeoverHint: isEnglish
    ? 'Take over this activity before retrying'
    : '如需重试该 Activity，请先接管后继续',
  phaseType: isEnglish ? 'Phase Type' : '阶段类型',
  phaseAttempt: isEnglish ? 'Attempt' : '尝试次数',
  phaseRuntimeSession: isEnglish ? 'Phase Session' : '阶段会话',
  phaseArtifacts: isEnglish ? 'Phase Artifacts' : '阶段产物',
  phaseArtifactCount: isEnglish ? 'Artifact Count' : '产物数量',
  phaseArtifactType: isEnglish ? 'Artifact Type' : '产物类型',
  phaseArtifactCommand: isEnglish ? 'Command' : '命令',
  phaseArtifactStatus: isEnglish ? 'Artifact Status' : '产物状态',
  phaseArtifactPath: isEnglish ? 'Artifact Path' : '产物路径',
  phaseArtifactSnapshotId: isEnglish ? 'Snapshot ID' : '快照 ID',
  phaseArtifactPageFingerprint: isEnglish ? 'Page Fingerprint' : '页面指纹',
  phaseNoData: isEnglish ? 'No phase records' : '暂无阶段记录',
  executionEnded: isEnglish ? 'Execution ended' : '执行已结束',
  endExecution: isEnglish ? 'End Execution' : '结束执行',
  phaseActionFailed: isEnglish ? 'Phase action failed' : '阶段操作失败',
  semanticOverview: isEnglish ? 'Semantic Overview' : '语义摘要',
  semanticMode: isEnglish ? 'Semantic Mode' : '语义模式',
  semanticSummary: isEnglish ? 'Semantic Summary' : '语义总结',
  previewReady: isEnglish ? 'Preview Ready' : '可预览',
  finalReady: isEnglish ? 'Final Ready' : '可正式生成',
  groupedMissing: isEnglish ? 'Missing Business Groups' : '缺失业务组',
  complexity: isEnglish ? 'Complexity' : '复杂度',
  missingFields: isEnglish ? 'Missing Fields' : '缺失字段数',
  arrayGroups: isEnglish ? 'Array Groups' : '数组组数',
  waitingInputSemanticHint: isEnglish ? 'Business-group hint' : '业务组提示',
  yes: isEnglish ? 'Yes' : '是',
  no: isEnglish ? 'No' : '否',
  groupLabel: isEnglish ? 'Group' : '分组',
  fieldLabel: isEnglish ? 'Field' : '字段',
  blockingLabel: isEnglish ? 'Blocking' : '阻塞',
  previewOkLabel: isEnglish ? 'Preview OK' : '可先预览',
  phaseSteps: isEnglish ? 'Phase Steps' : '阶段步骤',
  phaseStepIndex: isEnglish ? 'Index' : '序号',
  phaseStepAction: isEnglish ? 'Action' : '动作',
  phaseStepStatus: isEnglish ? 'Status' : '状态',
  phaseStepSnapshot: isEnglish ? 'Snapshot' : '快照',
  phaseStepDuration: isEnglish ? 'Duration' : '耗时',
  executionResult: isEnglish ? 'Execution Result' : '执行结果',
  humanReview: isEnglish ? 'Human Review' : '人工审查',
  reviewDecision: isEnglish ? 'Review Decision' : '审查结论',
  reviewPhase: isEnglish ? 'Review Phase' : '审查阶段',
  reviewedAt: isEnglish ? 'Reviewed At' : '审查时间',
  reviewContext: isEnglish ? 'Review Context' : '审查背景',
  reviewed: isEnglish ? 'Reviewed' : '已审查',
  manualReviewPending: isEnglish ? 'Waiting for Manual Review' : '待人工处理',
  openCurrentPage: isEnglish ? 'Open Current Page' : '打开当前页面',
  currentPageLink: isEnglish ? 'Current Page' : '当前页面',
  summaryInfo: isEnglish ? 'Summary' : '概要信息',
  operationsArea: isEnglish ? 'Operations' : '操作区域',
  runtimeInfo: isEnglish ? 'Runtime' : '运行时',
  thresholdSetting: isEnglish ? 'Threshold' : '阈值',
  noPendingActions: isEnglish ? 'No pending operations at the moment.' : '当前没有待处理操作。',
  expandPhaseTimeline: isEnglish ? 'Expand phase timeline' : '展开阶段时间线',
  currentStepLabel: isEnglish ? 'Current Step' : '当前步骤',
  currentStepHint: isEnglish
    ? 'Showing the step that is currently being executed.'
    : '展示当前正在执行的步骤。',
  executionSummaryTitle: isEnglish ? 'Execution Summary' : '执行总结',
  executionSummaryHint: isEnglish
    ? 'Showing the final outcome and key information after execution ends.'
    : '执行结束后，展示最终结果和关键信息。',
  detailButton: isEnglish ? 'Detail' : '详细',
  skillLabel: isEnglish ? 'Skill' : '技能',
  processingSummary: isEnglish ? 'Processing Summary' : '处理概要信息',
  progressOverview: isEnglish ? 'Progress' : '进度',
  totalActivities: isEnglish ? 'Total Activities' : '总阶段数',
  completedActivities: isEnglish ? 'Completed' : '已完成',
  pendingActivities: isEnglish ? 'Pending' : '待处理',
  loopCount: isEnglish ? 'Loops' : '轮次',
  processedItems: isEnglish ? 'Processed Items' : '处理条数',
  autoApprovedItems: isEnglish ? 'Auto Approved' : '自动承认',
  manualHandledItems: isEnglish ? 'Manual Handling' : '人工处理',
  manualHandledFlag: isEnglish ? 'Manual Intervention' : '人工介入',
  latestUpdate: isEnglish ? 'Latest Update' : '最近更新',
  noSummary: isEnglish ? 'No summary available.' : '暂无总结信息。',
});
