import { PrismaService } from '../../prisma/prisma.service';
import { BrowserRuntimeAdapter } from '../adapters/browser-runtime.adapter';
import { ExecutionRuntimeSessionService } from '../adapters/execution-runtime-session.service';
import { ExecutionCreateService } from '../creation/execution-create.service';
import { ExecutionApprovalService } from '../human-control/execution-approval.service';
import { ExecutionHumanControlService } from '../human-control/execution-human-control.service';
import { ExecutionInputResolutionService } from '../human-control/execution-input-resolution.service';
import { ExecutionSubmitInputService } from '../human-control/execution-submit-input.service';
import { ExecutionLifecycleService } from '../lifecycle/execution-lifecycle.service';
import { ExecutionStreamService } from '../lifecycle/execution-stream.service';
import { ExecutionQueryService } from '../query/execution-query.service';
import { ExecutionFailureService } from '../recovery/execution-failure.service';
import { ExecutionApplicationHooksService } from './execution-application-hooks.service';
import { ExecutionBrowserOrchestrationService } from '../step-runner/browser/execution-browser-orchestration.service';
import { BrowserPhaseExecutor } from '../step-runner/browser/browser-phase.executor';
import { ExecutionBrowserReadService } from '../step-runner/browser/execution-browser-read.service';
import { ExecutionFlowRunnerService } from '../step-runner/flow/execution-flow-runner.service';
import { ExecutionStartService } from '../step-runner/flow/execution-start.service';
import { ExecutionStepExecutorService } from '../step-runner/flow/execution-step-executor.service';
import { ExecutionPlanNormalizationService } from '../step-runner/planning/execution-plan-normalization.service';
import { ExecutionPlanningService } from '../step-runner/planning/execution-planning.service';
import { ExecutionRuntimeControlService } from '../step-runner/runtime/execution-runtime-control.service';
import { ExecutionRuntimeHooksService } from '../step-runner/runtime/execution-runtime-hooks.service';
import { RuntimeExecutionOrchestrator } from '../step-runner/runtime/runtime-execution.orchestrator';
import { RuntimeResultInterpreter } from '../step-runner/runtime/runtime-result.interpreter';
import { RuntimeStepRequestFactory } from '../step-runner/runtime/runtime-step-request.factory';
import { ExecutionSystemSkillResultService } from '../step-runner/runtime/execution-system-skill-result.service';
import { ExecutionStepService } from '../step-runner/steps/execution-step.service';
import { ExecutionEventService } from '../state/execution-event.service';
import { ExecutionPhaseService } from '../state/execution-phase.service';
import { ExecutionPhaseSyncService } from '../state/execution-phase-sync.service';
import { ExecutionStateService } from '../state/execution-state.service';
import { WorkflowActivityProgressService } from '../state/workflow-activity-progress.service';

export interface ResolveExecutionServiceDependenciesInput {
  prisma: PrismaService;
  runtimeExecutionOrchestrator?: RuntimeExecutionOrchestrator | ExecutionEventService;
  runtimeResultInterpreter?: RuntimeResultInterpreter;
  runtimeStepRequestFactory?: RuntimeStepRequestFactory;
  executionEventService?: ExecutionEventService;
  executionFailureService?: ExecutionFailureService;
  executionPhaseService?: ExecutionPhaseService;
  executionPhaseSyncService?: ExecutionPhaseSyncService;
  executionStateService?: ExecutionStateService;
  executionStepService?: ExecutionStepService;
  executionCreateService?: ExecutionCreateService;
  executionInputResolutionService?: ExecutionInputResolutionService;
  executionSubmitInputService?: ExecutionSubmitInputService;
  executionStartService?: ExecutionStartService;
  executionPlanNormalizationService?: ExecutionPlanNormalizationService;
  browserPhaseExecutor?: BrowserPhaseExecutor;
  executionHumanControlService?: ExecutionHumanControlService;
  executionApprovalService?: ExecutionApprovalService;
  executionPlanningService?: ExecutionPlanningService;
  executionRuntimeSessionService?: ExecutionRuntimeSessionService;
  executionFlowRunnerService?: ExecutionFlowRunnerService;
  executionStepExecutorService?: ExecutionStepExecutorService;
  executionApplicationHooksService?: ExecutionApplicationHooksService;
  executionRuntimeHooksService?: ExecutionRuntimeHooksService;
  executionRuntimeControlService?: ExecutionRuntimeControlService;
  executionSystemSkillResultService?: ExecutionSystemSkillResultService;
  executionBrowserOrchestrationService?: ExecutionBrowserOrchestrationService;
  browserRuntimeAdapter?: BrowserRuntimeAdapter;
  workflowActivityProgressService?: WorkflowActivityProgressService;
  executionQueryService?: ExecutionQueryService;
  executionLifecycleService?: ExecutionLifecycleService;
  executionBrowserReadService?: ExecutionBrowserReadService;
  executionStreamService?: ExecutionStreamService;
}

export interface MatchedExecutionServiceDependencies {
  executionEventService?: ExecutionEventService;
  executionFailureService?: ExecutionFailureService;
  executionPhaseService?: ExecutionPhaseService;
  executionPhaseSyncService?: ExecutionPhaseSyncService;
  executionStateService?: ExecutionStateService;
  executionStepService?: ExecutionStepService;
  executionCreateService?: ExecutionCreateService;
  executionInputResolutionService?: ExecutionInputResolutionService;
  executionSubmitInputService?: ExecutionSubmitInputService;
  executionStartService?: ExecutionStartService;
  executionPlanNormalizationService?: ExecutionPlanNormalizationService;
  browserPhaseExecutor?: BrowserPhaseExecutor;
  executionHumanControlService?: ExecutionHumanControlService;
  executionApprovalService?: ExecutionApprovalService;
  executionPlanningService?: ExecutionPlanningService;
  executionRuntimeSessionService?: ExecutionRuntimeSessionService;
  executionFlowRunnerService?: ExecutionFlowRunnerService;
  executionStepExecutorService?: ExecutionStepExecutorService;
  executionApplicationHooksService?: ExecutionApplicationHooksService;
  executionRuntimeHooksService?: ExecutionRuntimeHooksService;
  executionRuntimeControlService?: ExecutionRuntimeControlService;
  executionSystemSkillResultService?: ExecutionSystemSkillResultService;
  executionBrowserOrchestrationService?: ExecutionBrowserOrchestrationService;
  browserRuntimeAdapter?: BrowserRuntimeAdapter;
  workflowActivityProgressService?: WorkflowActivityProgressService;
  executionQueryService?: ExecutionQueryService;
  executionLifecycleService?: ExecutionLifecycleService;
  executionBrowserReadService?: ExecutionBrowserReadService;
  executionStreamService?: ExecutionStreamService;
}

export interface ResolvedExecutionServiceDependencies {
  executionEventService: ExecutionEventService;
  executionFailureService: ExecutionFailureService;
  executionFlowRunnerService: ExecutionFlowRunnerService;
  executionPhaseService: ExecutionPhaseService;
  executionPhaseSyncService: ExecutionPhaseSyncService;
  executionStateService: ExecutionStateService;
  executionLifecycleService: ExecutionLifecycleService;
  executionStreamService: ExecutionStreamService;
  executionQueryService: ExecutionQueryService;
  executionApplicationHooksService: ExecutionApplicationHooksService;
  executionStepService: ExecutionStepService;
  executionApprovalService: ExecutionApprovalService;
  executionHumanControlService: ExecutionHumanControlService;
  executionCreateService: ExecutionCreateService;
  executionInputResolutionService: ExecutionInputResolutionService;
  executionSubmitInputService: ExecutionSubmitInputService;
  executionStartService: ExecutionStartService;
  executionPlanningService: ExecutionPlanningService;
  executionPlanNormalizationService: ExecutionPlanNormalizationService;
  executionBrowserOrchestrationService: ExecutionBrowserOrchestrationService;
  executionRuntimeSessionService: ExecutionRuntimeSessionService;
  executionStepExecutorService: ExecutionStepExecutorService;
  executionRuntimeHooksService: ExecutionRuntimeHooksService;
  executionRuntimeControlService: ExecutionRuntimeControlService;
  executionSystemSkillResultService: ExecutionSystemSkillResultService;
  workflowActivityProgressService: WorkflowActivityProgressService;
  browserRuntimeAdapter: BrowserRuntimeAdapter;
  executionBrowserReadService: ExecutionBrowserReadService;
}
