import { useMemo } from 'react';
import { useWordIdentifyPanel } from '../../parameter-identify/word/useWordIdentifyPanel';
import { createHostAdapter } from '../../../host/adapters';
import {
  buildCompareDebugText,
  buildFrontendCompareResult,
  buildTableAnchorParagraphMap,
  getCompareCandidateDisplayName,
  rebuildCompareSummary,
} from '../../parameter-query/word';
import { TemplateUnderstandResponse } from '../../../api/carbone-api';
import {
  buildWordKeywordFocusedDebugExcerpt,
  buildWordParameterDetectionDebugText,
} from '../../../host/office/word/parameter';
import {
  buildWordChapterDetectionDebugText,
  buildWordDocumentStructureDebugText,
} from '../../../host/office/word/chapter';
import {
  appendUniqueCandidateIds,
  buildWordSectionBilingualPairList,
  buildWordSectionCandidateList,
  buildWordSectionPromptBilingualGroups,
  buildWordSectionPromptCandidates,
  buildWordSectionSubset,
  filterWordPromptBilingualGroupsByCandidates,
  isWordLoopCompareCandidate,
  takeWordRecognitionBatch,
} from '../../parameter-identify/word/identify-recognition.prompt.helpers';
import { useWordIdentifyCacheController } from '../../parameter-identify/word/identify-cache.controller';
import {
  buildAcceptedWordSuggestionSummaries,
  dedupeWordSectionSuggestions,
  hydrateWordSectionSuggestions,
  isWordSuggestionHighQuality,
  selectBestWordSuggestionForCandidate,
} from '../../parameter-identify/word/identify-suggestion.helpers';
import {
  buildWordSectionDocumentContent,
  buildWordSectionDocumentIR,
  buildWordSectionExcerpt,
} from './word-workflow.section.helpers';
import { createWordWorkflowActionControllers } from './word-workflow.controller-actions';
import { buildWordWorkflowPanelView } from './word-workflow.controller-view';
import { buildWordWorkflowRequest } from './word-workflow.actions.helpers';
import {
  buildPromptTraceDebugText,
  buildUnderstandingDebugText,
  buildWordUnderstandingSummaryText,
} from './word-workflow.debug';
import {
  buildWordCompareCacheKey,
  buildWordUnderstandingCacheKey,
  isWordRecognitionCacheCompatible,
  isWordUnderstandingCacheCompatible,
  loadWordCompareCache,
  loadWordRecognitionCache,
  loadWordUnderstandingCache,
  mergeWordRecognitionResultWithAppliedCache,
  removeWordCompareCacheEntry,
  removeWordRecognitionCacheEntry,
  removeWordUnderstandingCacheEntry,
  saveWordCompareCacheEntry,
  saveWordRecognitionCacheEntry,
  saveWordUnderstandingCacheEntry,
} from './word-workflow.cache';
import {
  formatConfidence,
  getCompareDocumentTypeLabel,
  getCompareHeadingLanguageSummary,
  normalizeCompareHeadingLanguages,
  WORD_SECTION_RECOGNITION_BATCH_SIZE,
  WORD_SECTION_RECOGNITION_MAX_ROUNDS,
  WORD_TECHNICAL_SERVICE_DEBUG_KEYWORDS,
} from './word-workflow.panel.helpers';
import { useWordWorkflowPanelEffects } from './useWordWorkflowPanelEffects';
import { useWordWorkflowCompareEditor } from './useWordWorkflowCompareEditor';
import { useWordWorkflowDerivedState } from './useWordWorkflowDerivedState';
import { useWordWorkflowPanelState } from './useWordWorkflowPanelState';

interface UseWordWorkflowPanelControllerOptions {
  onApplyComplete?: () => void;
}

export function useWordWorkflowPanelController(options: UseWordWorkflowPanelControllerOptions) {
  const identifyPanel = useWordIdentifyPanel();
  const panelState = useWordWorkflowPanelState();

  const hostAdapter = useMemo(() => createHostAdapter('word'), []);

  const derivedState = useWordWorkflowDerivedState({
    compareHeadingLanguages: panelState.compareHeadingLanguages,
    compareResult: panelState.compareResult,
    compareDocumentIr: panelState.compareDocumentIr,
    selectedCompareSections: panelState.selectedCompareSections,
    sampleUploadState: panelState.sampleUploadState,
    understandingResult: panelState.understandingResult,
    understandingRevision: panelState.understandingRevision,
    understandingLanguageSignature: panelState.understandingLanguageSignature,
    understandingCompareSignature: panelState.understandingCompareSignature,
    understandingCacheStatus: panelState.understandingCacheStatus,
    understandingCacheUpdatedAt: panelState.understandingCacheUpdatedAt,
    detectedUploadCacheStatus: panelState.detectedUploadCacheStatus,
    detectedUploadCacheUpdatedAt: panelState.detectedUploadCacheUpdatedAt,
    detectedUploadCacheResult: panelState.detectedUploadCacheResult,
    isUnderstanding: panelState.isUnderstanding,
    recognitionActivated: panelState.recognitionActivated,
    recognitionRevision: panelState.recognitionRevision,
    recognitionLanguageSignature: panelState.recognitionLanguageSignature,
    recognitionCompareSignature: panelState.recognitionCompareSignature,
    recognitionResult: panelState.recognitionResult,
    sectionGenerationResults: panelState.sectionGenerationResults,
    suggestions: identifyPanel.storeState.suggestions,
    workflowSourceLanguage: identifyPanel.workflowState.workflowSourceLanguage,
    workflowTargetLanguages: identifyPanel.workflowState.workflowTargetLanguages,
  });

  const compareEditor = useWordWorkflowCompareEditor({
    compareDocumentIr: panelState.compareDocumentIr,
    sampleUploadState: panelState.sampleUploadState,
    selectedTemplateType: identifyPanel.workflowState.selectedTemplateType,
    effectiveCompareHeadingLanguages: derivedState.effectiveCompareHeadingLanguages,
    sectionGenerationResults: panelState.sectionGenerationResults,
    suggestions: identifyPanel.storeState.suggestions,
    collapsedRecognitionSections: panelState.collapsedRecognitionSections,
    setCompareResult: panelState.setCompareResult,
    setCompareCacheStatus: panelState.setCompareCacheStatus,
    setCompareCacheUpdatedAt: panelState.setCompareCacheUpdatedAt,
    buildWordCompareCacheKey,
    rebuildCompareSummary,
  });

  const cacheController = useWordIdentifyCacheController({
    recognitionCacheKey: derivedState.recognitionCacheKey,
    recognitionCacheStatus: panelState.recognitionCacheStatus,
    sectionGenerationResults: panelState.sectionGenerationResults,
    collapsedRecognitionSections: panelState.collapsedRecognitionSections,
    compareDocumentIr: panelState.compareDocumentIr,
    compareResult: panelState.compareResult,
    sampleUploadState: panelState.sampleUploadState,
    selectedTemplateType: identifyPanel.workflowState.selectedTemplateType,
    effectiveCompareHeadingLanguages: derivedState.effectiveCompareHeadingLanguages,
    recognitionActivated: panelState.recognitionActivated,
    recognitionReady: derivedState.recognitionReady,
    recognitionStale: derivedState.recognitionStale,
    recognitionDataFresh: derivedState.recognitionDataFresh,
    hasCompare: derivedState.hasCompare,
    languageSignature: derivedState.languageSignature,
    currentRecognitionCacheSignature: derivedState.currentRecognitionCacheSignature,
    onApplyComplete: options.onApplyComplete,
    setSuggestions: identifyPanel.storeState.setSuggestions,
    setSectionGenerationResults: panelState.setSectionGenerationResults,
    setCollapsedRecognitionSections: panelState.setCollapsedRecognitionSections,
    setRecognitionResult: panelState.setRecognitionResult,
    setRecognitionRevision: panelState.setRecognitionRevision,
    setRecognitionLanguageSignature: panelState.setRecognitionLanguageSignature,
    setRecognitionCompareSignature: panelState.setRecognitionCompareSignature,
    setRecognitionActivated: panelState.setRecognitionActivated,
    setRecognitionCacheStatus: panelState.setRecognitionCacheStatus,
    setRecognitionCacheUpdatedAt: panelState.setRecognitionCacheUpdatedAt,
    setCompareCacheUpdatedAt: panelState.setCompareCacheUpdatedAt,
    addDebugLog: identifyPanel.storeState.addDebugLog,
    loadWordRecognitionCache,
    saveWordRecognitionCacheEntry,
    removeWordRecognitionCacheEntry,
    isWordRecognitionCacheCompatible,
    mergeRecognitionResultWithAppliedCache: (nextResult, cachedEntry) =>
      mergeWordRecognitionResultWithAppliedCache(
        nextResult,
        cachedEntry,
        dedupeWordSectionSuggestions
      ),
    buildWordCompareCacheKey,
    saveWordCompareCacheEntry,
  });

  useWordWorkflowPanelEffects({
    hostAdapter,
    sampleUploadState: panelState.sampleUploadState,
    selectedTemplateType: identifyPanel.workflowState.selectedTemplateType,
    effectiveCompareHeadingLanguages: derivedState.effectiveCompareHeadingLanguages,
    workflowSourceLanguage: identifyPanel.workflowState.workflowSourceLanguage,
    workflowTargetLanguages: identifyPanel.workflowState.workflowTargetLanguages,
    languageSignature: derivedState.languageSignature,
    currentRecognitionCacheSignature: derivedState.currentRecognitionCacheSignature,
    compareCandidateSections: derivedState.compareCandidateSections,
    sectionGenerationResults: panelState.sectionGenerationResults,
    setWorkflowSourceLanguage: identifyPanel.workflowState.setWorkflowSourceLanguage,
    setWorkflowTargetLanguages: identifyPanel.workflowState.setWorkflowTargetLanguages,
    setCollapsedCompareSections: panelState.setCollapsedCompareSections,
    setSelectedCompareSections: panelState.setSelectedCompareSections,
    setCollapsedRecognitionSections: panelState.setCollapsedRecognitionSections,
    setCompareDocumentIr: panelState.setCompareDocumentIr,
    setCompareResult: panelState.setCompareResult,
    setCompareCacheStatus: panelState.setCompareCacheStatus,
    setCompareCacheUpdatedAt: panelState.setCompareCacheUpdatedAt,
    setSectionGenerationResults: panelState.setSectionGenerationResults,
    setSuggestions: identifyPanel.storeState.setSuggestions,
    setRecognitionResult: panelState.setRecognitionResult,
    setRecognitionRevision: panelState.setRecognitionRevision,
    setRecognitionLanguageSignature: panelState.setRecognitionLanguageSignature,
    setRecognitionCompareSignature: panelState.setRecognitionCompareSignature,
    setRecognitionActivated: panelState.setRecognitionActivated,
    setDetectedUploadCacheStatus: panelState.setDetectedUploadCacheStatus,
    setDetectedUploadCacheUpdatedAt: panelState.setDetectedUploadCacheUpdatedAt,
    setDetectedUploadCacheResult: panelState.setDetectedUploadCacheResult,
  });

  const buildWorkflowRequest = async (requestOptions?: {
    includeUnderstanding?: boolean;
    useSelectedCompareCandidates?: boolean;
    prefetchedUnderstanding?: TemplateUnderstandResponse | null;
  }) =>
    buildWordWorkflowRequest(
      {
        hostAdapter,
        compareResult: panelState.compareResult,
        effectiveCompareCandidateFields: derivedState.effectiveCompareCandidateFields,
        currentCompareSignature: derivedState.currentCompareSignature,
        sampleUploadState: panelState.sampleUploadState,
        understandingResult: panelState.understandingResult,
        workflowSourceLanguage: identifyPanel.workflowState.workflowSourceLanguage,
        workflowTargetLanguages: identifyPanel.workflowState.workflowTargetLanguages,
        selectedTemplateType: identifyPanel.workflowState.selectedTemplateType,
        useMultiStage: identifyPanel.workflowState.useMultiStage,
        analysisExecutor: identifyPanel.storeState.analysisExecutor,
        analysisThinkingEnabled: identifyPanel.storeState.analysisThinkingEnabled,
        buildWordUnderstandingCacheKey,
      },
      requestOptions
    );

  const workflowActions = createWordWorkflowActionControllers({
    compare: {
      hostAdapter,
      sampleUploadState: panelState.sampleUploadState,
      selectedTemplateType: identifyPanel.workflowState.selectedTemplateType,
      effectiveCompareHeadingLanguages: derivedState.effectiveCompareHeadingLanguages,
      technicalServiceDebugKeywords: WORD_TECHNICAL_SERVICE_DEBUG_KEYWORDS,
      setCompareHighlightSummary: panelState.setCompareHighlightSummary,
      setCompareCacheStatus: panelState.setCompareCacheStatus,
      setCompareCacheUpdatedAt: panelState.setCompareCacheUpdatedAt,
      setUnderstandingResult: panelState.setUnderstandingResult,
      setRecognitionResult: panelState.setRecognitionResult,
      setSectionGenerationResults: panelState.setSectionGenerationResults,
      setRecognitionActivated: panelState.setRecognitionActivated,
      setSuggestions: identifyPanel.storeState.setSuggestions,
      setCollapsedRecognitionSections: panelState.setCollapsedRecognitionSections,
      setRecognitionCacheStatus: panelState.setRecognitionCacheStatus,
      setRecognitionCacheUpdatedAt: panelState.setRecognitionCacheUpdatedAt,
      setAnalysisError: identifyPanel.storeState.setAnalysisError,
      setIsComparing: panelState.setIsComparing,
      setCompareDocumentIr: panelState.setCompareDocumentIr,
      setCompareResult: panelState.setCompareResult,
      addDebugLog: identifyPanel.storeState.addDebugLog,
      buildWordCompareCacheKey,
      loadWordCompareCache,
      removeWordCompareCacheEntry,
      saveWordCompareCacheEntry,
      buildFrontendCompareResult,
      buildTableAnchorParagraphMap,
      buildCompareDebugText,
      buildWordKeywordFocusedDebugExcerpt,
      buildWordParameterDetectionDebugText,
      buildWordDocumentStructureDebugText,
      buildWordChapterDetectionDebugText,
    },
    step: {
      compareCandidateSections: derivedState.compareCandidateSections,
      normalizeCompareHeadingLanguages,
      setSelectedTemplateType: identifyPanel.workflowState.setSelectedTemplateType,
      setCompareHeadingLanguages: panelState.setCompareHeadingLanguages,
      setCollapsedCompareSections: panelState.setCollapsedCompareSections,
      setCollapsedRecognitionSections: panelState.setCollapsedRecognitionSections,
      setSelectedCompareSections: panelState.setSelectedCompareSections,
      setCompareResult: panelState.setCompareResult,
      setCompareDocumentIr: panelState.setCompareDocumentIr,
      setCompareHighlightSummary: panelState.setCompareHighlightSummary,
      setCompareCacheStatus: panelState.setCompareCacheStatus,
      setCompareCacheUpdatedAt: panelState.setCompareCacheUpdatedAt,
      setUnderstandingResult: panelState.setUnderstandingResult,
      setRecognitionResult: panelState.setRecognitionResult,
      setSectionGenerationResults: panelState.setSectionGenerationResults,
      setSuggestions: identifyPanel.storeState.setSuggestions,
      setUnderstandingCacheStatus: panelState.setUnderstandingCacheStatus,
      setUnderstandingCacheUpdatedAt: panelState.setUnderstandingCacheUpdatedAt,
      setRecognitionCacheStatus: panelState.setRecognitionCacheStatus,
      setRecognitionCacheUpdatedAt: panelState.setRecognitionCacheUpdatedAt,
      setDetectedUploadCacheStatus: panelState.setDetectedUploadCacheStatus,
      setDetectedUploadCacheUpdatedAt: panelState.setDetectedUploadCacheUpdatedAt,
      setDetectedUploadCacheResult: panelState.setDetectedUploadCacheResult,
      setSampleUploadState: panelState.setSampleUploadState,
    },
    highlight: {
      compareResult: panelState.compareResult,
      effectiveCompareCandidateFields: derivedState.effectiveCompareCandidateFields,
      setAnalysisError: identifyPanel.storeState.setAnalysisError,
      setIsHighlightingCandidates: panelState.setIsHighlightingCandidates,
      setIsClearingHighlights: panelState.setIsClearingHighlights,
      setCompareHighlightSummary: panelState.setCompareHighlightSummary,
      addDebugLog: identifyPanel.storeState.addDebugLog,
      getCandidateDisplayName: getCompareCandidateDisplayName,
    },
    recognition: {
      sampleUploadState: panelState.sampleUploadState,
      compareResult: panelState.compareResult,
      compareCandidateSections: derivedState.compareCandidateSections,
      effectiveCompareCandidateFields: derivedState.effectiveCompareCandidateFields,
      apiBaseUrl: identifyPanel.storeState.apiBaseUrl,
      languageSignature: derivedState.languageSignature,
      currentCompareSignature: derivedState.currentCompareSignature,
      currentRecognitionCacheSignature: derivedState.currentRecognitionCacheSignature,
      workflowSourceLanguage: identifyPanel.workflowState.workflowSourceLanguage,
      workflowTargetLanguages: identifyPanel.workflowState.workflowTargetLanguages,
      selectedCompareSectionKeys: derivedState.selectedCompareSectionKeys,
      selectedRecognitionSections: derivedState.selectedRecognitionSections,
      detectedSectionMap: derivedState.detectedSectionMap,
      selectedTemplateType: identifyPanel.workflowState.selectedTemplateType,
      analysisExecutor: identifyPanel.storeState.analysisExecutor,
      analysisThinkingEnabled: identifyPanel.storeState.analysisThinkingEnabled,
      useMultiStage: identifyPanel.workflowState.useMultiStage,
      aiOrchestratorBaseUrl: identifyPanel.storeState.aiOrchestratorBaseUrl,
      aiOrchestratorAuthToken: identifyPanel.storeState.aiOrchestratorAuthToken,
      recognitionCacheKey: derivedState.recognitionCacheKey,
      collapsedRecognitionSections: panelState.collapsedRecognitionSections,
      wordSectionRecognitionBatchSize: WORD_SECTION_RECOGNITION_BATCH_SIZE,
      wordSectionRecognitionMaxRounds: WORD_SECTION_RECOGNITION_MAX_ROUNDS,
      setAnalysisError: identifyPanel.storeState.setAnalysisError,
      addDebugLog: identifyPanel.storeState.addDebugLog,
      setIsUnderstanding: panelState.setIsUnderstanding,
      setUnderstandingResult: panelState.setUnderstandingResult,
      setUnderstandingRevision: panelState.setUnderstandingRevision,
      setUnderstandingLanguageSignature: panelState.setUnderstandingLanguageSignature,
      setUnderstandingCompareSignature: panelState.setUnderstandingCompareSignature,
      setUnderstandingCacheStatus: panelState.setUnderstandingCacheStatus,
      setUnderstandingCacheUpdatedAt: panelState.setUnderstandingCacheUpdatedAt,
      setIsRecognizing: panelState.setIsRecognizing,
      setRecognitionResult: panelState.setRecognitionResult,
      setSectionGenerationResults: panelState.setSectionGenerationResults,
      setSuggestions: identifyPanel.storeState.setSuggestions,
      setCollapsedRecognitionSections: panelState.setCollapsedRecognitionSections,
      setRecognitionCacheStatus: panelState.setRecognitionCacheStatus,
      setRecognitionCacheUpdatedAt: panelState.setRecognitionCacheUpdatedAt,
      setRecognitionRevision: panelState.setRecognitionRevision,
      setRecognitionLanguageSignature: panelState.setRecognitionLanguageSignature,
      setRecognitionCompareSignature: panelState.setRecognitionCompareSignature,
      setRecognitionActivated: panelState.setRecognitionActivated,
      buildWorkflowRequest,
      loadWordUnderstandingCache,
      isWordUnderstandingCacheCompatible,
      removeWordUnderstandingCacheEntry,
      saveWordUnderstandingCacheEntry,
      buildUnderstandingDebugText,
      buildWordUnderstandingSummaryText,
      loadWordRecognitionCache,
      saveWordRecognitionCacheEntry,
      mergeRecognitionResultWithAppliedCache: (nextResult, cachedEntry) =>
        mergeWordRecognitionResultWithAppliedCache(
          nextResult,
          cachedEntry,
          dedupeWordSectionSuggestions
        ),
      persistCompareCacheRecognitionSnapshot:
        cacheController.persistCompareCacheRecognitionSnapshot,
      buildWordSectionExcerpt,
      buildWordSectionDocumentIR,
      buildWordSectionDocumentContent,
      buildWordSectionPromptBilingualGroups,
      buildWordSectionCandidateList,
      buildWordSectionBilingualPairList,
      takeWordRecognitionBatch,
      buildWordSectionSubset,
      buildWordSectionPromptCandidates,
      filterWordPromptBilingualGroupsByCandidates,
      buildAcceptedWordSuggestionSummaries,
      hydrateWordSectionSuggestions,
      buildPromptTraceDebugText,
      selectBestWordSuggestionForCandidate,
      isWordSuggestionHighQuality,
      appendUniqueCandidateIds,
      isWordLoopCompareCandidate,
      dedupeWordSectionSuggestions,
    },
  });

  return buildWordWorkflowPanelView({
    sampleUploaded: panelState.sampleUploadState.uploaded,
    hasCompare: derivedState.hasCompare,
    recognitionReady: derivedState.recognitionReady,
    followup: {
      recognitionReady: derivedState.recognitionReady,
      suggestions: identifyPanel.storeState.suggestions,
      isAnalyzing: identifyPanel.storeState.isAnalyzing,
      aiSkillGuide: identifyPanel.workflowState.aiSkillGuide,
      draftId: identifyPanel.workflowState.draftId,
      draftInfo: identifyPanel.workflowState.draftInfo,
      latestBackendDraftInfo: identifyPanel.workflowState.latestBackendDraftInfo,
      draftWorkflowNotice: identifyPanel.workflowState.draftWorkflowNotice,
      isGeneratingGuide: identifyPanel.workflowState.isGeneratingGuide,
      isVerifying: identifyPanel.workflowState.isVerifying,
      isSavingDraft: identifyPanel.workflowState.isSavingDraft,
      draftWorkflowCollapsed: panelState.draftWorkflowCollapsed,
      guidePreviewCollapsed: panelState.guidePreviewCollapsed,
      setDraftWorkflowCollapsed: panelState.setDraftWorkflowCollapsed,
      setGuidePreviewCollapsed: panelState.setGuidePreviewCollapsed,
      handleGenerateAISkillGuide: identifyPanel.workflowState.handleGenerateAISkillGuide,
      handleVerifyTemplate: identifyPanel.workflowState.handleVerifyTemplate,
      handleSaveDraft: identifyPanel.workflowState.handleSaveDraft,
      handleLoadDraft: identifyPanel.workflowState.handleLoadDraft,
      handleClearDraft: identifyPanel.workflowState.handleClearDraft,
      aiGeneratedData: identifyPanel.workflowState.aiGeneratedData,
      previewResult: identifyPanel.workflowState.previewResult,
      saveResult: identifyPanel.workflowState.saveResult,
      verifySaveCollapsed: panelState.verifySaveCollapsed,
      setVerifySaveCollapsed: panelState.setVerifySaveCollapsed,
      isGeneratingParams: identifyPanel.workflowState.isGeneratingParams,
      analysisThinkingEnabled: identifyPanel.storeState.analysisThinkingEnabled,
      setAnalysisThinkingEnabled: identifyPanel.storeState.setAnalysisThinkingEnabled,
      aiDescription: identifyPanel.workflowState.aiDescription,
      handleAiDescriptionChange: identifyPanel.workflowState.handleAiDescriptionChange,
      handleGenerateParameters: identifyPanel.workflowState.handleGenerateParameters,
      aiGenerateResult: identifyPanel.workflowState.aiGenerateResult,
      isPreviewing: identifyPanel.workflowState.isPreviewing,
      handlePreviewWithAIParams: identifyPanel.workflowState.handlePreviewWithAIParams,
      previewInlineSupported: identifyPanel.previewInlineSupported,
      apiBaseUrl: identifyPanel.storeState.apiBaseUrl,
      getDownloadLabel: identifyPanel.getDownloadLabel,
      templateName: identifyPanel.workflowState.templateName,
      setTemplateName: identifyPanel.workflowState.setTemplateName,
      selectedTemplateType: identifyPanel.workflowState.selectedTemplateType,
      isSaving: identifyPanel.workflowState.isSaving,
      handleSaveTemplateAndGuide: identifyPanel.workflowState.handleSaveTemplateAndGuide,
    },
    loadSection: {
      step1Collapsed: panelState.step1Collapsed,
      setStep1Collapsed: panelState.setStep1Collapsed,
      sampleUploadState: panelState.sampleUploadState,
      uploadStatusLabel: derivedState.uploadStatusLabel,
      uploadStatusTone: derivedState.uploadStatusTone,
      understandingActionHint: derivedState.understandingActionHint,
      understandingStatusLabel: derivedState.understandingStatusLabel,
      understandingStatusTone: derivedState.understandingStatusTone,
      understandingCacheTimeText: derivedState.understandingCacheTimeText,
      understandingStale: derivedState.understandingStale,
      understandingCacheDescription: derivedState.understandingCacheDescription,
      isUnderstanding: panelState.isUnderstanding,
      understandingSummaryCollapsed: panelState.understandingSummaryCollapsed,
      setUnderstandingSummaryCollapsed: panelState.setUnderstandingSummaryCollapsed,
      understandingSummaryText: derivedState.understandingSummaryText,
      displayedUnderstandingSummaryResult: derivedState.displayedUnderstandingSummaryResult,
      handleStartUnderstanding: workflowActions.handleStartUnderstanding,
      handleSampleUploadStateChange: workflowActions.handleSampleUploadStateChange,
    },
    querySection: {
      step2Collapsed: panelState.step2Collapsed,
      setStep2Collapsed: panelState.setStep2Collapsed,
      sampleUploadState: panelState.sampleUploadState,
      selectedTemplateType: identifyPanel.workflowState.selectedTemplateType as
        | 'contract'
        | 'report',
      effectiveCompareHeadingLanguages: derivedState.effectiveCompareHeadingLanguages,
      handleCompareDocumentTypeChange: workflowActions.handleCompareDocumentTypeChange,
      handleCompareHeadingLanguageToggle: workflowActions.handleCompareHeadingLanguageToggle,
      isComparing: panelState.isComparing,
      isHighlightingCandidates: panelState.isHighlightingCandidates,
      isClearingHighlights: panelState.isClearingHighlights,
      handleStartCompare: workflowActions.handleStartCompare,
      handleHighlightCompareCandidates: workflowActions.handleHighlightCompareCandidates,
      handleClearCompareHighlights: workflowActions.handleClearCompareHighlights,
      compareResult: panelState.compareResult,
      compareSummaryCollapsed: panelState.compareSummaryCollapsed,
      setCompareSummaryCollapsed: panelState.setCompareSummaryCollapsed,
      compareSectionsCollapsed: panelState.compareSectionsCollapsed,
      setCompareSectionsCollapsed: panelState.setCompareSectionsCollapsed,
      compareCacheStatus: panelState.compareCacheStatus,
      compareCacheUpdatedAt: panelState.compareCacheUpdatedAt,
      selectedCompareSectionKeys: derivedState.selectedCompareSectionKeys,
      compareCandidateSections: derivedState.compareCandidateSections,
      selectedCompareSections: panelState.selectedCompareSections,
      collapsedCompareSections: panelState.collapsedCompareSections,
      analysisThinkingEnabled: identifyPanel.storeState.analysisThinkingEnabled,
      setAnalysisThinkingEnabled: identifyPanel.storeState.setAnalysisThinkingEnabled,
      recognitionBlocked: derivedState.recognitionBlocked,
      isRecognizing: panelState.isRecognizing,
      isUnderstanding: panelState.isUnderstanding,
      recognitionReady: derivedState.recognitionReady,
      totalSuggestionCount: derivedState.totalSuggestionCount,
      pendingSuggestionCount: derivedState.pendingSuggestionCount,
      derivedPrimaryChapters: derivedState.derivedPrimaryChapters,
      setAllCompareSectionsSelected: workflowActions.setAllCompareSectionsSelected,
      toggleCompareSectionSelection: workflowActions.toggleCompareSectionSelection,
      toggleCompareSectionCollapse: workflowActions.toggleCompareSectionCollapse,
      handleStartRecognition: workflowActions.handleStartRecognition,
      applyState: identifyPanel.applyState,
      persistAppliedRecognitionCache: cacheController.persistAppliedRecognitionCache,
      getCompareDocumentTypeLabel,
      getCompareHeadingLanguageSummary,
      updateCompareCandidate: compareEditor.updateCompareCandidate,
      deleteCompareCandidate: compareEditor.deleteCompareCandidate,
      isWordLoopCompareCandidate,
      sectionGenerationResultMap: derivedState.sectionGenerationResultMap,
      sectionSuggestionMap: derivedState.sectionSuggestionMap,
      collapsedRecognitionSections: panelState.collapsedRecognitionSections,
      toggleRecognitionSectionCollapse: workflowActions.toggleRecognitionSectionCollapse,
      formatConfidence,
      sectionProcessingSummary: derivedState.sectionProcessingSummary,
    },
    debugPanel: {
      showDebugPanel: identifyPanel.storeState.showDebugPanel,
      setShowDebugPanel: identifyPanel.storeState.setShowDebugPanel,
      analysisError: identifyPanel.storeState.analysisError,
      analysisErrorDetails: identifyPanel.storeState.analysisErrorDetails,
      showErrorDetails: identifyPanel.workflowState.showErrorDetails,
      setShowErrorDetails: identifyPanel.workflowState.setShowErrorDetails,
      recentErrorLogs: identifyPanel.recentErrorLogs,
    },
  });
}
