export const PARAM_LABEL_MAP: Record<string, string> = {
  contractTitle: '合同名称',
  counterpartyName: '相对方企业主体',
  cooperationSubject: '合作业务主题',
  durationYears: '保密义务年限',
  myPosition: '我方合同立场',
  penaltyAmount: '违约金赔偿约定',
  remarks: '商务诉求说明',
  contractType: '合同类型',
  signDate: '签署日期',
  currentStage: '当前流程阶段',
  leaveType: '请假类型',
  startTime: '开始时间',
  endTime: '结束时间',
  durationHours: '请假时长',
  reason: '请假事由',
  handoverPerson: '工作交接人',
  expenseType: '报销类型',
  amount: '报销金额',
  baseFileName: '基准版本',
  compareFileName: '比对版本',
  fileNameA: '基准合同',
  fileNameB: '比对合同',
};

export const IGNORED_TASK_CONTEXT_PARAM_KEYS = new Set([
  'downloadUrl',
  'fileUrl',
  'contractUrl',
  'fileName',
  'contractFileName',
  'executionId',
  'isDraftReplaced',
  'originalDraftUrl',
  'originalDraftFileName',
  'originalDraftSize',
  'rawContent',
  'text',
  'fileUrlA',
  'downloadUrlA',
  'fileNameA',
  'fileUrlB',
  'downloadUrlB',
  'fileNameB',
]);
