export const RELEASE_MANAGER_PRISMA = Symbol('RELEASE_MANAGER_PRISMA');
export const RELEASE_MANAGER_SKILL_SERVICE = Symbol('RELEASE_MANAGER_SKILL_SERVICE');
export const RELEASE_MANAGER_TOOL_CATALOG = Symbol('RELEASE_MANAGER_TOOL_CATALOG');
export const RELEASE_MANAGER_TEMPORAL_WORKFLOW = Symbol('RELEASE_MANAGER_TEMPORAL_WORKFLOW');
export const RELEASE_MANAGER_EXECUTION_FLOW_VALIDATION_FACADE = Symbol(
  'RELEASE_MANAGER_EXECUTION_FLOW_VALIDATION_FACADE'
);
export const RELEASE_MANAGER_ACTIVITY_EXECUTION = Symbol('RELEASE_MANAGER_ACTIVITY_EXECUTION');
