/** Project runtime evidence for an explicitly configured operation-report postprocessor. */
export function buildBrowserOperationReportLines(): string[] {
  return [
    '    def _build_operation_report_context(self, envelope: dict, params: dict) -> dict:',
    '        phases = []',
    '        for phase in self._checkpoint_phases:',
    '            result = phase.get("result") or {}',
    '            commands = []',
    '            page_contents = []',
    '            for command in result.get("results") or []:',
    '                commands.append({key: command[key] for key in ("command", "selector", "templateStepId", "status", "message", "pageUrl", "pageTitle") if command.get(key) is not None})',
    '                data = command.get("data") or {}',
    '                content = data.get("mainContent")',
    '                if isinstance(content, str) and content and content not in page_contents:',
    '                    page_contents.append(content)',
    '            phases.append({',
    '                "stepId": phase.get("stepId"),',
    '                "stepName": phase.get("stepName"),',
    '                "loopIteration": phase.get("loopIteration"),',
    '                "status": result.get("status"),',
    '                "commands": commands,',
    '                "pageContent": "\\n\\n".join(page_contents),',
    '                "extractedValues": {key: value for key, value in (result.get("variables") or {}).items() if not key.endswith("_clean_content") and not any(secret in key.lower() for secret in ("password", "credential", "secret", "token"))},',
    '                "humanResolution": result.get("humanResolution"),',
    '                "resolvedByHuman": result.get("resolvedByHuman", False),',
    '                "takeoverReason": result.get("takeoverReason"),',
    '                "loopStopValue": result.get("loopStopValue"),',
    '            })',
    '        return {',
    '            "schemaVersion": "browser-operation-evidence/v1",',
    '            "executionId": params.get("executionId"),',
    '            "status": (envelope.get("execution") or {}).get("status"),',
    '            "parameters": {key: value for key, value in (envelope.get("variables") or {}).items() if not key.endswith("_clean_content")},',
    '            "phases": phases,',
    '            "humanInterventionCount": sum(1 for phase in phases if phase["humanResolution"]),',
    '            "humanBrowserActionsAudited": False,',
    '        }',
    '',
  ];
}
