/** Use the normalized worker endpoint so recorder capture profiles survive publication. */
export function buildBrowserCaptureExecutionLines(): string[] {
  return [
    '        execute_result = {"success": True, "results": []}',
    '        for command, configured_step in zip(commands, command_steps):',
    '            step_config = configured_step.get("config") or {}',
    '            execute_payload = {',
    '                "executionId": str(input_data.get("executionId") or runtime_session_id),',
    '                "runtimeSessionId": runtime_session_id,',
    '                "backend": selected_backend,',
    '                "stepId": str(step_config.get("templateStepId") or ""),',
    '                "action": command["tool"],',
    '                "args": command.get("params") or {},',
    '            }',
    '            if isinstance(step_config.get("captureProfile"), dict):',
    '                execute_payload["captureProfile"] = step_config["captureProfile"]',
    '            activity.logger.info("执行浏览器步骤并采集页面证据", extra={"stepId": execute_payload["stepId"]})',
    '            try:',
    '                execute_response = await asyncio.to_thread(',
    '                    requests.post,',
    '                    f"{browser_worker_base_url}/browser/execute-step",',
    '                    json=execute_payload, headers=browser_headers, timeout=http_timeout,',
    '                )',
    '                execute_response.raise_for_status()',
    '                step_response = execute_response.json()',
    '            except requests.RequestException as exc:',
    '                raise ApplicationError(f"browser-worker 执行失败: {exc}", non_retryable=False)',
    '            step_output = dict(step_response.get("output") or {})',
    '            step_output["templateStepId"] = execute_payload["stepId"]',
    '            step_output["command"] = command["tool"]',
    '            if command["tool"] in ("click", "get_text", "select", "check", "uncheck"):',
    '                step_output["selector"] = (command.get("params") or {}).get("selector") or (command.get("params") or {}).get("target")',
    '            step_output["message"] = step_response.get("errorMessage") or step_output.get("stderr") or step_output.get("message")',
    '            step_output["status"] = "success" if step_response.get("success") else "error"',
    '            execute_result["results"].append(step_output)',
    '            if not step_response.get("success"):',
    '                execute_result["success"] = False',
    '                execute_result["message"] = step_output["message"]',
    '                break',
  ];
}
