import type { ExecutionStatus } from '@/api/execution';
import { buildExecutionDetailText } from '@/features/executions/lib/executionDetailText';

export interface ExecutionDetailSectionsProps {
  text: ReturnType<typeof buildExecutionDetailText>;
  isEnglish: boolean;
  execution?: any;
  displayRuntimeType: string;
  statusLabels: Record<string, string>;
  statusColors: Record<string, string>;
  getExecutionStatusLabel: (status?: ExecutionStatus | string) => string;
  getExecutionStatusColor: (status?: ExecutionStatus | string) => string;
  isBrowserExecution: boolean;
  effectiveBrowserExecutionResult: unknown;
  normalizedResult: any;
  getSkillDisplayName: (skillId?: string) => string;
  displayActivityPhases: any[];
  shouldShowExecutionSummary: boolean;
  shouldShowLiveProgressInfo: boolean;
  currentPhase: any;
  currentExecutionStep: any;
  activityProgressCurrent: number;
  completedActivityCount: number;
  pendingActivityCount: number;
  totalLoopCount: number;
  currentPhaseLoopIteration?: number;
  latestActivityUpdateAt?: string;
  summaryHeadline?: string;
  loopSummary?: any;
  latestExecutionReview?: any;
  takeoverFocusPhase?: any;
  currentPhaseDetailUrl?: string;
  waitingInputStep?: any;
  waitingInputSummary?: string;
  requiredInputs: any[];
  requiredInputGroups: any[];
  approveAndContinueLoading: boolean;
  approveLoading: boolean;
  rejectLoading: boolean;
  submitInputLoading: boolean;
  onApproveAndContinue: () => void;
  onApprove: () => void;
  onReject: () => void;
  onSubmitInput: (values: Record<string, unknown>) => void;
  executionInput: unknown;
  primaryResultText?: string;
  shouldRenderPrimaryAsMarkdown: boolean;
  shouldShowStructuredResult: boolean;
  resultPreviewValue: unknown;
  effectiveResultJson: unknown;
  shouldShowCurrentPhaseInfo: boolean;
  runtimeSession?: any;
  isExecutionActive: boolean;
  stableRuntimeSessionNovncUrl?: string;
  semantic?: any;
  shouldShowLegacySteps: boolean;
  steps?: any[];
  currentStepIndex: number;
}
