<<<<<<< HEAD
import React, { useState, useRef } from 'react';
import {
  Table, Card, Button, Input, Space, Tag, Typography, Modal, message, Form, Select,
  Divider, Alert, Collapse, Badge, Popconfirm, Statistic, Row, Col, Switch, InputNumber
=======
import React, { useState } from 'react';
import {
  Table, Card, Button, Input, Space, Tag, Typography, Modal, message, Form, Select,
  Divider, Alert, Empty, Collapse, Switch, Tooltip, Badge, Timeline, Tabs, Descriptions, Popconfirm
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
} from 'antd';
import {
  SearchOutlined, PlusOutlined, EditOutlined, DeleteOutlined, PlayCircleOutlined,
  ReloadOutlined, ApiOutlined, CodeOutlined, FileTextOutlined, ChromeOutlined,
<<<<<<< HEAD
  CheckCircleOutlined, ThunderboltOutlined, SettingOutlined,
  ExperimentOutlined, HeartOutlined, ClockCircleOutlined, RetweetOutlined,
  LineChartOutlined, WarningOutlined, OrderedListOutlined, CopyOutlined,
  SaveOutlined, RobotOutlined, EyeOutlined, LoadingOutlined
=======
  CheckCircleOutlined, WarningOutlined, ThunderboltOutlined, CopyOutlined,
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
} from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import { useQuery, useMutation, useQueryClient } from 'react-query';
import { activityApi, ActivityDTO, CreateActivityDto, ActivityValidationResult } from '../../api/activity';
import type { ColumnsType } from 'antd/es/table';

<<<<<<< HEAD
const { Text, Title, Paragraph } = Typography;
const { Option } = Select;
const { Panel } = Collapse;
const { TextArea } = Input;

const HANDLER_CONFIG: Record<string, { label: string; color: string; icon: React.ReactNode }> = {
  api: { label: 'API', color: 'green', icon: <ApiOutlined /> },
  carbone: { label: 'Carbone', color: 'blue', icon: <FileTextOutlined /> },
  browser: { label: '浏览器', color: 'purple', icon: <ChromeOutlined /> },
  script: { label: '脚本', color: 'orange', icon: <CodeOutlined /> },
};

interface ActivityStep {
  id: string;
  name: string;
  type: 'api' | 'carbone' | 'browser' | 'script';
  timeout: string;
  retryPolicy?: { maxRetries: number };
  config: Record<string, any>;
}

interface ActivityFormData {
  name: string;
  fn: string;
  description: string;  // AI guidance prompt for code generation
  taskQueue: string;
  startToCloseTimeout: string;
  heartbeatTimeout?: string;
  scheduleToStartTimeout: string;
  scheduleToCloseTimeout: string;
  retryPolicy?: { maxRetries: number; backoffMs?: number };
  idempotencyKey?: string;
  steps: ActivityStep[];
}

const generatePythonCode = (form: ActivityFormData): string => {
  const lines: string[] = [];
  lines.push('# Generated by Temporal Activity Generator');
  lines.push('# See: services/portal/src/skills/temporal-developer/SKILL.md');
  lines.push('');
  lines.push('from datetime import timedelta');
  lines.push('from temporalio import activity');
  lines.push('from temporalio.exceptions import ApplicationError');
  lines.push('from typing import Optional, Dict, Any');
  lines.push('');
  lines.push('@activity.defn');
  lines.push(`def ${form.fn}(input_data: Dict[str, Any]) -> Dict[str, Any]:`);

  if (form.description) {
    lines.push(`    """`);
    lines.push(`    Activity: ${form.name}`);
    lines.push(`    `);
    lines.push(`    Description: ${form.description}`);
    lines.push(`    `);
    lines.push(`    Configuration:`);
    lines.push(`      - Task Queue: ${form.taskQueue}`);
    lines.push(`      - StartToClose Timeout: ${form.startToCloseTimeout}`);
    if (form.heartbeatTimeout) {
      lines.push(`      - Heartbeat Timeout: ${form.heartbeatTimeout}`);
    }
    if (form.retryPolicy) {
      lines.push(`      - Retry Policy: maxRetries=${form.retryPolicy.maxRetries}`);
    }
    if (form.idempotencyKey) {
      lines.push(`      - Idempotency Key: ${form.idempotencyKey}`);
    }
    lines.push(`    """.replace('"', '\\"')`);
  } else {
    lines.push(`    """Activity: ${form.name}""".replace('"', '\\"')`);
  }

  lines.push('    activity.logger.info("Activity started")');

  if (form.heartbeatTimeout) {
    lines.push(`    activity.logger.info(f"Heartbeat timeout: ${form.heartbeatTimeout}")`);
  }

  lines.push('    activity.heartbeat("initializing")');

  if (form.steps.length > 0) {
    lines.push('    # Execute activity steps');
    form.steps.forEach((step, idx) => {
      lines.push('');
      lines.push(`    # === Step ${idx + 1}: ${step.name} ===`);
      lines.push(`    activity.heartbeat("executing_step_${idx + 1}")`);
      lines.push('    info = activity.info()');
      lines.push('    if info.is_cancelled:');
      lines.push('        activity.logger.warning("Activity cancelled")');
      lines.push('        return {"status": "cancelled", "step": ' + (idx + 1) + '}');

      if (step.type === 'api') {
        lines.push(`    try:`);
        lines.push(`        result_${idx + 1} = yield execute_api_request(`);
        lines.push(`            endpoint="${step.config.endpoint || 'https://api.example.com'}",`);
        lines.push(`            method="${step.config.method || 'GET'}"`);
        if (form.idempotencyKey) {
          lines.push(`            idempotency_key="${form.idempotencyKey}"`);
        }
        lines.push(`        )`);
        lines.push(`        activity.logger.info(f"Step ${idx + 1} completed: {result_${idx + 1}}")`);
        lines.push(`    except Exception as e:`);
        lines.push(`        activity.logger.error(f"Step ${idx + 1} failed: {e}")`);
        lines.push(`        raise ApplicationError(f"Step ${idx + 1} failed: {e}", non_retryable=False)`);
      } else if (step.type === 'script') {
        lines.push(`    result_${idx + 1} = yield execute_script(`);
        lines.push('        """');
        lines.push((step.config.script || '# your code here').split('\n').map(l => `        ${l}`).join('\n'));
        lines.push('        """');
        lines.push('    )');
      } else if (step.type === 'carbone') {
        lines.push(`    result_${idx + 1} = yield render_with_carbone(`);
        lines.push(`        template_id="${step.config.templateId || '{{template_id}}'}",`);
        lines.push(`        data=input_data`);
        lines.push('    )');
      } else if (step.type === 'browser') {
        lines.push(`    result_${idx + 1} = yield execute_browser_action(`);
        lines.push(`        action="${step.config.action || 'click'}",`);
        lines.push(`        selector="${step.config.selector || '{{selector}}'}"`);
        lines.push('    )');
      }
    });
  }

  lines.push('');
  lines.push('    activity.heartbeat("completed")');
  lines.push('    return {');
  lines.push('        "status": "success",');
  lines.push(`        "activity": "${form.name}",`);
  if (form.steps.length > 0) {
    lines.push('        "results": {');
    form.steps.forEach((step, idx) => {
      lines.push(`            "${step.name}": result_${idx + 1}${idx < form.steps.length - 1 ? ',' : ''}`);
    });
    lines.push('        }');
  }
  lines.push('    }');

  return lines.join('\n');
=======
const { Title, Text, Paragraph } = Typography;
const { Option } = Select;
const { Panel } = Collapse;
const { TextArea } = Input;
const { TabPane } = Tabs;

// Handler type configuration
const HANDLER_CONFIG: Record<string, { label: string; color: string; icon: React.ReactNode; description: string }> = {
  api: {
    label: 'API 调用',
    color: 'green',
    icon: <ApiOutlined />,
    description: '通过 HTTP API 调用外部服务',
  },
  carbone: {
    label: 'Carbone 渲染',
    color: 'blue',
    icon: <FileTextOutlined />,
    description: '使用 Carbone 引擎渲染文档',
  },
  browser: {
    label: '浏览器操作',
    color: 'purple',
    icon: <ChromeOutlined />,
    description: '自动化浏览器操作',
  },
  script: {
    label: '脚本执行',
    color: 'orange',
    icon: <CodeOutlined />,
    description: '执行自定义脚本',
  },
};

interface ActivityFormData {
  name: string;
  fn: string;
  timeout: string;
  retryPolicy?: { maxRetries: number };
  handler: 'api' | 'carbone' | 'browser' | 'script';
  config: Record<string, any>;
}

const DEFAULT_ACTIVITY: ActivityFormData = {
  name: '',
  fn: '',
  timeout: '30s',
  retryPolicy: { maxRetries: 3 },
  handler: 'api',
  config: {},
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
};

const ActivityPage: React.FC = () => {
  const { t } = useTranslation(['common', 'admin']);
  const queryClient = useQueryClient();
<<<<<<< HEAD
  const [form] = Form.useForm();
=======

>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
  const [searchText, setSearchText] = useState('');
  const [editModalVisible, setEditModalVisible] = useState(false);
  const [detailModalVisible, setDetailModalVisible] = useState(false);
  const [validateModalVisible, setValidateModalVisible] = useState(false);
<<<<<<< HEAD
  const [simulationModalVisible, setSimulationModalVisible] = useState(false);
  const [codePreviewVisible, setCodePreviewVisible] = useState(false);
  const [editingActivity, setEditingActivity] = useState<ActivityDTO | null>(null);
  const [selectedActivity, setSelectedActivity] = useState<ActivityDTO | null>(null);
  const [validationResult, setValidationResult] = useState<ActivityValidationResult | null>(null);
  const [simulationResult, setSimulationResult] = useState<any>(null);
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const [isGeneratingCode, setIsGeneratingCode] = useState(false);
  const [realValidateModalVisible, setRealValidateModalVisible] = useState(false);
  const [realValidateResult, setRealValidateResult] = useState<any>(null);
  const [isRealValidating, setIsRealValidating] = useState(false);
  const [realValidateLogs, setRealValidateLogs] = useState<string[]>([]);
  const [realValidateError, setRealValidateError] = useState<string | null>(null);
  const [cachedCode, setCachedCode] = useState<string | null>(null);
  const [isCachingCode, setIsCachingCode] = useState(false);
  const [isValidated, setIsValidated] = useState(false);
  const [activityForm, setActivityForm] = useState<ActivityFormData>({
    name: '',
    fn: '',
    description: '',
    taskQueue: 'SKILL_TASK_QUEUE',
    startToCloseTimeout: '60s',
    heartbeatTimeout: undefined,
    scheduleToStartTimeout: '30s',
    scheduleToCloseTimeout: '120s',
    retryPolicy: undefined,
    idempotencyKey: undefined,
    steps: [],
  });

  const activitiesQuery = useQuery(['activities', searchText], () => activityApi.list());

=======
  const [handlerFilter, setHandlerFilter] = useState<string | undefined>();
  const [editingActivity, setEditingActivity] = useState<ActivityDTO | null>(null);
  const [selectedActivity, setSelectedActivity] = useState<ActivityDTO | null>(null);
  const [validationResult, setValidationResult] = useState<ActivityValidationResult | null>(null);
  const [form] = Form.useForm();
  const [activityForm, setActivityForm] = useState<ActivityFormData>(DEFAULT_ACTIVITY);

  // Queries
  const activitiesQuery = useQuery(
    ['activities', handlerFilter],
    () => activityApi.list(handlerFilter)
  );

  // Mutations
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
  const createMutation = useMutation(activityApi.create, {
    onSuccess: () => {
      message.success(t('common:success'));
      queryClient.invalidateQueries(['activities']);
      setEditModalVisible(false);
      form.resetFields();
<<<<<<< HEAD
      resetForm();
    },
    onError: (err: any) => message.error(err?.message || t('common:error')),
  });

  const updateMutation = useMutation(
    ({ id, data }: { id: string; data: Partial<CreateActivityDto> }) => activityApi.update(id, data),
=======
      setActivityForm(DEFAULT_ACTIVITY);
    },
    onError: () => {
      message.error(t('common:error'));
    },
  });

  const updateMutation = useMutation(
    ({ id, data }: { id: string; data: CreateActivityDto }) => activityApi.update(id, data),
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
    {
      onSuccess: () => {
        message.success(t('common:success'));
        queryClient.invalidateQueries(['activities']);
        setEditModalVisible(false);
<<<<<<< HEAD
      },
      onError: (err: any) => message.error(err?.message || t('common:error')),
=======
        setEditingActivity(null);
      },
      onError: () => {
        message.error(t('common:error'));
      },
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
    }
  );

  const deleteMutation = useMutation(activityApi.delete, {
    onSuccess: () => {
      message.success(t('common:success'));
      queryClient.invalidateQueries(['activities']);
    },
<<<<<<< HEAD
    onError: (err: any) => message.error(err?.message || t('common:error')),
=======
    onError: () => {
      message.error(t('common:error'));
    },
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
  });

  const validateMutation = useMutation(activityApi.validate, {
    onSuccess: (result) => {
      setValidationResult(result);
      message.success('验证完成');
    },
<<<<<<< HEAD
    onError: (err: any) => message.error(err?.message || '验证失败'),
  });

  // 真实验证：使用 SSE 流式执行
  const handleRealValidate = async () => {
    setIsRealValidating(true);
    setRealValidateLogs([]);
    setRealValidateError(null);
    setRealValidateResult(null);

    try {
      // 先拉取最新的代码（从服务器获取最新的 activity 配置）
      let code = cachedCode || generatedCode;
      setRealValidateLogs(prev => [...prev, '正在获取最新代码...']);

      // 如果有正在编辑的 activity，从服务器获取最新的 generatedCode
      if (editingActivity) {
        try {
          const latestActivity = await activityApi.getById(editingActivity.id);
          if (latestActivity.generatedCode) {
            code = latestActivity.generatedCode;
            setCachedCode(code);
            setGeneratedCode(code);
            setRealValidateLogs(prev => [...prev, '已从服务器获取最新代码']);
          }
        } catch (e) {
          setRealValidateLogs(prev => [...prev, '获取最新代码失败，使用本地代码']);
        }
      }

      // 如果还是没有代码，则生成新代码
      if (!code) {
        setRealValidateLogs(prev => [...prev, '正在生成代码...']);
        const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';
        const genResult = await activityApi.generateCode({
          name: activityForm.name,
          fn: activityForm.fn,
          timeout: activityForm.startToCloseTimeout,
          handler: handler as any,
          retryPolicy: activityForm.retryPolicy,
          config: {
            description: activityForm.description,
            taskQueue: activityForm.taskQueue,
            steps: activityForm.steps,
            heartbeatTimeout: activityForm.heartbeatTimeout,
            idempotencyKey: activityForm.idempotencyKey,
          },
        });
        if (!genResult.success || !genResult.code) {
          throw new Error(genResult.error || '代码生成失败');
        }
        code = genResult.code;
        setGeneratedCode(code);
        setRealValidateLogs(prev => [...prev, '代码生成完成']);
      }

      // Execute with SSE streaming
      setRealValidateLogs(prev => [...prev, '开始执行代码...']);
      await activityApi.executeCodeStream(
        { code, fn: activityForm.fn, taskQueue: activityForm.taskQueue, input: {} },
        (event) => {
          if (event.type === 'log' && event.message) {
            setRealValidateLogs(prev => [...prev, event.message!]);
          } else if (event.type === 'done') {
            setRealValidateResult(event.result);
            setIsRealValidating(false);
          } else if (event.type === 'error') {
            setRealValidateError(event.message || '执行失败');
            setIsRealValidating(false);
          }
        }
      );
    } catch (err: any) {
      setRealValidateError(err?.message || '真实验证失败');
      setIsRealValidating(false);
    }
  };

  // 重新生成代码（带错误信息）- 生成后保存并重新验证
  const handleRegenerateWithError = async (errorMsg: string) => {
    setRealValidateError(errorMsg); // Keep error visible
    setIsGeneratingCode(true);
    setIsValidated(false); // Reset validation on regeneration

    const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';

    try {
      // 调用生成API，传入错误上下文
      const result = await activityApi.generateCode({
        name: activityForm.name,
        fn: activityForm.fn,
        timeout: activityForm.startToCloseTimeout,
        handler: handler as any,
        retryPolicy: activityForm.retryPolicy,
        config: {
          description: activityForm.description,
          taskQueue: activityForm.taskQueue,
          steps: activityForm.steps,
          heartbeatTimeout: activityForm.heartbeatTimeout,
          idempotencyKey: activityForm.idempotencyKey,
        },
      }, errorMsg); // 传入错误信息指导AI重新生成

      if (!result.success || !result.code) {
        message.error(result.error || '重新生成代码失败');
        setIsGeneratingCode(false);
        return;
      }

      setGeneratedCode(result.code);
      message.success('代码重新生成成功');

      // 如果有正在编辑的Activity，保存新代码到数据库
      if (editingActivity) {
        try {
          await activityApi.update(editingActivity.id, { generatedCode: result.code });
          setCachedCode(result.code);
          message.success('新代码已保存到数据库');
        } catch (e: any) {
          message.error('保存代码失败: ' + (e?.message || '未知错误'));
        }
      }

      setIsGeneratingCode(false);

      // 立即重新验证
      setRealValidateModalVisible(true);
      setRealValidateLogs([]);
      setRealValidateError(null);
      setRealValidateResult(null);

      setRealValidateLogs(prev => [...prev, '代码已重新生成，开始验证...']);

      await activityApi.executeCodeStream(
        { code: result.code, fn: activityForm.fn, taskQueue: activityForm.taskQueue, input: {} },
        (event) => {
          if (event.type === 'log' && event.message) {
            setRealValidateLogs(prev => [...prev, event.message!]);
          } else if (event.type === 'done') {
            setRealValidateResult(event.result);
            setIsRealValidating(false);
            // event.result 结构: {success: false, error: "..."} 或 {success: true, result: {...}}
            const resultSuccess = event.result?.success !== false && !event.result?.error && !event.result?.status_code;
            if (resultSuccess) {
              setIsValidated(true);
              setRealValidateLogs(prev => [...prev, '✓ 验证通过，可以点击保存按钮正式保存']);
            } else if (event.result?.error || event.result?.status_code >= 400) {
              const errorMsg = event.result.error || event.result.message || JSON.stringify(event.result);
              setRealValidateError(errorMsg);
            }
          } else if (event.type === 'error') {
            setRealValidateError(event.message || '执行失败');
            setIsRealValidating(false);
          }
        }
      );
    } catch (err: any) {
      message.error(err?.message || '重新生成失败');
      setIsGeneratingCode(false);
    }
  };

  const handleGenerateCode = async () => {
    const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';
    setIsGeneratingCode(true);
    setIsValidated(false); // Reset validation when generating new code
    try {
      const result = await activityApi.generateCode({
        name: activityForm.name,
        fn: activityForm.fn,
        timeout: activityForm.startToCloseTimeout,
        handler: handler as any,
        retryPolicy: activityForm.retryPolicy,
        config: {
          description: activityForm.description,
          taskQueue: activityForm.taskQueue,
          steps: activityForm.steps,
          heartbeatTimeout: activityForm.heartbeatTimeout,
          idempotencyKey: activityForm.idempotencyKey,
        },
      }); // 无错误上下文，初次生成
      if (result.success && result.code) {
        setGeneratedCode(result.code);
        setRealValidateError(null);
        setCodePreviewVisible(true);
      } else {
        message.error(result.error || '代码生成失败');
      }
    } catch (err: any) {
      message.error(err?.message || '代码生成失败');
    } finally {
      setIsGeneratingCode(false);
    }
  };

  const resetForm = () => {
    setActivityForm({
      name: '', fn: '', description: '', taskQueue: 'SKILL_TASK_QUEUE',
      startToCloseTimeout: '60s', heartbeatTimeout: undefined,
      scheduleToStartTimeout: '30s', scheduleToCloseTimeout: '120s',
      retryPolicy: undefined, idempotencyKey: undefined,
      steps: [],
    });
    setGeneratedCode('');
  };

  const handleCreate = () => {
    setEditingActivity(null);
    resetForm();
    setIsValidated(false);
=======
    onError: () => {
      message.error('验证失败');
    },
  });

  // Handlers
  const handleCreate = () => {
    setEditingActivity(null);
    form.resetFields();
    setActivityForm(DEFAULT_ACTIVITY);
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
    setEditModalVisible(true);
  };

  const handleEdit = (activity: ActivityDTO) => {
    setEditingActivity(activity);
<<<<<<< HEAD
    const steps: ActivityStep[] = activity.config?.steps || [];
    setActivityForm({
      name: activity.name,
      fn: activity.fn,
      description: activity.config?.description || '',
      taskQueue: activity.config?.taskQueue || 'SKILL_TASK_QUEUE',
      startToCloseTimeout: '60s',
      heartbeatTimeout: activity.config?.heartbeatTimeout,
      scheduleToStartTimeout: '30s',
      scheduleToCloseTimeout: '120s',
      retryPolicy: activity.retryPolicy,
      idempotencyKey: activity.config?.idempotencyKey,
      steps,
    });
    // Load saved generated code if exists
    // API returns generatedCode at top level, not inside config
    if (activity.generatedCode) {
      setGeneratedCode(activity.generatedCode);
      setCachedCode(activity.generatedCode); // Also set cached code
      setIsValidated(true); // Already validated since it was saved
    } else {
      setGeneratedCode('');
      setCachedCode(null);
      setIsValidated(false);
    }
=======
    form.setFieldsValue({
      name: activity.name,
      fn: activity.fn,
      timeout: activity.timeout,
      handler: activity.handler,
    });
    setActivityForm({
      name: activity.name,
      fn: activity.fn,
      timeout: activity.timeout,
      retryPolicy: activity.retryPolicy,
      handler: activity.handler as any,
      config: activity.config || {},
    });
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
    setEditModalVisible(true);
  };

  const handleViewDetail = (activity: ActivityDTO) => {
    setSelectedActivity(activity);
    setDetailModalVisible(true);
  };

  const handleValidate = () => {
<<<<<<< HEAD
    setValidationResult(null);
    setValidateModalVisible(true);
    const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';
    validateMutation.mutate({
      name: activityForm.name,
      fn: activityForm.fn,
      timeout: activityForm.startToCloseTimeout,
      handler: handler as any,
      retryPolicy: activityForm.retryPolicy,
      config: {
        taskQueue: activityForm.taskQueue,
        steps: activityForm.steps,
        heartbeatTimeout: activityForm.heartbeatTimeout,
        idempotencyKey: activityForm.idempotencyKey,
      },
    } as any);
  };

  const handleSave = () => {
    const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';
    // Use cached code if available, otherwise use state
    const codeToSave = cachedCode || generatedCode;
    const data: CreateActivityDto = {
      name: activityForm.name,
      fn: activityForm.fn,
      timeout: activityForm.startToCloseTimeout,
      handler: handler as any,
      retryPolicy: activityForm.retryPolicy,
      config: {
        description: activityForm.description,
        taskQueue: activityForm.taskQueue,
        steps: activityForm.steps,
        heartbeatTimeout: activityForm.heartbeatTimeout,
        idempotencyKey: activityForm.idempotencyKey,
        generatedCode: codeToSave || undefined,
      },
    };

    if (editingActivity) {
      updateMutation.mutate({ id: editingActivity.id, data });
    } else {
      createMutation.mutate(data);
    }
  };

  // 缓存代码并立即验证
  const handleCacheAndValidate = async () => {
    if (!generatedCode) {
      message.warning('请先生成代码');
      return;
    }

    if (!editingActivity) {
      message.warning('请先保存 Activity 基本信息');
      return;
    }

    // 1. 先保存代码到数据库
    setIsCachingCode(true);
    let latestCode = generatedCode;
    try {
      await activityApi.update(editingActivity.id, { generatedCode });
      setCachedCode(generatedCode);
      message.success('代码已缓存并保存到数据库');
    } catch (err: any) {
      message.error(err?.message || '保存代码失败');
      setIsCachingCode(false);
      return;
    }

    // 2. 立即触发真实验证 - 先拉取最新代码再执行
    setRealValidateModalVisible(true);
    setRealValidateLogs([]);
    setRealValidateError(null);
    setRealValidateResult(null);

    try {
      setRealValidateLogs(prev => [...prev, '代码已保存，开始验证...']);

      // 先拉取最新代码
      setRealValidateLogs(prev => [...prev, '正在获取最新代码...']);
      try {
        const latestActivity = await activityApi.getById(editingActivity.id);
        if (latestActivity.generatedCode) {
          latestCode = latestActivity.generatedCode;
          setRealValidateLogs(prev => [...prev, '已从数据库获取最新代码']);
        }
      } catch (e) {
        setRealValidateLogs(prev => [...prev, '获取最新代码失败，使用本地代码']);
      }

      await activityApi.executeCodeStream(
        { code: latestCode, fn: activityForm.fn, taskQueue: activityForm.taskQueue, input: {} },
        (event) => {
          if (event.type === 'log' && event.message) {
            setRealValidateLogs(prev => [...prev, event.message!]);
          } else if (event.type === 'done') {
            setRealValidateResult(event.result);
            setIsCachingCode(false);
            setIsRealValidating(false);
            // event.result 结构: {success: false, error: "..."} 或 {success: true, result: {...}}
            const resultSuccess = event.result?.success !== false && !event.result?.error && !event.result?.status_code;
            if (resultSuccess) {
              setIsValidated(true);
              setRealValidateLogs(prev => [...prev, '✓ 验证通过，可以点击保存按钮正式保存']);
            } else if (event.result?.error || event.result?.status_code >= 400) {
              // 执行返回了错误结果
              const errorMsg = event.result.error || event.result.message || JSON.stringify(event.result);
              setRealValidateError(errorMsg);
            }
          } else if (event.type === 'error') {
            setRealValidateError(event.message || '执行失败');
            setIsCachingCode(false);
            setIsRealValidating(false);
          }
        }
      );
    } catch (err: any) {
      setRealValidateError(err?.message || '验证失败');
      setIsCachingCode(false);
      setIsRealValidating(false);
    }
=======
    validateMutation.mutate(activityForm as any);
    setValidateModalVisible(true);
  };

  const handleSave = () => {
    form.validateFields().then(() => {
      if (editingActivity) {
        updateMutation.mutate({ id: editingActivity.id, data: activityForm as any });
      } else {
        createMutation.mutate(activityForm as any);
      }
    });
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
  };

  const handleDelete = (id: string) => {
    Modal.confirm({
      title: t('common:confirmDelete'),
      content: '删除后无法恢复，是否继续？',
      onOk: () => deleteMutation.mutate(id),
    });
  };

<<<<<<< HEAD
  const handleSimulate = (type: 'success' | 'failure' | 'timeout' | 'heartbeat') => {
    setSimulationResult({
      type,
      timestamp: new Date().toISOString(),
      message: type === 'success' ? 'Activity 执行成功' :
        type === 'failure' ? 'Activity 执行失败' :
        type === 'timeout' ? 'Activity 执行超时' : '心跳已发送',
      heartbeatEvents: type === 'heartbeat' ? [
        { time: '00:00:01', stage: 'initializing' },
        { time: '00:00:05', stage: 'executing_step_1' },
        { time: '00:00:10', stage: 'completed' },
      ] : [],
    });
  };

  const updateActivityForm = (field: string, value: any) => {
    setActivityForm((prev) => ({ ...prev, [field]: value }));
  };

  const addStep = () => {
    const newStep: ActivityStep = {
      id: `step_${Date.now()}`,
      name: `步骤 ${activityForm.steps.length + 1}`,
      type: 'api',
      timeout: '30s',
      config: { endpoint: '', method: 'GET' },
    };
    setActivityForm((prev) => ({ ...prev, steps: [...prev.steps, newStep] }));
  };

  const removeStep = (id: string) => {
    setActivityForm((prev) => ({ ...prev, steps: prev.steps.filter(s => s.id !== id) }));
  };

  const updateStep = (id: string, field: string, value: any) => {
    setActivityForm((prev) => ({
      ...prev,
      steps: prev.steps.map(s => s.id === id ? { ...s, [field]: value } : s)
    }));
  };

  const copyCode = () => {
    navigator.clipboard.writeText(generatedCode);
    message.success('代码已复制');
  };

  const columns: ColumnsType<ActivityDTO> = [
    { title: '名称', dataIndex: 'name', key: 'name', width: 180, render: (name, r) => <a onClick={() => handleViewDetail(r)}><Text strong>{name}</Text></a> },
    { title: '函数名', dataIndex: 'fn', key: 'fn', width: 150, render: fn => <Tag color="cyan">{fn}</Tag> },
    { title: '处理器', key: 'handler', width: 80, render: (_, r) => <Tag color={HANDLER_CONFIG[r.handler]?.color}>{HANDLER_CONFIG[r.handler]?.label}</Tag> },
    { title: '步骤', key: 'steps', width: 60, render: (_, r) => <Tag>{r.config?.steps?.length || 0}</Tag> },
    { title: '超时', dataIndex: 'timeout', key: 'timeout', width: 70 },
    { title: '心跳', key: 'heartbeat', width: 60, render: (_, r) => r.config?.heartbeatTimeout ? <Tag color="blue">{r.config.heartbeatTimeout}</Tag> : <Tag>-</Tag> },
    { title: '重试', key: 'retryPolicy', width: 60, render: (_, r) => r.retryPolicy ? <Tag color="orange">有</Tag> : <Tag>无</Tag> },
    { title: '状态', key: 'status', width: 70, render: (_, r) => <Tag color={r.isActive ? 'green' : 'default'}>{r.isActive ? '启用' : '禁用'}</Tag> },
    { title: t('common:actions'), key: 'actions', width: 100, render: (_, r) => (
      <Space size="small">
        <Button type="link" size="small" icon={<EditOutlined />} onClick={() => handleEdit(r)} />
        <Popconfirm title="确认删除" onConfirm={() => handleDelete(r.id)} okText="删除" okButtonProps={{ danger: true }}>
          <Button type="link" size="small" icon={<DeleteOutlined />} danger />
        </Popconfirm>
      </Space>
    )},
  ];

  const filteredActivities = (activitiesQuery.data || []).filter(a =>
    a.name.toLowerCase().includes(searchText.toLowerCase()) || a.fn.toLowerCase().includes(searchText.toLowerCase())
  );

  const stats = {
    total: activitiesQuery.data?.length || 0,
    api: activitiesQuery.data?.filter(a => a.handler === 'api').length || 0,
    script: activitiesQuery.data?.filter(a => a.handler === 'script').length || 0,
    active: activitiesQuery.data?.filter(a => a.isActive).length || 0,
  };

  return (
    <div>
      <Row gutter={16} style={{ marginBottom: 24 }}>
        <Col span={6}><Card><Statistic title="总数" value={stats.total} prefix={<ThunderboltOutlined />} /></Card></Col>
        <Col span={6}><Card><Statistic title="API" value={stats.api} valueStyle={{ color: '#52c41a' }} /></Card></Col>
        <Col span={6}><Card><Statistic title="脚本" value={stats.script} valueStyle={{ color: '#fa8c16' }} /></Card></Col>
        <Col span={6}><Card><Statistic title="已启用" value={stats.active} valueStyle={{ color: '#1890ff' }} /></Card></Col>
      </Row>

      <Card style={{ marginBottom: 16 }}>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <Input placeholder="搜索..." prefix={<SearchOutlined />} value={searchText} onChange={e => setSearchText(e.target.value)} style={{ width: 200 }} allowClear />
          <Space>
            <Button icon={<PlusOutlined />} type="primary" onClick={handleCreate}>创建</Button>
            <Button icon={<ReloadOutlined />} onClick={() => activitiesQuery.refetch()} />
=======
  const updateActivityForm = (field: string, value: any) => {
    setActivityForm(prev => ({ ...prev, [field]: value }));
  };

  // Render handler badge
  const renderHandlerBadge = (handler: string) => {
    const info = HANDLER_CONFIG[handler] || { label: handler, color: 'default' };
    return <Tag color={info.color}>{info.label}</Tag>;
  };

  // Render config fields based on handler type
  const renderConfigFields = () => {
    switch (activityForm.handler) {
      case 'api':
        return (
          <Card size="small" style={{ background: '#fafafa' }}>
            <Paragraph type="secondary">
              API 活动通过 HTTP 请求调用外部服务。配置端点、方法、 Headers 和请求体。
            </Paragraph>
            <Form.Item label="端点 URL">
              <Input
                value={activityForm.config.endpoint || ''}
                onChange={(e) => updateActivityForm('config', { ...activityForm.config, endpoint: e.target.value })}
                placeholder="https://api.example.com/v1/resource"
              />
            </Form.Item>
            <Space>
              <Form.Item label="HTTP 方法">
                <Select
                  value={activityForm.config.method || 'POST'}
                  onChange={(v) => updateActivityForm('config', { ...activityForm.config, method: v })}
                  style={{ width: 120 }}
                >
                  <Option value="GET">GET</Option>
                  <Option value="POST">POST</Option>
                  <Option value="PUT">PUT</Option>
                  <Option value="DELETE">DELETE</Option>
                  <Option value="PATCH">PATCH</Option>
                </Select>
              </Form.Item>
              <Form.Item label="超时 (ms)">
                <Input
                  type="number"
                  value={activityForm.config.timeoutMs || 30000}
                  onChange={(e) => updateActivityForm('config', { ...activityForm.config, timeoutMs: parseInt(e.target.value) })}
                  style={{ width: 100 }}
                />
              </Form.Item>
            </Space>
            <Form.Item label="Headers (JSON)">
              <TextArea
                value={JSON.stringify(activityForm.config.headers || {}, null, 2)}
                onChange={(e) => {
                  try {
                    updateActivityForm('config', { ...activityForm.config, headers: JSON.parse(e.target.value) });
                  } catch {}
                }}
                rows={3}
                placeholder='{"Authorization": "Bearer {{token}}"}'
                style={{ fontFamily: 'monospace' }}
              />
            </Form.Item>
            <Form.Item label="请求体模板 (JSON)">
              <TextArea
                value={JSON.stringify(activityForm.config.body || {}, null, 2)}
                onChange={(e) => {
                  try {
                    updateActivityForm('config', { ...activityForm.config, body: JSON.parse(e.target.value) });
                  } catch {}
                }}
                rows={4}
                placeholder='{"templateId": "{{params.templateId}}"}'
                style={{ fontFamily: 'monospace' }}
              />
            </Form.Item>
          </Card>
        );

      case 'carbone':
        return (
          <Card size="small" style={{ background: '#fafafa' }}>
            <Paragraph type="secondary">
              Carbone 活动使用 Carbone 引擎渲染文档。配置模板 ID 和数据映射。
            </Paragraph>
            <Form.Item label="模板 ID">
              <Input
                value={activityForm.config.templateId || ''}
                onChange={(e) => updateActivityForm('config', { ...activityForm.config, templateId: e.target.value })}
                placeholder="template-invoice-001"
              />
            </Form.Item>
            <Form.Item label="输出格式">
              <Select
                value={activityForm.config.outputFormat || 'docx'}
                onChange={(v) => updateActivityForm('config', { ...activityForm.config, outputFormat: v })}
                style={{ width: 150 }}
              >
                <Option value="docx">DOCX</Option>
                <Option value="xlsx">XLSX</Option>
                <Option value="pptx">PPTX</Option>
                <Option value="pdf">PDF</Option>
              </Select>
            </Form.Item>
            <Form.Item label="数据映射 (JSON)">
              <TextArea
                value={JSON.stringify(activityForm.config.dataMapping || {}, null, 2)}
                onChange={(e) => {
                  try {
                    updateActivityForm('config', { ...activityForm.config, dataMapping: JSON.parse(e.target.value) });
                  } catch {}
                }}
                rows={4}
                placeholder='{"company": "{{params.companyName}}", "amount": "{{params.amount}}"}'
                style={{ fontFamily: 'monospace' }}
              />
            </Form.Item>
          </Card>
        );

      case 'browser':
        return (
          <Card size="small" style={{ background: '#fafafa' }}>
            <Paragraph type="secondary">
              Browser 活动执行浏览器自动化操作。配置操作类型和目标元素。
            </Paragraph>
            <Form.Item label="操作类型">
              <Select
                value={activityForm.config.action || 'click'}
                onChange={(v) => updateActivityForm('config', { ...activityForm.config, action: v })}
                style={{ width: 150 }}
              >
                <Option value="click">点击</Option>
                <Option value="fill">填写</Option>
                <Option value="select">选择</Option>
                <Option value="hover">悬停</Option>
                <Option value="screenshot">截图</Option>
                <Option value="evaluate">执行脚本</Option>
              </Select>
            </Form.Item>
            <Form.Item label="CSS 选择器">
              <Input
                value={activityForm.config.selector || ''}
                onChange={(e) => updateActivityForm('config', { ...activityForm.config, selector: e.target.value })}
                placeholder="#submit-button"
              />
            </Form.Item>
            <Form.Item label="输入值">
              <TextArea
                value={activityForm.config.value || ''}
                onChange={(e) => updateActivityForm('config', { ...activityForm.config, value: e.target.value })}
                rows={2}
                placeholder="要填写或选择的值"
              />
            </Form.Item>
          </Card>
        );

      case 'script':
        return (
          <Card size="small" style={{ background: '#fafafa' }}>
            <Paragraph type="secondary">
              Script 活动执行自定义 JavaScript/TypeScript 脚本。脚本应返回 Promise。
            </Paragraph>
            <Form.Item label="脚本内容">
              <TextArea
                value={activityForm.config.script || ''}
                onChange={(e) => updateActivityForm('config', { ...activityForm.config, script: e.target.value })}
                rows={8}
                placeholder={'async function execute(params) {\n  // your code here\n  return { result: "success" };\n}'}
                style={{ fontFamily: 'monospace' }}
              />
            </Form.Item>
          </Card>
        );

      default:
        return null;
    }
  };

  // Render config display in detail modal
  const renderConfigDisplay = (config: Record<string, any>, handler: string) => {
    switch (handler) {
      case 'api':
        return (
          <Descriptions size="small" bordered column={1}>
            <Descriptions.Item label="端点">{config.endpoint || '-'}</Descriptions.Item>
            <Descriptions.Item label="方法">{config.method || 'POST'}</Descriptions.Item>
            <Descriptions.Item label="超时">{config.timeoutMs || 30000}ms</Descriptions.Item>
            <Descriptions.Item label="Headers">
              <pre style={{ margin: 0, fontSize: 12 }}>{JSON.stringify(config.headers || {}, null, 2)}</pre>
            </Descriptions.Item>
            <Descriptions.Item label="请求体">
              <pre style={{ margin: 0, fontSize: 12 }}>{JSON.stringify(config.body || {}, null, 2)}</pre>
            </Descriptions.Item>
          </Descriptions>
        );

      case 'carbone':
        return (
          <Descriptions size="small" bordered column={1}>
            <Descriptions.Item label="模板 ID">{config.templateId || '-'}</Descriptions.Item>
            <Descriptions.Item label="输出格式">{config.outputFormat || 'docx'}</Descriptions.Item>
            <Descriptions.Item label="数据映射">
              <pre style={{ margin: 0, fontSize: 12 }}>{JSON.stringify(config.dataMapping || {}, null, 2)}</pre>
            </Descriptions.Item>
          </Descriptions>
        );

      case 'browser':
        return (
          <Descriptions size="small" bordered column={1}>
            <Descriptions.Item label="操作">{config.action || '-'}</Descriptions.Item>
            <Descriptions.Item label="选择器">{config.selector || '-'}</Descriptions.Item>
            <Descriptions.Item label="值">{config.value || '-'}</Descriptions.Item>
          </Descriptions>
        );

      case 'script':
        return (
          <Descriptions size="small" bordered column={1}>
            <Descriptions.Item label="脚本">
              <pre style={{ margin: 0, fontSize: 12, maxHeight: 200, overflow: 'auto' }}>
                {config.script || '// 无脚本内容'}
              </pre>
            </Descriptions.Item>
          </Descriptions>
        );

      default:
        return <Text>配置详情不可用</Text>;
    }
  };

  // Columns
  const columns: ColumnsType<ActivityDTO> = [
    {
      title: '活动名称',
      dataIndex: 'name',
      key: 'name',
      width: 200,
      render: (name: string, record: ActivityDTO) => (
        <a onClick={() => handleViewDetail(record)} style={{ cursor: 'pointer' }}>
          <strong>{name}</strong>
        </a>
      ),
    },
    {
      title: '函数名',
      dataIndex: 'fn',
      key: 'fn',
      width: 150,
      render: (fn: string) => <Tag>{fn}</Tag>,
    },
    {
      title: '处理器',
      dataIndex: 'handler',
      key: 'handler',
      width: 120,
      render: (handler: string) => renderHandlerBadge(handler),
    },
    {
      title: '超时',
      dataIndex: 'timeout',
      key: 'timeout',
      width: 80,
      render: (timeout: string) => <Tag color="blue">{timeout}</Tag>,
    },
    {
      title: '重试策略',
      key: 'retryPolicy',
      width: 100,
      render: (_, record) => (
        record.retryPolicy ? (
          <Tag color="orange">最多 {record.retryPolicy.maxRetries} 次</Tag>
        ) : (
          <Text type="secondary">无</Text>
        )
      ),
    },
    {
      title: '状态',
      key: 'status',
      width: 80,
      render: (_, record) => (
        <Tag color={record.isActive ? 'green' : 'default'}>
          {record.isActive ? '已启用' : '已禁用'}
        </Tag>
      ),
    },
    {
      title: t('common:actions'),
      key: 'actions',
      width: 180,
      fixed: 'right',
      render: (_, record) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
          >
            编辑
          </Button>
          <Popconfirm
            title="确认删除"
            description="删除后无法恢复"
            onConfirm={() => handleDelete(record.id)}
            okText="删除"
            cancelText="取消"
            okButtonProps={{ danger: true }}
          >
            <Button
              type="link"
              size="small"
              icon={<DeleteOutlined />}
              danger
            />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <Title level={4}>Activity 管理</Title>

      <Card style={{ marginTop: 8, marginBottom: 16 }}>
        <Space direction="vertical" size="small">
          <Text strong>Activity 说明：</Text>
          <Text>• Activity 是 Temporal 工作流中的非确定性副作用操作</Text>
          <Text>• 每个 Activity 可以调用 API、渲染文档、执行浏览器操作或运行脚本</Text>
          <Text>• Activity 支持重试策略和超时配置</Text>
          <Divider style={{ margin: '8px 0' }} />
          <Text strong>处理器类型：</Text>
          <Space wrap>
            {Object.entries(HANDLER_CONFIG).map(([key, info]) => (
              <Tag key={key} color={info.color} icon={info.icon as any}>
                {info.label}
              </Tag>
            ))}
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
          </Space>
        </Space>
      </Card>

      <Card>
<<<<<<< HEAD
        <Table columns={columns} dataSource={filteredActivities} rowKey="id" loading={activitiesQuery.isLoading} pagination={{ showSizeChanger: true, showTotal: total => `共 ${total} 条` }} />
      </Card>

      {/* Edit Modal */}
      <Modal
        title={editingActivity ? '编辑 Activity' : '创建 Activity'}
        open={editModalVisible}
        onCancel={() => setEditModalVisible(false)}
        footer={null}
        width={1000}
        destroyOnClose
      >
        <Form layout="vertical">
          {/* Basic Info */}
          <Card size="small" style={{ marginBottom: 16 }}>
            <Row gutter={16}>
              <Col span={12}>
                <Form.Item label="名称" required>
                  <Input value={activityForm.name} onChange={e => updateActivityForm('name', e.target.value)} placeholder="天气查询" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item label="函数名" required>
                  <Input value={activityForm.fn} onChange={e => updateActivityForm('fn', e.target.value)} placeholder="weatherQuery" />
                </Form.Item>
              </Col>
            </Row>
            <Row gutter={16}>
              <Col span={24}>
                <Form.Item label="AI 指导说明（描述这个 Activity 的功能，让 AI 生成更准确的代码）">
                  <TextArea value={activityForm.description} onChange={e => updateActivityForm('description', e.target.value)} placeholder="例如：这是一个天气查询 Activity，查询上海和北京两地的天气并返回结果..." rows={2} />
                </Form.Item>
              </Col>
            </Row>
            <Row gutter={16}>
              <Col span={12}>
                <Form.Item label="Task Queue">
                  <Input value={activityForm.taskQueue} onChange={e => updateActivityForm('taskQueue', e.target.value)} />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item label="StartToClose 超时">
                  <Select value={activityForm.startToCloseTimeout} onChange={v => updateActivityForm('startToCloseTimeout', v)}>
                    <Option value="30s">30s</Option>
                    <Option value="60s">60s</Option>
                    <Option value="120s">120s</Option>
                    <Option value="300s">300s</Option>
                  </Select>
                </Form.Item>
              </Col>
            </Row>
          </Card>

          {/* Optional Settings */}
          <Card size="small" style={{ marginBottom: 16 }}>
            <Title level={5} style={{ marginBottom: 12 }}><SettingOutlined /> 可选配置（指导 AI 生成代码）</Title>
            <Row gutter={16}>
              <Col span={8}>
                <Form.Item label="心跳超时">
                  <Space>
                    <Switch checked={!!activityForm.heartbeatTimeout} onChange={checked => updateActivityForm('heartbeatTimeout', checked ? '30s' : undefined)} />
                    {activityForm.heartbeatTimeout && (
                      <Select value={activityForm.heartbeatTimeout} onChange={v => updateActivityForm('heartbeatTimeout', v)} style={{ width: 100 }}>
                        <Option value="5s">5s</Option>
                        <Option value="10s">10s</Option>
                        <Option value="30s">30s</Option>
                        <Option value="60s">60s</Option>
                      </Select>
                    )}
                  </Space>
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item label="ScheduleToStart">
                  <Select value={activityForm.scheduleToStartTimeout} onChange={v => updateActivityForm('scheduleToStartTimeout', v)}>
                    <Option value="10s">10s</Option>
                    <Option value="30s">30s</Option>
                    <Option value="60s">60s</Option>
                  </Select>
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item label="ScheduleToClose">
                  <Select value={activityForm.scheduleToCloseTimeout} onChange={v => updateActivityForm('scheduleToCloseTimeout', v)}>
                    <Option value="60s">60s</Option>
                    <Option value="120s">120s</Option>
                    <Option value="300s">300s</Option>
                  </Select>
                </Form.Item>
              </Col>
            </Row>
            <Row gutter={16}>
              <Col span={12}>
                <Form.Item label="幂等键策略（指导 AI 生成）">
                  <Switch checked={!!activityForm.idempotencyKey} onChange={checked => updateActivityForm('idempotencyKey', checked ? "{{workflowId}}-{{activityName}}-{{inputHash}}" : undefined)} />
                  {activityForm.idempotencyKey && (
                    <Input value={activityForm.idempotencyKey} onChange={e => updateActivityForm('idempotencyKey', e.target.value || undefined)} placeholder="{{workflowId}}-{{activityName}}-{{inputHash}}" style={{ marginLeft: 16, width: 200 }} />
                  )}
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item label="重试策略">
                  <Switch checked={!!activityForm.retryPolicy} onChange={checked => updateActivityForm('retryPolicy', checked ? { maxRetries: 3, backoffMs: 1000 } : undefined)} />
                  {activityForm.retryPolicy && (
                    <Space style={{ marginLeft: 16 }}>
                      <InputNumber value={activityForm.retryPolicy.maxRetries} onChange={v => updateActivityForm('retryPolicy', { ...activityForm.retryPolicy!, maxRetries: v || 0 })} min={1} max={10} size="small" />
                      <Text type="secondary">次</Text>
                    </Space>
                  )}
                </Form.Item>
              </Col>
            </Row>
          </Card>

          {/* Steps */}
          <Card size="small" style={{ marginBottom: 16 }}>
            <Title level={5} style={{ marginBottom: 12 }}><OrderedListOutlined /> 步骤列表</Title>
            <Button type="dashed" icon={<PlusOutlined />} onClick={addStep} block style={{ marginBottom: 12 }}>
              添加步骤
            </Button>
            {activityForm.steps.length === 0 ? (
              <Text type="secondary">添加步骤来定义 Activity 的执行流程</Text>
            ) : (
              activityForm.steps.map((step, idx) => (
                <Card key={step.id} size="small" style={{ marginBottom: 8, border: '1px solid #d9d9d9' }}>
                  <Row gutter={12} align="middle">
                    <Col><Badge count={idx + 1} style={{ backgroundColor: '#1890ff' }} /></Col>
                    <Col flex={1}>
                      <Input value={step.name} onChange={e => updateStep(step.id, 'name', e.target.value)} placeholder="步骤名称" style={{ marginBottom: 8 }} />
                      <Space>
                        <Select value={step.type} onChange={v => updateStep(step.id, 'type', v)} style={{ width: 100 }}>
                          <Option value="api">API</Option>
                          <Option value="script">脚本</Option>
                          <Option value="carbone">Carbone</Option>
                          <Option value="browser">浏览器</Option>
                        </Select>
                        <Input value={step.timeout} onChange={e => updateStep(step.id, 'timeout', e.target.value)} placeholder="超时" style={{ width: 70 }} />
                      </Space>
                    </Col>
                    <Col>
                      <Button type="text" danger icon={<DeleteOutlined />} onClick={() => removeStep(step.id)} />
                    </Col>
                  </Row>
                  {step.type === 'api' && (
                    <div style={{ marginTop: 8, padding: 8, background: '#f6ffed', borderRadius: 4 }}>
                      <Input value={step.config.endpoint || ''} onChange={e => updateStep(step.id, 'config', { ...step.config, endpoint: e.target.value })} placeholder="https://uapis.cn/api/v1/misc/weather?city=北京" prefix={<ApiOutlined />} />
                    </div>
                  )}
                  {step.type === 'script' && (
                    <div style={{ marginTop: 8, padding: 8, background: '#fff7e6', borderRadius: 4 }}>
                      <TextArea value={step.config.script || ''} onChange={e => updateStep(step.id, 'config', { ...step.config, script: e.target.value })} placeholder="// 代码..." rows={2} style={{ fontFamily: 'monospace' }} />
                    </div>
                  )}
                </Card>
              ))
            )}
          </Card>

          {/* Actions */}
          <Space style={{ width: '100%', justifyContent: 'flex-end' }}>
            <Button icon={<RobotOutlined />} onClick={handleGenerateCode} loading={isGeneratingCode}>AI 生成代码</Button>
            <Button icon={<EyeOutlined />} onClick={() => setCodePreviewVisible(true)} disabled={!generatedCode}>查看代码</Button>
            <Button icon={<PlayCircleOutlined />} onClick={handleValidate}>验证配置</Button>
            <Button icon={<ThunderboltOutlined />} onClick={() => setRealValidateModalVisible(true)} disabled={!cachedCode && !generatedCode}>真实验证</Button>
            <Button icon={<ExperimentOutlined />} onClick={() => setSimulationModalVisible(true)}>模拟</Button>
            <Button onClick={() => setEditModalVisible(false)}>取消</Button>
            <Button type="primary" icon={<SaveOutlined />} loading={createMutation.isLoading || updateMutation.isLoading} onClick={handleSave} disabled={!isValidated && !!generatedCode}>保存{!isValidated && !!generatedCode ? '（请先验证）' : ''}</Button>
          </Space>
        </Form>
      </Modal>

      {/* Code Preview Modal */}
      <Modal
        title={<Space><RobotOutlined /> AI 生成的 Python 代码</Space>}
        open={codePreviewVisible}
        onCancel={() => { setCodePreviewVisible(false); setIsGeneratingCode(false); }}
        footer={[
          <Button key="copy" icon={<CopyOutlined />} onClick={copyCode}>复制代码</Button>,
          <Button key="cache" type="primary" icon={<ThunderboltOutlined />} onClick={handleCacheAndValidate} loading={isCachingCode || isRealValidating}>
            {isValidated ? '已验证' : '缓存并验证'}
          </Button>,
          <Button key="close" onClick={() => { setCodePreviewVisible(false); setIsGeneratingCode(false); }}>关闭</Button>
        ]}
        width={800}
      >
        <Paragraph type="secondary" style={{ marginBottom: 16 }}>
          以下代码由 AI 根据您的配置自动生成，可用于参考或复制到 Temporal Worker 中使用。点击"缓存代码"可保存到配置中。
        </Paragraph>
        <Card bodyStyle={{ padding: 0 }} style={{ background: '#1e1e1e', borderRadius: 8 }}>
          {isGeneratingCode ? (
            <div style={{ padding: 40, textAlign: 'center', color: '#d4d4d4' }}>
              <LoadingOutlined style={{ fontSize: 24 }} /><br /><br />
              正在生成代码，请稍候...
            </div>
          ) : (
            <pre style={{ color: '#d4d4d4', padding: 16, margin: 0, fontFamily: 'Monaco, Menlo, "Ubuntu Mono", monospace', fontSize: 12, lineHeight: 1.5, overflow: 'auto', maxHeight: 500 }}>
              {generatedCode || generatePythonCode(activityForm)}
            </pre>
          )}
        </Card>
      </Modal>

      {/* Simulation Modal */}
      <Modal title="模拟测试" open={simulationModalVisible} onCancel={() => setSimulationModalVisible(false)} footer={null} width={500}>
        <Space direction="vertical" style={{ width: '100%' }}>
          <Text>选择场景：</Text>
          <Space wrap>
            <Button icon={<CheckCircleOutlined />} onClick={() => handleSimulate('success')} type="primary">成功</Button>
            <Button icon={<WarningOutlined />} danger onClick={() => handleSimulate('failure')}>失败</Button>
            <Button icon={<ClockCircleOutlined />} onClick={() => handleSimulate('timeout')}>超时</Button>
            <Button icon={<HeartOutlined />} onClick={() => handleSimulate('heartbeat')}>心跳</Button>
          </Space>
          {simulationResult && (
            <Card size="small" style={{ marginTop: 16, background: '#f5f5f5' }}>
              <p><strong>类型：</strong>{simulationResult.type}</p>
              <p><strong>消息：</strong>{simulationResult.message}</p>
              {simulationResult.heartbeatEvents?.length > 0 && (
                <>
                  <p><strong>心跳事件：</strong></p>
                  <ul>{simulationResult.heartbeatEvents.map((e: any, i: number) => <li key={i}>{e.time} - {e.stage}</li>)}</ul>
                </>
              )}
            </Card>
          )}
        </Space>
      </Modal>

      {/* Detail Modal */}
      <Modal title="详情" open={detailModalVisible} onCancel={() => setDetailModalVisible(false)} footer={null} width={700}>
        {selectedActivity && (
          <Collapse defaultActiveKey={['basic', 'monitoring', 'steps']}>
            <Panel header={<Text><ThunderboltOutlined /> 基本信息</Text>} key="basic">
              <Row gutter={16}>
                <Col span={12}><Text><strong>名称:</strong> {selectedActivity.name}</Text></Col>
                <Col span={12}><Text><strong>函数名:</strong> <Tag color="cyan">{selectedActivity.fn}</Tag></Text></Col>
                <Col span={24}><Text><strong>说明:</strong> {selectedActivity.config?.description || '无'}</Text></Col>
                <Col span={12}><Text><strong>超时:</strong> {selectedActivity.timeout}</Text></Col>
                <Col span={12}><Text><strong>心跳:</strong> {selectedActivity.config?.heartbeatTimeout || '未配置'}</Text></Col>
                <Col span={12}><Text><strong>幂等键:</strong> {selectedActivity.config?.idempotencyKey || '未配置'}</Text></Col>
              </Row>
            </Panel>
            <Panel header={<Text><OrderedListOutlined /> 步骤详情 ({selectedActivity.config?.steps?.length || 0})</Text>} key="steps">
              {selectedActivity.config?.steps?.map((step: any, idx: number) => (
                <Card key={idx} size="small" style={{ marginBottom: 8 }}>
                  <Text strong>步骤 {idx + 1}: {step.name}</Text>
                  <br />
                  <Text type="secondary">类型: {step.type} | 超时: {step.timeout}</Text>
                  {step.type === 'api' && <div><Text type="secondary">端点: {step.config?.endpoint}</Text></div>}
                </Card>
              ))}
            </Panel>
            <Panel header={<Text><LineChartOutlined /> 监控</Text>} key="monitoring">
              <Row gutter={16}>
                <Col span={8}><Card size="small"><Statistic title="平均耗时" value="1.2s" /></Card></Col>
                <Col span={8}><Card size="small"><Statistic title="失败率" value="0.5%" valueStyle={{ color: '#52c41a' }} /></Card></Col>
                <Col span={8}><Card size="small"><Statistic title="Backlog" value="12" /></Card></Col>
              </Row>
=======
        <Space style={{ marginBottom: 16, width: '100%', justifyContent: 'space-between' }}>
          <Space>
            <Input
              placeholder="搜索活动..."
              prefix={<SearchOutlined />}
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
              style={{ width: 200 }}
              allowClear
            />
            <Select
              placeholder="筛选处理器"
              value={handlerFilter}
              onChange={setHandlerFilter}
              allowClear
              style={{ width: 150 }}
            >
              {Object.entries(HANDLER_CONFIG).map(([key, info]) => (
                <Option key={key} value={key}>{info.label}</Option>
              ))}
            </Select>
          </Space>
          <Space>
            <Button
              icon={<PlusOutlined />}
              type="primary"
              onClick={handleCreate}
            >
              创建 Activity
            </Button>
            <Button
              icon={<ReloadOutlined />}
              onClick={() => activitiesQuery.refetch()}
            >
              {t('common:refresh')}
            </Button>
          </Space>
        </Space>

        <Table
          columns={columns}
          dataSource={activitiesQuery.data || []}
          rowKey="id"
          loading={activitiesQuery.isLoading}
          scroll={{ x: 1000 }}
          pagination={{
            showSizeChanger: true,
            showTotal: (total) => t('common:pagination.total', { total }),
          }}
        />
      </Card>

      {/* Detail Modal */}
      <Modal
        title={`Activity 详情 - ${selectedActivity?.name}`}
        open={detailModalVisible}
        onCancel={() => {
          setDetailModalVisible(false);
          setSelectedActivity(null);
        }}
        footer={null}
        width={700}
      >
        {selectedActivity && (
          <Collapse defaultActiveKey={['basic', 'config']}>
            <Panel header="基本信息" key="basic">
              <Descriptions size="small" column={2}>
                <Descriptions.Item label="ID">{selectedActivity.id}</Descriptions.Item>
                <Descriptions.Item label="状态">
                  {selectedActivity.isActive ? <Tag color="green">已启用</Tag> : <Tag>已禁用</Tag>}
                </Descriptions.Item>
                <Descriptions.Item label="名称">{selectedActivity.name}</Descriptions.Item>
                <Descriptions.Item label="函数名">{selectedActivity.fn}</Descriptions.Item>
                <Descriptions.Item label="超时">{selectedActivity.timeout}</Descriptions.Item>
                <Descriptions.Item label="处理器">{renderHandlerBadge(selectedActivity.handler)}</Descriptions.Item>
                <Descriptions.Item label="重试策略">
                  {selectedActivity.retryPolicy ? (
                    <Tag color="orange">最多 {selectedActivity.retryPolicy.maxRetries} 次</Tag>
                  ) : (
                    <Text type="secondary">无</Text>
                  )}
                </Descriptions.Item>
              </Descriptions>
            </Panel>
            <Panel header="配置详情" key="config">
              {renderConfigDisplay(selectedActivity.config || {}, selectedActivity.handler)}
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
            </Panel>
          </Collapse>
        )}
      </Modal>

<<<<<<< HEAD
      {/* Validation Modal */}
      <Modal title="验证结果" open={validateModalVisible} onCancel={() => setValidateModalVisible(false)} footer={[<Button onClick={() => setValidateModalVisible(false)}>关闭</Button>]}>
        {validateMutation.isPending ? (
          <div style={{ padding: 40, textAlign: 'center' }}>
            <LoadingOutlined style={{ fontSize: 24 }} /><br /><br />
            正在验证配置，请稍候...
          </div>
        ) : validationResult ? (
          <Space direction="vertical" style={{ width: '100%' }}>
            <Alert type={validationResult.isValid ? 'success' : 'error'} message={validationResult.isValid ? '验证通过' : '验证失败'} showIcon />
            <Text>评分: {validationResult.score}/100</Text>
            <Text type="secondary" style={{ fontSize: 12 }}>
              说明：验证仅检查配置结构有效性，不执行生成的 Python 代码。生成的代码可直接复制到 Temporal Worker 使用。
            </Text>
            {validationResult.errors?.length > 0 && <Alert type="error" message="错误" description={<ul>{validationResult.errors.map((e, i) => <li key={i}>{e}</li>)}</ul>} />}
            {validationResult.warnings?.length > 0 && <Alert type="warning" message="警告" description={<ul>{validationResult.warnings.map((w, i) => <li key={i}>{w}</li>)}</ul>} />}
            {validationResult.suggestions?.length > 0 && <Alert type="info" message="建议" description={<ul>{validationResult.suggestions.map((s, i) => <li key={i}>{s}</li>)}</ul>} />}
          </Space>
        ) : <Alert type="info" message="点击验证按钮开始验证" />}
      </Modal>

      {/* Real Validation Modal - SSE 流式执行真实代码 */}
      <Modal
        title={<Space><ThunderboltOutlined /> 真实验证（执行代码）</Space>}
        open={realValidateModalVisible}
        onCancel={() => { setRealValidateModalVisible(false); setIsRealValidating(false); setRealValidateLogs([]); setRealValidateError(null); }}
        footer={[<Button onClick={() => setRealValidateModalVisible(false)}>关闭</Button>]}
        width={800}
      >
        <Space direction="vertical" style={{ width: '100%' }}>
          {realValidateError && (
            <Alert
              type="error"
              message="执行失败"
              description={
                <div>
                  <pre style={{ margin: '8px 0', fontSize: 12, whiteSpace: 'pre-wrap' }}>{realValidateError}</pre>
                  <Button
                    type="primary"
                    icon={<RobotOutlined />}
                    onClick={() => handleRegenerateWithError(realValidateError)}
                    loading={isGeneratingCode}
                    style={{ marginTop: 8 }}
                  >
                    重新生成代码
                  </Button>
                </div>
              }
              showIcon
            />
          )}

          {realValidateResult && !realValidateError && (
            <Alert
              type={realValidateResult.success ? 'success' : 'error'}
              message={realValidateResult.success ? '执行成功' : '执行失败'}
              showIcon
            />
          )}

          <div>
            <Text strong>执行日志：</Text>
            <div style={{ background: '#1e1e1e', color: '#d4d4d4', padding: 12, borderRadius: 4, maxHeight: 300, overflow: 'auto', marginTop: 8 }}>
              <pre style={{ margin: 0, fontSize: 11 }}>
                {realValidateLogs.map((log, i) => (
                  <div key={i}>{log}</div>
                ))}
                {isRealValidating && <span style={{ color: '#1890ff' }}>▋</span>}
              </pre>
            </div>
          </div>

          {realValidateResult && !realValidateError && realValidateResult.result && (
            <Card size="small" style={{ background: '#f5f5f5' }}>
              <Text strong>执行结果：</Text>
              <pre style={{ margin: '8px 0', fontSize: 12, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
                {typeof realValidateResult.result === 'string' ? realValidateResult.result : JSON.stringify(realValidateResult.result, null, 2)}
              </pre>
            </Card>
          )}

          {!isRealValidating && !realValidateResult && !realValidateError && (
            <Alert type="info" message="真实验证将执行以下步骤：" description={
              <ul style={{ margin: '8px 0' }}>
                <li>1. 使用已保存的代码（如有）</li>
                <li>2. 或重新生成最新 AI 代码</li>
                <li>3. 将代码发送到 Temporal Worker 执行</li>
                <li>4. 实时返回执行日志</li>
              </ul>
            } />
          )}

          {!isRealValidating && (
            <Button
              type="primary"
              icon={<ThunderboltOutlined />}
              onClick={handleRealValidate}
              loading={isGeneratingCode}
            >
              {generatedCode ? '使用已有代码执行' : '生成代码并执行'}
            </Button>
          )}
        </Space>
=======
      {/* Edit/Create Modal */}
      <Modal
        title={editingActivity ? '编辑 Activity' : '创建 Activity'}
        open={editModalVisible}
        onOk={handleSave}
        onCancel={() => {
          setEditModalVisible(false);
          setEditingActivity(null);
        }}
        footer={[
          <Button
            key="validate"
            icon={<PlayCircleOutlined />}
            onClick={handleValidate}
            style={{ marginRight: 8 }}
          >
            验证
          </Button>,
          <Button
            key="cancel"
            onClick={() => setEditModalVisible(false)}
          >
            取消
          </Button>,
          <Button
            key="save"
            type="primary"
            loading={createMutation.isLoading || updateMutation.isLoading}
            onClick={handleSave}
          >
            保存
          </Button>,
        ]}
        confirmLoading={createMutation.isLoading || updateMutation.isLoading}
        width={800}
        style={{ top: 20 }}
      >
        <Form form={form} layout="vertical">
          <Space style={{ width: '100%' }} direction="vertical">
            <Form.Item
              name="name"
              label="活动名称"
              rules={[{ required: true, message: '请输入活动名称' }]}
            >
              <Input placeholder="例如：生成合同参数" />
            </Form.Item>
            <Form.Item
              name="fn"
              label="函数名"
              rules={[{ required: true, message: '请输入函数名' }]}
            >
              <Input placeholder="例如：generateContractParams" />
            </Form.Item>
            <Space>
              <Form.Item
                name="timeout"
                label="超时时间"
                rules={[{ required: true, message: '请输入超时时间' }]}
              >
                <Select
                  value={activityForm.timeout}
                  onChange={(v) => updateActivityForm('timeout', v)}
                  style={{ width: 120 }}
                >
                  <Option value="10s">10s</Option>
                  <Option value="30s">30s</Option>
                  <Option value="1m">1m</Option>
                  <Option value="5m">5m</Option>
                  <Option value="10m">10m</Option>
                </Select>
              </Form.Item>
              <Form.Item
                name="handler"
                label="处理器类型"
                rules={[{ required: true, message: '请选择处理器类型' }]}
              >
                <Select
                  value={activityForm.handler}
                  onChange={(v) => updateActivityForm('handler', v)}
                  style={{ width: 150 }}
                >
                  {Object.entries(HANDLER_CONFIG).map(([key, info]) => (
                    <Option key={key} value={key}>
                      <Space>{info.icon} {info.label}</Space>
                    </Option>
                  ))}
                </Select>
              </Form.Item>
            </Space>
            <Form.Item label="重试策略">
              <Space>
                <Switch
                  checked={!!activityForm.retryPolicy}
                  onChange={(checked) => {
                    if (checked) {
                      updateActivityForm('retryPolicy', { maxRetries: 3 });
                    } else {
                      updateActivityForm('retryPolicy', undefined);
                    }
                  }}
                />
                {activityForm.retryPolicy && (
                  <Input
                    type="number"
                    value={activityForm.retryPolicy.maxRetries}
                    onChange={(e) => updateActivityForm('retryPolicy', { maxRetries: parseInt(e.target.value) || 0 })}
                    style={{ width: 80 }}
                    placeholder="重试次数"
                  />
                )}
              </Space>
            </Form.Item>
          </Space>

          <Divider orientation="left">
            <Space>
              {HANDLER_CONFIG[activityForm.handler]?.icon}
              <Text strong>配置详情</Text>
              <Tag color={HANDLER_CONFIG[activityForm.handler]?.color}>
                {HANDLER_CONFIG[activityForm.handler]?.description}
              </Tag>
            </Space>
          </Divider>

          {renderConfigFields()}
        </Form>
      </Modal>

      {/* Validate Modal */}
      <Modal
        title="验证 Activity 配置"
        open={validateModalVisible}
        onCancel={() => {
          setValidateModalVisible(false);
          setValidationResult(null);
        }}
        footer={[
          <Button
            key="close"
            onClick={() => {
              setValidateModalVisible(false);
              setValidationResult(null);
            }}
          >
            关闭
          </Button>,
        ]}
        width={600}
      >
        {validationResult ? (
          <Space direction="vertical" style={{ width: '100%' }}>
            <Alert
              type={validationResult.isValid ? 'success' : 'error'}
              message={validationResult.isValid ? '验证通过' : '验证失败'}
              icon={validationResult.isValid ? <CheckCircleOutlined /> : <WarningOutlined />}
              showIcon
            />
            <Card size="small">
              <Space direction="vertical">
                <Text>
                  <strong>评分:</strong> {validationResult.score}/100
                </Text>
              </Space>
            </Card>
            {validationResult.errors.length > 0 && (
              <Alert
                type="error"
                message="错误"
                description={
                  <ul>
                    {validationResult.errors.map((e, i) => <li key={i}>{e}</li>)}
                  </ul>
                }
              />
            )}
            {validationResult.warnings.length > 0 && (
              <Alert
                type="warning"
                message="警告"
                description={
                  <ul>
                    {validationResult.warnings.map((w, i) => <li key={i}>{w}</li>)}
                  </ul>
                }
              />
            )}
            {validationResult.suggestions && validationResult.suggestions.length > 0 && (
              <Alert
                type="info"
                message="建议"
                description={
                  <ul>
                    {validationResult.suggestions.map((s, i) => <li key={i}>{s}</li>)}
                  </ul>
                }
              />
            )}
          </Space>
        ) : (
          <Alert type="info" message="点击验证按钮开始验证" />
        )}
>>>>>>> 326e2d06510e0b3ff127d572df7deb4ecb7b1191
      </Modal>
    </div>
  );
};

export default ActivityPage;