import React, { useState, useRef } from 'react';
import {
  Table, Card, Button, Input, Space, Tag, Typography, Modal, message, Form, Select,
  Divider, Alert, Collapse, Badge, Popconfirm, Statistic, Row, Col, Switch, InputNumber
} from 'antd';
import {
  SearchOutlined, PlusOutlined, EditOutlined, DeleteOutlined, PlayCircleOutlined,
  ReloadOutlined, ApiOutlined, CodeOutlined, FileTextOutlined, ChromeOutlined,
  CheckCircleOutlined, ThunderboltOutlined, SettingOutlined,
  ExperimentOutlined, HeartOutlined, ClockCircleOutlined, RetweetOutlined,
  LineChartOutlined, WarningOutlined, OrderedListOutlined, CopyOutlined,
  SaveOutlined, RobotOutlined, EyeOutlined, LoadingOutlined
} from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import { useQuery, useMutation, useQueryClient } from 'react-query';
import { activityApi, ActivityDTO, CreateActivityDto, ActivityValidationResult } from '../../api/activity';
import type { ColumnsType } from 'antd/es/table';

const { Text, Title, Paragraph } = Typography;
const { Option } = Select;
const { Panel } = Collapse;
const { TextArea } = Input;

const HANDLER_CONFIG: Record<string, { label: string; color: string; icon: React.ReactNode }> = {
  api: { label: 'API', color: 'green', icon: <ApiOutlined /> },
  carbone: { label: 'Carbone', color: 'blue', icon: <FileTextOutlined /> },
  browser: { label: '浏览器', color: 'purple', icon: <ChromeOutlined /> },
  script: { label: '脚本', color: 'orange', icon: <CodeOutlined /> },
};

interface ActivityStep {
  id: string;
  name: string;
  type: 'api' | 'carbone' | 'browser' | 'script';
  timeout: string;
  retryPolicy?: { maxRetries: number };
  config: Record<string, any>;
}

interface ActivityFormData {
  name: string;
  fn: string;
  description: string;  // AI guidance prompt for code generation
  taskQueue: string;
  startToCloseTimeout: string;
  heartbeatTimeout?: string;
  scheduleToStartTimeout: string;
  scheduleToCloseTimeout: string;
  retryPolicy?: { maxRetries: number; backoffMs?: number };
  idempotencyKey?: string;
  steps: ActivityStep[];
}

const generatePythonCode = (form: ActivityFormData): string => {
  const lines: string[] = [];
  lines.push('# Generated by Temporal Activity Generator');
  lines.push('# See: services/portal/src/skills/temporal-developer/SKILL.md');
  lines.push('');
  lines.push('from datetime import timedelta');
  lines.push('from temporalio import activity');
  lines.push('from temporalio.exceptions import ApplicationError');
  lines.push('from typing import Optional, Dict, Any');
  lines.push('');
  lines.push('@activity.defn');
  lines.push(`def ${form.fn}(input_data: Dict[str, Any]) -> Dict[str, Any]:`);

  if (form.description) {
    lines.push(`    """`);
    lines.push(`    Activity: ${form.name}`);
    lines.push(`    `);
    lines.push(`    Description: ${form.description}`);
    lines.push(`    `);
    lines.push(`    Configuration:`);
    lines.push(`      - Task Queue: ${form.taskQueue}`);
    lines.push(`      - StartToClose Timeout: ${form.startToCloseTimeout}`);
    if (form.heartbeatTimeout) {
      lines.push(`      - Heartbeat Timeout: ${form.heartbeatTimeout}`);
    }
    if (form.retryPolicy) {
      lines.push(`      - Retry Policy: maxRetries=${form.retryPolicy.maxRetries}`);
    }
    if (form.idempotencyKey) {
      lines.push(`      - Idempotency Key: ${form.idempotencyKey}`);
    }
    lines.push(`    """.replace('"', '\\"')`);
  } else {
    lines.push(`    """Activity: ${form.name}""".replace('"', '\\"')`);
  }

  lines.push('    activity.logger.info("Activity started")');

  if (form.heartbeatTimeout) {
    lines.push(`    activity.logger.info(f"Heartbeat timeout: ${form.heartbeatTimeout}")`);
  }

  lines.push('    activity.heartbeat("initializing")');

  if (form.steps.length > 0) {
    lines.push('    # Execute activity steps');
    form.steps.forEach((step, idx) => {
      lines.push('');
      lines.push(`    # === Step ${idx + 1}: ${step.name} ===`);
      lines.push(`    activity.heartbeat("executing_step_${idx + 1}")`);
      lines.push('    info = activity.info()');
      lines.push('    if info.is_cancelled:');
      lines.push('        activity.logger.warning("Activity cancelled")');
      lines.push('        return {"status": "cancelled", "step": ' + (idx + 1) + '}');

      if (step.type === 'api') {
        lines.push(`    try:`);
        lines.push(`        result_${idx + 1} = yield execute_api_request(`);
        lines.push(`            endpoint="${step.config.endpoint || 'https://api.example.com'}",`);
        lines.push(`            method="${step.config.method || 'GET'}"`);
        if (form.idempotencyKey) {
          lines.push(`            idempotency_key="${form.idempotencyKey}"`);
        }
        lines.push(`        )`);
        lines.push(`        activity.logger.info(f"Step ${idx + 1} completed: {result_${idx + 1}}")`);
        lines.push(`    except Exception as e:`);
        lines.push(`        activity.logger.error(f"Step ${idx + 1} failed: {e}")`);
        lines.push(`        raise ApplicationError(f"Step ${idx + 1} failed: {e}", non_retryable=False)`);
      } else if (step.type === 'script') {
        lines.push(`    result_${idx + 1} = yield execute_script(`);
        lines.push('        """');
        lines.push((step.config.script || '# your code here').split('\n').map(l => `        ${l}`).join('\n'));
        lines.push('        """');
        lines.push('    )');
      } else if (step.type === 'carbone') {
        lines.push(`    result_${idx + 1} = yield render_with_carbone(`);
        lines.push(`        template_id="${step.config.templateId || '{{template_id}}'}",`);
        lines.push(`        data=input_data`);
        lines.push('    )');
      } else if (step.type === 'browser') {
        lines.push(`    result_${idx + 1} = yield execute_browser_action(`);
        lines.push(`        action="${step.config.action || 'click'}",`);
        lines.push(`        selector="${step.config.selector || '{{selector}}'}"`);
        lines.push('    )');
      }
    });
  }

  lines.push('');
  lines.push('    activity.heartbeat("completed")');
  lines.push('    return {');
  lines.push('        "status": "success",');
  lines.push(`        "activity": "${form.name}",`);
  if (form.steps.length > 0) {
    lines.push('        "results": {');
    form.steps.forEach((step, idx) => {
      lines.push(`            "${step.name}": result_${idx + 1}${idx < form.steps.length - 1 ? ',' : ''}`);
    });
    lines.push('        }');
  }
  lines.push('    }');

  return lines.join('\n');
};

const ActivityPage: React.FC = () => {
  const { t } = useTranslation(['common', 'admin']);
  const queryClient = useQueryClient();
  const [form] = Form.useForm();
  const [searchText, setSearchText] = useState('');
  const [editModalVisible, setEditModalVisible] = useState(false);
  const [detailModalVisible, setDetailModalVisible] = useState(false);
  const [validateModalVisible, setValidateModalVisible] = useState(false);
  const [simulationModalVisible, setSimulationModalVisible] = useState(false);
  const [codePreviewVisible, setCodePreviewVisible] = useState(false);
  const [editingActivity, setEditingActivity] = useState<ActivityDTO | null>(null);
  const [selectedActivity, setSelectedActivity] = useState<ActivityDTO | null>(null);
  const [validationResult, setValidationResult] = useState<ActivityValidationResult | null>(null);
  const [simulationResult, setSimulationResult] = useState<any>(null);
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const [isGeneratingCode, setIsGeneratingCode] = useState(false);
  const [realValidateModalVisible, setRealValidateModalVisible] = useState(false);
  const [realValidateResult, setRealValidateResult] = useState<any>(null);
  const [isRealValidating, setIsRealValidating] = useState(false);
  const [realValidateLogs, setRealValidateLogs] = useState<string[]>([]);
  const [realValidateError, setRealValidateError] = useState<string | null>(null);
  const [cachedCode, setCachedCode] = useState<string | null>(null);
  const [activityForm, setActivityForm] = useState<ActivityFormData>({
    name: '',
    fn: '',
    description: '',
    taskQueue: 'SKILL_TASK_QUEUE',
    startToCloseTimeout: '60s',
    heartbeatTimeout: undefined,
    scheduleToStartTimeout: '30s',
    scheduleToCloseTimeout: '120s',
    retryPolicy: undefined,
    idempotencyKey: undefined,
    steps: [],
  });

  const activitiesQuery = useQuery(['activities', searchText], () => activityApi.list());

  const createMutation = useMutation(activityApi.create, {
    onSuccess: () => {
      message.success(t('common:success'));
      queryClient.invalidateQueries(['activities']);
      setEditModalVisible(false);
      form.resetFields();
      resetForm();
    },
    onError: (err: any) => message.error(err?.message || t('common:error')),
  });

  const updateMutation = useMutation(
    ({ id, data }: { id: string; data: Partial<CreateActivityDto> }) => activityApi.update(id, data),
    {
      onSuccess: () => {
        message.success(t('common:success'));
        queryClient.invalidateQueries(['activities']);
        setEditModalVisible(false);
      },
      onError: (err: any) => message.error(err?.message || t('common:error')),
    }
  );

  const deleteMutation = useMutation(activityApi.delete, {
    onSuccess: () => {
      message.success(t('common:success'));
      queryClient.invalidateQueries(['activities']);
    },
    onError: (err: any) => message.error(err?.message || t('common:error')),
  });

  const validateMutation = useMutation(activityApi.validate, {
    onSuccess: (result) => {
      setValidationResult(result);
      message.success('验证完成');
    },
    onError: (err: any) => message.error(err?.message || '验证失败'),
  });

  const generateCodeMutation = useMutation(activityApi.generateCode, {
    onSuccess: (result) => {
      setIsGeneratingCode(false);
      if (result.success && result.code) {
        setGeneratedCode(result.code);
        setRealValidateError(null); // Clear error after successful regeneration
        setCodePreviewVisible(true);
      } else {
        message.error(result.error || '代码生成失败');
      }
    },
    onError: (err: any) => {
      setIsGeneratingCode(false);
      message.error(err?.message || '代码生成失败');
    },
  });

  // 真实验证：使用 SSE 流式执行
  const handleRealValidate = async () => {
    setIsRealValidating(true);
    setRealValidateLogs([]);
    setRealValidateError(null);
    setRealValidateResult(null);

    try {
      // 先拉取最新的代码（从服务器获取最新的 activity 配置）
      let code = cachedCode || generatedCode;
      setRealValidateLogs(prev => [...prev, '正在获取最新代码...']);

      // 如果有正在编辑的 activity，从服务器获取最新的 generatedCode
      if (editingActivity) {
        try {
          const latestActivity = await activityApi.getById(editingActivity.id);
          if (latestActivity.config?.generatedCode) {
            code = latestActivity.config.generatedCode;
            setCachedCode(code);
            setGeneratedCode(code);
            setRealValidateLogs(prev => [...prev, '已从服务器获取最新代码']);
          }
        } catch (e) {
          setRealValidateLogs(prev => [...prev, '获取最新代码失败，使用本地代码']);
        }
      }

      // 如果还是没有代码，则生成新代码
      if (!code) {
        setRealValidateLogs(prev => [...prev, '正在生成代码...']);
        const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';
        const genResult = await activityApi.generateCode({
          name: activityForm.name,
          fn: activityForm.fn,
          timeout: activityForm.startToCloseTimeout,
          handler: handler as any,
          retryPolicy: activityForm.retryPolicy,
          config: {
            description: activityForm.description,
            taskQueue: activityForm.taskQueue,
            steps: activityForm.steps,
            heartbeatTimeout: activityForm.heartbeatTimeout,
            idempotencyKey: activityForm.idempotencyKey,
          },
        });
        if (!genResult.success || !genResult.code) {
          throw new Error(genResult.error || '代码生成失败');
        }
        code = genResult.code;
        setGeneratedCode(code);
        setRealValidateLogs(prev => [...prev, '代码生成完成']);
      }

      // Execute with SSE streaming
      setRealValidateLogs(prev => [...prev, '开始执行代码...']);
      await activityApi.executeCodeStream(
        { code, fn: activityForm.fn, taskQueue: activityForm.taskQueue, input: {} },
        (event) => {
          if (event.type === 'log' && event.message) {
            setRealValidateLogs(prev => [...prev, event.message!]);
          } else if (event.type === 'done') {
            setRealValidateResult(event.result);
            setIsRealValidating(false);
          } else if (event.type === 'error') {
            setRealValidateError(event.message || '执行失败');
            setIsRealValidating(false);
          }
        }
      );
    } catch (err: any) {
      setRealValidateError(err?.message || '真实验证失败');
      setIsRealValidating(false);
    }
  };

  // 重新生成代码（带错误信息）
  const handleRegenerateWithError = (errorMsg: string) => {
    setRealValidateError(errorMsg); // Keep error visible
    setIsGeneratingCode(true);
    const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';
    generateCodeMutation.mutate({
      name: activityForm.name,
      fn: activityForm.fn,
      timeout: activityForm.startToCloseTimeout,
      handler: handler as any,
      retryPolicy: activityForm.retryPolicy,
      config: {
        description: activityForm.description,
        taskQueue: activityForm.taskQueue,
        steps: activityForm.steps,
        heartbeatTimeout: activityForm.heartbeatTimeout,
        idempotencyKey: activityForm.idempotencyKey,
      },
    });
  };

  const handleGenerateCode = () => {
    const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';
    setIsGeneratingCode(true);
    generateCodeMutation.mutate({
      name: activityForm.name,
      fn: activityForm.fn,
      timeout: activityForm.startToCloseTimeout,
      handler: handler as any,
      retryPolicy: activityForm.retryPolicy,
      config: {
        description: activityForm.description,
        taskQueue: activityForm.taskQueue,
        steps: activityForm.steps,
        heartbeatTimeout: activityForm.heartbeatTimeout,
        idempotencyKey: activityForm.idempotencyKey,
      },
    });
  };

  const resetForm = () => {
    setActivityForm({
      name: '', fn: '', description: '', taskQueue: 'SKILL_TASK_QUEUE',
      startToCloseTimeout: '60s', heartbeatTimeout: undefined,
      scheduleToStartTimeout: '30s', scheduleToCloseTimeout: '120s',
      retryPolicy: undefined, idempotencyKey: undefined,
      steps: [],
    });
    setGeneratedCode('');
  };

  const handleCreate = () => {
    setEditingActivity(null);
    resetForm();
    setEditModalVisible(true);
  };

  const handleEdit = (activity: ActivityDTO) => {
    setEditingActivity(activity);
    const steps: ActivityStep[] = activity.config?.steps || [];
    setActivityForm({
      name: activity.name,
      fn: activity.fn,
      description: activity.config?.description || '',
      taskQueue: activity.config?.taskQueue || 'SKILL_TASK_QUEUE',
      startToCloseTimeout: '60s',
      heartbeatTimeout: activity.config?.heartbeatTimeout,
      scheduleToStartTimeout: '30s',
      scheduleToCloseTimeout: '120s',
      retryPolicy: activity.retryPolicy,
      idempotencyKey: activity.config?.idempotencyKey,
      steps,
    });
    // Load saved generated code if exists
    if (activity.config?.generatedCode) {
      setGeneratedCode(activity.config.generatedCode);
      setCachedCode(activity.config.generatedCode); // Also set cached code
    } else {
      setGeneratedCode('');
      setCachedCode(null);
    }
    setEditModalVisible(true);
  };

  const handleViewDetail = (activity: ActivityDTO) => {
    setSelectedActivity(activity);
    setDetailModalVisible(true);
  };

  const handleValidate = () => {
    setValidationResult(null);
    setValidateModalVisible(true);
    const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';
    validateMutation.mutate({
      name: activityForm.name,
      fn: activityForm.fn,
      timeout: activityForm.startToCloseTimeout,
      handler: handler as any,
      retryPolicy: activityForm.retryPolicy,
      config: {
        taskQueue: activityForm.taskQueue,
        steps: activityForm.steps,
        heartbeatTimeout: activityForm.heartbeatTimeout,
        idempotencyKey: activityForm.idempotencyKey,
      },
    } as any);
  };

  const handleSave = () => {
    const handler = activityForm.steps.length > 0 ? activityForm.steps[0].type : 'api';
    // Use cached code if available, otherwise use state
    const codeToSave = cachedCode || generatedCode;
    const data: CreateActivityDto = {
      name: activityForm.name,
      fn: activityForm.fn,
      timeout: activityForm.startToCloseTimeout,
      handler: handler as any,
      retryPolicy: activityForm.retryPolicy,
      config: {
        description: activityForm.description,
        taskQueue: activityForm.taskQueue,
        steps: activityForm.steps,
        heartbeatTimeout: activityForm.heartbeatTimeout,
        idempotencyKey: activityForm.idempotencyKey,
        generatedCode: codeToSave || undefined,
      },
    };

    if (editingActivity) {
      updateMutation.mutate({ id: editingActivity.id, data });
    } else {
      createMutation.mutate(data);
    }
  };

  const handleDelete = (id: string) => {
    Modal.confirm({
      title: t('common:confirmDelete'),
      content: '删除后无法恢复，是否继续？',
      onOk: () => deleteMutation.mutate(id),
    });
  };

  const handleSimulate = (type: 'success' | 'failure' | 'timeout' | 'heartbeat') => {
    setSimulationResult({
      type,
      timestamp: new Date().toISOString(),
      message: type === 'success' ? 'Activity 执行成功' :
        type === 'failure' ? 'Activity 执行失败' :
        type === 'timeout' ? 'Activity 执行超时' : '心跳已发送',
      heartbeatEvents: type === 'heartbeat' ? [
        { time: '00:00:01', stage: 'initializing' },
        { time: '00:00:05', stage: 'executing_step_1' },
        { time: '00:00:10', stage: 'completed' },
      ] : [],
    });
  };

  const updateActivityForm = (field: string, value: any) => {
    setActivityForm((prev) => ({ ...prev, [field]: value }));
  };

  const addStep = () => {
    const newStep: ActivityStep = {
      id: `step_${Date.now()}`,
      name: `步骤 ${activityForm.steps.length + 1}`,
      type: 'api',
      timeout: '30s',
      config: { endpoint: '', method: 'GET' },
    };
    setActivityForm((prev) => ({ ...prev, steps: [...prev.steps, newStep] }));
  };

  const removeStep = (id: string) => {
    setActivityForm((prev) => ({ ...prev, steps: prev.steps.filter(s => s.id !== id) }));
  };

  const updateStep = (id: string, field: string, value: any) => {
    setActivityForm((prev) => ({
      ...prev,
      steps: prev.steps.map(s => s.id === id ? { ...s, [field]: value } : s)
    }));
  };

  const copyCode = () => {
    navigator.clipboard.writeText(generatedCode);
    message.success('代码已复制');
  };

  const columns: ColumnsType<ActivityDTO> = [
    { title: '名称', dataIndex: 'name', key: 'name', width: 180, render: (name, r) => <a onClick={() => handleViewDetail(r)}><Text strong>{name}</Text></a> },
    { title: '函数名', dataIndex: 'fn', key: 'fn', width: 150, render: fn => <Tag color="cyan">{fn}</Tag> },
    { title: '处理器', key: 'handler', width: 80, render: (_, r) => <Tag color={HANDLER_CONFIG[r.handler]?.color}>{HANDLER_CONFIG[r.handler]?.label}</Tag> },
    { title: '步骤', key: 'steps', width: 60, render: (_, r) => <Tag>{r.config?.steps?.length || 0}</Tag> },
    { title: '超时', dataIndex: 'timeout', key: 'timeout', width: 70 },
    { title: '心跳', key: 'heartbeat', width: 60, render: (_, r) => r.config?.heartbeatTimeout ? <Tag color="blue">{r.config.heartbeatTimeout}</Tag> : <Tag>-</Tag> },
    { title: '重试', key: 'retryPolicy', width: 60, render: (_, r) => r.retryPolicy ? <Tag color="orange">有</Tag> : <Tag>无</Tag> },
    { title: '状态', key: 'status', width: 70, render: (_, r) => <Tag color={r.isActive ? 'green' : 'default'}>{r.isActive ? '启用' : '禁用'}</Tag> },
    { title: t('common:actions'), key: 'actions', width: 100, render: (_, r) => (
      <Space size="small">
        <Button type="link" size="small" icon={<EditOutlined />} onClick={() => handleEdit(r)} />
        <Popconfirm title="确认删除" onConfirm={() => handleDelete(r.id)} okText="删除" okButtonProps={{ danger: true }}>
          <Button type="link" size="small" icon={<DeleteOutlined />} danger />
        </Popconfirm>
      </Space>
    )},
  ];

  const filteredActivities = (activitiesQuery.data || []).filter(a =>
    a.name.toLowerCase().includes(searchText.toLowerCase()) || a.fn.toLowerCase().includes(searchText.toLowerCase())
  );

  const stats = {
    total: activitiesQuery.data?.length || 0,
    api: activitiesQuery.data?.filter(a => a.handler === 'api').length || 0,
    script: activitiesQuery.data?.filter(a => a.handler === 'script').length || 0,
    active: activitiesQuery.data?.filter(a => a.isActive).length || 0,
  };

  return (
    <div>
      <Row gutter={16} style={{ marginBottom: 24 }}>
        <Col span={6}><Card><Statistic title="总数" value={stats.total} prefix={<ThunderboltOutlined />} /></Card></Col>
        <Col span={6}><Card><Statistic title="API" value={stats.api} valueStyle={{ color: '#52c41a' }} /></Card></Col>
        <Col span={6}><Card><Statistic title="脚本" value={stats.script} valueStyle={{ color: '#fa8c16' }} /></Card></Col>
        <Col span={6}><Card><Statistic title="已启用" value={stats.active} valueStyle={{ color: '#1890ff' }} /></Card></Col>
      </Row>

      <Card style={{ marginBottom: 16 }}>
        <Space style={{ width: '100%', justifyContent: 'space-between' }}>
          <Input placeholder="搜索..." prefix={<SearchOutlined />} value={searchText} onChange={e => setSearchText(e.target.value)} style={{ width: 200 }} allowClear />
          <Space>
            <Button icon={<PlusOutlined />} type="primary" onClick={handleCreate}>创建</Button>
            <Button icon={<ReloadOutlined />} onClick={() => activitiesQuery.refetch()} />
          </Space>
        </Space>
      </Card>

      <Card>
        <Table columns={columns} dataSource={filteredActivities} rowKey="id" loading={activitiesQuery.isLoading} pagination={{ showSizeChanger: true, showTotal: total => `共 ${total} 条` }} />
      </Card>

      {/* Edit Modal */}
      <Modal
        title={editingActivity ? '编辑 Activity' : '创建 Activity'}
        open={editModalVisible}
        onCancel={() => setEditModalVisible(false)}
        footer={null}
        width={1000}
        destroyOnClose
      >
        <Form layout="vertical">
          {/* Basic Info */}
          <Card size="small" style={{ marginBottom: 16 }}>
            <Row gutter={16}>
              <Col span={12}>
                <Form.Item label="名称" required>
                  <Input value={activityForm.name} onChange={e => updateActivityForm('name', e.target.value)} placeholder="天气查询" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item label="函数名" required>
                  <Input value={activityForm.fn} onChange={e => updateActivityForm('fn', e.target.value)} placeholder="weatherQuery" />
                </Form.Item>
              </Col>
            </Row>
            <Row gutter={16}>
              <Col span={24}>
                <Form.Item label="AI 指导说明（描述这个 Activity 的功能，让 AI 生成更准确的代码）">
                  <TextArea value={activityForm.description} onChange={e => updateActivityForm('description', e.target.value)} placeholder="例如：这是一个天气查询 Activity，查询上海和北京两地的天气并返回结果..." rows={2} />
                </Form.Item>
              </Col>
            </Row>
            <Row gutter={16}>
              <Col span={12}>
                <Form.Item label="Task Queue">
                  <Input value={activityForm.taskQueue} onChange={e => updateActivityForm('taskQueue', e.target.value)} />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item label="StartToClose 超时">
                  <Select value={activityForm.startToCloseTimeout} onChange={v => updateActivityForm('startToCloseTimeout', v)}>
                    <Option value="30s">30s</Option>
                    <Option value="60s">60s</Option>
                    <Option value="120s">120s</Option>
                    <Option value="300s">300s</Option>
                  </Select>
                </Form.Item>
              </Col>
            </Row>
          </Card>

          {/* Optional Settings */}
          <Card size="small" style={{ marginBottom: 16 }}>
            <Title level={5} style={{ marginBottom: 12 }}><SettingOutlined /> 可选配置（指导 AI 生成代码）</Title>
            <Row gutter={16}>
              <Col span={8}>
                <Form.Item label="心跳超时">
                  <Space>
                    <Switch checked={!!activityForm.heartbeatTimeout} onChange={checked => updateActivityForm('heartbeatTimeout', checked ? '30s' : undefined)} />
                    {activityForm.heartbeatTimeout && (
                      <Select value={activityForm.heartbeatTimeout} onChange={v => updateActivityForm('heartbeatTimeout', v)} style={{ width: 100 }}>
                        <Option value="5s">5s</Option>
                        <Option value="10s">10s</Option>
                        <Option value="30s">30s</Option>
                        <Option value="60s">60s</Option>
                      </Select>
                    )}
                  </Space>
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item label="ScheduleToStart">
                  <Select value={activityForm.scheduleToStartTimeout} onChange={v => updateActivityForm('scheduleToStartTimeout', v)}>
                    <Option value="10s">10s</Option>
                    <Option value="30s">30s</Option>
                    <Option value="60s">60s</Option>
                  </Select>
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item label="ScheduleToClose">
                  <Select value={activityForm.scheduleToCloseTimeout} onChange={v => updateActivityForm('scheduleToCloseTimeout', v)}>
                    <Option value="60s">60s</Option>
                    <Option value="120s">120s</Option>
                    <Option value="300s">300s</Option>
                  </Select>
                </Form.Item>
              </Col>
            </Row>
            <Row gutter={16}>
              <Col span={12}>
                <Form.Item label="幂等键策略（指导 AI 生成）">
                  <Switch checked={!!activityForm.idempotencyKey} onChange={checked => updateActivityForm('idempotencyKey', checked ? "{{workflowId}}-{{activityName}}-{{inputHash}}" : undefined)} />
                  {activityForm.idempotencyKey && (
                    <Input value={activityForm.idempotencyKey} onChange={e => updateActivityForm('idempotencyKey', e.target.value || undefined)} placeholder="{{workflowId}}-{{activityName}}-{{inputHash}}" style={{ marginLeft: 16, width: 200 }} />
                  )}
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item label="重试策略">
                  <Switch checked={!!activityForm.retryPolicy} onChange={checked => updateActivityForm('retryPolicy', checked ? { maxRetries: 3, backoffMs: 1000 } : undefined)} />
                  {activityForm.retryPolicy && (
                    <Space style={{ marginLeft: 16 }}>
                      <InputNumber value={activityForm.retryPolicy.maxRetries} onChange={v => updateActivityForm('retryPolicy', { ...activityForm.retryPolicy!, maxRetries: v || 0 })} min={1} max={10} size="small" />
                      <Text type="secondary">次</Text>
                    </Space>
                  )}
                </Form.Item>
              </Col>
            </Row>
          </Card>

          {/* Steps */}
          <Card size="small" style={{ marginBottom: 16 }}>
            <Title level={5} style={{ marginBottom: 12 }}><OrderedListOutlined /> 步骤列表</Title>
            <Button type="dashed" icon={<PlusOutlined />} onClick={addStep} block style={{ marginBottom: 12 }}>
              添加步骤
            </Button>
            {activityForm.steps.length === 0 ? (
              <Text type="secondary">添加步骤来定义 Activity 的执行流程</Text>
            ) : (
              activityForm.steps.map((step, idx) => (
                <Card key={step.id} size="small" style={{ marginBottom: 8, border: '1px solid #d9d9d9' }}>
                  <Row gutter={12} align="middle">
                    <Col><Badge count={idx + 1} style={{ backgroundColor: '#1890ff' }} /></Col>
                    <Col flex={1}>
                      <Input value={step.name} onChange={e => updateStep(step.id, 'name', e.target.value)} placeholder="步骤名称" style={{ marginBottom: 8 }} />
                      <Space>
                        <Select value={step.type} onChange={v => updateStep(step.id, 'type', v)} style={{ width: 100 }}>
                          <Option value="api">API</Option>
                          <Option value="script">脚本</Option>
                          <Option value="carbone">Carbone</Option>
                          <Option value="browser">浏览器</Option>
                        </Select>
                        <Input value={step.timeout} onChange={e => updateStep(step.id, 'timeout', e.target.value)} placeholder="超时" style={{ width: 70 }} />
                      </Space>
                    </Col>
                    <Col>
                      <Button type="text" danger icon={<DeleteOutlined />} onClick={() => removeStep(step.id)} />
                    </Col>
                  </Row>
                  {step.type === 'api' && (
                    <div style={{ marginTop: 8, padding: 8, background: '#f6ffed', borderRadius: 4 }}>
                      <Input value={step.config.endpoint || ''} onChange={e => updateStep(step.id, 'config', { ...step.config, endpoint: e.target.value })} placeholder="https://uapis.cn/api/v1/misc/weather?city=北京" prefix={<ApiOutlined />} />
                    </div>
                  )}
                  {step.type === 'script' && (
                    <div style={{ marginTop: 8, padding: 8, background: '#fff7e6', borderRadius: 4 }}>
                      <TextArea value={step.config.script || ''} onChange={e => updateStep(step.id, 'config', { ...step.config, script: e.target.value })} placeholder="// 代码..." rows={2} style={{ fontFamily: 'monospace' }} />
                    </div>
                  )}
                </Card>
              ))
            )}
          </Card>

          {/* Actions */}
          <Space style={{ width: '100%', justifyContent: 'flex-end' }}>
            <Button icon={<RobotOutlined />} onClick={handleGenerateCode} loading={generateCodeMutation.isPending || isGeneratingCode}>AI 生成代码</Button>
            <Button icon={<EyeOutlined />} onClick={() => setCodePreviewVisible(true)} disabled={!generatedCode && !generateCodeMutation.isSuccess}>查看代码</Button>
            <Button icon={<PlayCircleOutlined />} onClick={handleValidate}>验证配置</Button>
            <Button icon={<ThunderboltOutlined />} onClick={() => setRealValidateModalVisible(true)} disabled={!cachedCode && !generatedCode && !generateCodeMutation.isSuccess}>真实验证</Button>
            <Button icon={<ExperimentOutlined />} onClick={() => setSimulationModalVisible(true)}>模拟</Button>
            <Button onClick={() => setEditModalVisible(false)}>取消</Button>
            <Button type="primary" icon={<SaveOutlined />} loading={createMutation.isLoading || updateMutation.isLoading} onClick={handleSave}>保存</Button>
          </Space>
        </Form>
      </Modal>

      {/* Code Preview Modal */}
      <Modal
        title={<Space><RobotOutlined /> AI 生成的 Python 代码</Space>}
        open={codePreviewVisible}
        onCancel={() => { setCodePreviewVisible(false); setIsGeneratingCode(false); }}
        footer={[
          <Button key="copy" icon={<CopyOutlined />} onClick={copyCode}>复制代码</Button>,
          <Button key="cache" icon={<SaveOutlined />} onClick={() => {
            if (generatedCode) {
              // Store in state so handleSave can include it
              setCachedCode(generatedCode);
              message.success('代码已缓存，保存时将一并存储');
            } else {
              message.warning('请先生成代码');
            }
          }}>缓存代码</Button>,
          <Button key="close" onClick={() => { setCodePreviewVisible(false); setIsGeneratingCode(false); }}>关闭</Button>
        ]}
        width={800}
      >
        <Paragraph type="secondary" style={{ marginBottom: 16 }}>
          以下代码由 AI 根据您的配置自动生成，可用于参考或复制到 Temporal Worker 中使用。点击"缓存代码"可保存到配置中。
        </Paragraph>
        <Card bodyStyle={{ padding: 0 }} style={{ background: '#1e1e1e', borderRadius: 8 }}>
          {isGeneratingCode || generateCodeMutation.isPending ? (
            <div style={{ padding: 40, textAlign: 'center', color: '#d4d4d4' }}>
              <LoadingOutlined style={{ fontSize: 24 }} /><br /><br />
              正在生成代码，请稍候...
            </div>
          ) : (
            <pre style={{ color: '#d4d4d4', padding: 16, margin: 0, fontFamily: 'Monaco, Menlo, "Ubuntu Mono", monospace', fontSize: 12, lineHeight: 1.5, overflow: 'auto', maxHeight: 500 }}>
              {generatedCode || generatePythonCode(activityForm)}
            </pre>
          )}
        </Card>
      </Modal>

      {/* Simulation Modal */}
      <Modal title="模拟测试" open={simulationModalVisible} onCancel={() => setSimulationModalVisible(false)} footer={null} width={500}>
        <Space direction="vertical" style={{ width: '100%' }}>
          <Text>选择场景：</Text>
          <Space wrap>
            <Button icon={<CheckCircleOutlined />} onClick={() => handleSimulate('success')} type="primary">成功</Button>
            <Button icon={<WarningOutlined />} danger onClick={() => handleSimulate('failure')}>失败</Button>
            <Button icon={<ClockCircleOutlined />} onClick={() => handleSimulate('timeout')}>超时</Button>
            <Button icon={<HeartOutlined />} onClick={() => handleSimulate('heartbeat')}>心跳</Button>
          </Space>
          {simulationResult && (
            <Card size="small" style={{ marginTop: 16, background: '#f5f5f5' }}>
              <p><strong>类型：</strong>{simulationResult.type}</p>
              <p><strong>消息：</strong>{simulationResult.message}</p>
              {simulationResult.heartbeatEvents?.length > 0 && (
                <>
                  <p><strong>心跳事件：</strong></p>
                  <ul>{simulationResult.heartbeatEvents.map((e: any, i: number) => <li key={i}>{e.time} - {e.stage}</li>)}</ul>
                </>
              )}
            </Card>
          )}
        </Space>
      </Modal>

      {/* Detail Modal */}
      <Modal title="详情" open={detailModalVisible} onCancel={() => setDetailModalVisible(false)} footer={null} width={700}>
        {selectedActivity && (
          <Collapse defaultActiveKey={['basic', 'monitoring', 'steps']}>
            <Panel header={<Text><ThunderboltOutlined /> 基本信息</Text>} key="basic">
              <Row gutter={16}>
                <Col span={12}><Text><strong>名称:</strong> {selectedActivity.name}</Text></Col>
                <Col span={12}><Text><strong>函数名:</strong> <Tag color="cyan">{selectedActivity.fn}</Tag></Text></Col>
                <Col span={24}><Text><strong>说明:</strong> {selectedActivity.config?.description || '无'}</Text></Col>
                <Col span={12}><Text><strong>超时:</strong> {selectedActivity.timeout}</Text></Col>
                <Col span={12}><Text><strong>心跳:</strong> {selectedActivity.config?.heartbeatTimeout || '未配置'}</Text></Col>
                <Col span={12}><Text><strong>幂等键:</strong> {selectedActivity.config?.idempotencyKey || '未配置'}</Text></Col>
              </Row>
            </Panel>
            <Panel header={<Text><OrderedListOutlined /> 步骤详情 ({selectedActivity.config?.steps?.length || 0})</Text>} key="steps">
              {selectedActivity.config?.steps?.map((step: any, idx: number) => (
                <Card key={idx} size="small" style={{ marginBottom: 8 }}>
                  <Text strong>步骤 {idx + 1}: {step.name}</Text>
                  <br />
                  <Text type="secondary">类型: {step.type} | 超时: {step.timeout}</Text>
                  {step.type === 'api' && <div><Text type="secondary">端点: {step.config?.endpoint}</Text></div>}
                </Card>
              ))}
            </Panel>
            <Panel header={<Text><LineChartOutlined /> 监控</Text>} key="monitoring">
              <Row gutter={16}>
                <Col span={8}><Card size="small"><Statistic title="平均耗时" value="1.2s" /></Card></Col>
                <Col span={8}><Card size="small"><Statistic title="失败率" value="0.5%" valueStyle={{ color: '#52c41a' }} /></Card></Col>
                <Col span={8}><Card size="small"><Statistic title="Backlog" value="12" /></Card></Col>
              </Row>
            </Panel>
          </Collapse>
        )}
      </Modal>

      {/* Validation Modal */}
      <Modal title="验证结果" open={validateModalVisible} onCancel={() => setValidateModalVisible(false)} footer={[<Button onClick={() => setValidateModalVisible(false)}>关闭</Button>]}>
        {validateMutation.isPending ? (
          <div style={{ padding: 40, textAlign: 'center' }}>
            <LoadingOutlined style={{ fontSize: 24 }} /><br /><br />
            正在验证配置，请稍候...
          </div>
        ) : validationResult ? (
          <Space direction="vertical" style={{ width: '100%' }}>
            <Alert type={validationResult.isValid ? 'success' : 'error'} message={validationResult.isValid ? '验证通过' : '验证失败'} showIcon />
            <Text>评分: {validationResult.score}/100</Text>
            <Text type="secondary" style={{ fontSize: 12 }}>
              说明：验证仅检查配置结构有效性，不执行生成的 Python 代码。生成的代码可直接复制到 Temporal Worker 使用。
            </Text>
            {validationResult.errors?.length > 0 && <Alert type="error" message="错误" description={<ul>{validationResult.errors.map((e, i) => <li key={i}>{e}</li>)}</ul>} />}
            {validationResult.warnings?.length > 0 && <Alert type="warning" message="警告" description={<ul>{validationResult.warnings.map((w, i) => <li key={i}>{w}</li>)}</ul>} />}
            {validationResult.suggestions?.length > 0 && <Alert type="info" message="建议" description={<ul>{validationResult.suggestions.map((s, i) => <li key={i}>{s}</li>)}</ul>} />}
          </Space>
        ) : <Alert type="info" message="点击验证按钮开始验证" />}
      </Modal>

      {/* Real Validation Modal - SSE 流式执行真实代码 */}
      <Modal
        title={<Space><ThunderboltOutlined /> 真实验证（执行代码）</Space>}
        open={realValidateModalVisible}
        onCancel={() => { setRealValidateModalVisible(false); setIsRealValidating(false); setRealValidateLogs([]); setRealValidateError(null); }}
        footer={[<Button onClick={() => setRealValidateModalVisible(false)}>关闭</Button>]}
        width={800}
      >
        <Space direction="vertical" style={{ width: '100%' }}>
          {realValidateError && (
            <Alert
              type="error"
              message="执行失败"
              description={
                <div>
                  <pre style={{ margin: '8px 0', fontSize: 12, whiteSpace: 'pre-wrap' }}>{realValidateError}</pre>
                  <Button
                    type="primary"
                    icon={<RobotOutlined />}
                    onClick={() => handleRegenerateWithError(realValidateError)}
                    loading={isGeneratingCode}
                    style={{ marginTop: 8 }}
                  >
                    重新生成代码
                  </Button>
                </div>
              }
              showIcon
            />
          )}

          {realValidateResult && !realValidateError && (
            <Alert
              type={realValidateResult.success ? 'success' : 'error'}
              message={realValidateResult.success ? '执行成功' : '执行失败'}
              showIcon
            />
          )}

          <div>
            <Text strong>执行日志：</Text>
            <div style={{ background: '#1e1e1e', color: '#d4d4d4', padding: 12, borderRadius: 4, maxHeight: 300, overflow: 'auto', marginTop: 8 }}>
              <pre style={{ margin: 0, fontSize: 11 }}>
                {realValidateLogs.map((log, i) => (
                  <div key={i}>{log}</div>
                ))}
                {isRealValidating && <span style={{ color: '#1890ff' }}>▋</span>}
              </pre>
            </div>
          </div>

          {realValidateResult && !realValidateError && realValidateResult.result && (
            <Card size="small" style={{ background: '#f5f5f5' }}>
              <Text strong>执行结果：</Text>
              <pre style={{ margin: '8px 0', fontSize: 12, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
                {typeof realValidateResult.result === 'string' ? realValidateResult.result : JSON.stringify(realValidateResult.result, null, 2)}
              </pre>
            </Card>
          )}

          {!isRealValidating && !realValidateResult && !realValidateError && (
            <Alert type="info" message="真实验证将执行以下步骤：" description={
              <ul style={{ margin: '8px 0' }}>
                <li>1. 使用已保存的代码（如有）</li>
                <li>2. 或重新生成最新 AI 代码</li>
                <li>3. 将代码发送到 Temporal Worker 执行</li>
                <li>4. 实时返回执行日志</li>
              </ul>
            } />
          )}

          {!isRealValidating && (
            <Button
              type="primary"
              icon={<ThunderboltOutlined />}
              onClick={handleRealValidate}
              loading={isGeneratingCode}
            >
              {generatedCode ? '使用已有代码执行' : '生成代码并执行'}
            </Button>
          )}
        </Space>
      </Modal>
    </div>
  );
};

export default ActivityPage;