import { Module } from '@nestjs/common';
import { BrowserSemanticsClient } from '../../client/browser-semantics.client';
import { ModelModule } from '../model/model.module';
import { RedisModule } from '../redis/redis.module';
import { BranchAnalysisModule } from '../branch-analysis/branch-analysis.module';
import { BrowserCommandController, RecorderDebugController } from './gateway';
import {
  RecorderDebugSessionCoordinatorService,
  RecorderDebugSessionStoreService,
} from './session';
import {
  RecorderDebugObservationRefreshService,
  RecorderObservationService,
  RecorderSnapshotService,
  RecorderSnapshotReuseService,
  RecorderTargetResolutionReuseService,
  RecorderStructureProbeService,
} from './observe';
import {
  BrowserActionValidatorService,
  BrowserCandidateContextFormatter,
  BrowserCommandActionService,
  BrowserCommandAtomicService,
  BrowserCommandClickContextService,
  BrowserCommandContextNormalizerService,
  BrowserCommandFieldFillService,
  BrowserCommandLoginService,
  BrowserCommandNavigationService,
  BrowserCommandReadService,
  BrowserCommandSearchService,
  BrowserCommandSemanticLogService,
  BrowserCommandSemanticRuntimeService,
  BrowserCommandSequentialService,
  BrowserCommandService,
  BrowserExecutionPlannerService,
  BrowserPlannerPromptBuilder,
  BrowserPlannerResponseParser,
  RecorderDisambiguationService,
  RecorderParameterService,
  TableRegionResolverService,
} from './intent';
import {
  BrowserExecutionControllerService,
  ExecutionReconcileService,
  RecorderDebugBranchFacade,
  RecorderDebugChatExecutionService,
  RecorderDebugChatFlowService,
  RecorderDebugChatSupportService,
  RecorderDebugExecutionService,
  RecorderDebugOutcomeService,
  RecorderDebugObservationFacade,
  RecorderDebugResponseService,
  RecorderDebugService,
  RecorderDebugSessionFacade,
} from './execute';
import { RecorderHistoryCompressionService } from './execute/recorder';
import {
  RecorderConditionalBranchService,
  RecorderLoopExportService,
  RecorderLoopLocatorService,
  RecorderLoopService,
  RecorderLoopStateService,
} from './loop';
import {
  RecorderExportAssemblyService,
  RecorderExportService,
  RecorderScriptExportService,
  RecorderTemplateExportService,
  RecorderDurableLocatorResolver,
} from './export';
import { RecorderStateStoreService } from './execute/recorder';
import { RecorderDebugRollbackService } from './execute/recorder';

@Module({
  imports: [ModelModule, RedisModule, BranchAnalysisModule],
  controllers: [BrowserCommandController, RecorderDebugController],
  providers: [
    BrowserCommandService,
    BrowserCommandLoginService,
    BrowserCommandNavigationService,
    BrowserCommandReadService,
    BrowserCommandActionService,
    BrowserCommandSearchService,
    BrowserCommandFieldFillService,
    BrowserCommandAtomicService,
    BrowserCommandSequentialService,
    BrowserCommandSemanticLogService,
    BrowserCommandSemanticRuntimeService,
    BrowserCommandContextNormalizerService,
    BrowserCommandClickContextService,
    TableRegionResolverService,
    BrowserSemanticsClient,
    BrowserCandidateContextFormatter,
    BrowserPlannerPromptBuilder,
    BrowserPlannerResponseParser,
    BrowserExecutionControllerService,
    BrowserExecutionPlannerService,
    RecorderDebugBranchFacade,
    RecorderDebugObservationFacade,
    RecorderDebugSessionFacade,
    RecorderDebugService,
    RecorderDebugChatSupportService,
    RecorderDebugChatExecutionService,
    RecorderDebugChatFlowService,
    RecorderConditionalBranchService,
    RecorderDebugExecutionService,
    RecorderDebugOutcomeService,
    RecorderDebugObservationRefreshService,
    RecorderDebugResponseService,
    RecorderDebugSessionCoordinatorService,
    RecorderDebugSessionStoreService,
    RecorderExportAssemblyService,
    RecorderLoopStateService,
    RecorderLoopLocatorService,
    RecorderLoopExportService,
    RecorderLoopService,
    RecorderExportService,
    RecorderDurableLocatorResolver,
    RecorderDisambiguationService,
    RecorderObservationService,
    RecorderSnapshotService,
    RecorderSnapshotReuseService,
    RecorderTargetResolutionReuseService,
    RecorderStructureProbeService,
    BrowserActionValidatorService,
    RecorderParameterService,
    RecorderScriptExportService,
    RecorderTemplateExportService,
    ExecutionReconcileService,
    RecorderHistoryCompressionService,
    RecorderStateStoreService,
    RecorderDebugRollbackService,
  ],
  exports: [
    BrowserCommandService,
    RecorderDebugService,
    RecorderLoopService,
    ExecutionReconcileService,
  ],
})
export class BrowserModule {}
