import { RecorderSessionLockService } from './recorder/recorder-session-lock.service';
import { buildRecorderVerification } from './recorder/recorder-debug-verification';
import { execSync } from 'child_process';

describe('Verification of All 5 P1 Fixes', () => {

  describe('Fix 1: Workflow Condition Evaluation & Fail-Closed Behavior', () => {
    it('accurately parses operators from arrow functions without matching the arrow and fails closed on invalid inputs', () => {
      // Execute the exact Python snippet generated by temporal-workflow-deterministic-activity-code.helpers
      const pythonScript = `
import re

def _eval_cond(cond_fn_str, eval_ctx, def_text):
    if not cond_fn_str:
        return True
    expr = str(cond_fn_str).strip()
    if "=>" in expr:
        expr = expr.split("=>", 1)[1].strip()
    ctx_var_names = re.findall(r"""ctx\\.([a-zA-Z0-9_]+)""", expr)
    op_match = re.search(r"""([><]=?|===?|!==?)""", expr)
    if op_match and any(op in expr for op in (">", "<", ">=", "<=")):
        op = op_match.group(1)
        left_raw = eval_ctx.get(ctx_var_names[0]) if ctx_var_names else def_text
        left_clean = re.sub(r"""[^0-9.-]+""", "", str(left_raw or ""))
        if len(ctx_var_names) > 1:
            right_raw = eval_ctx.get(ctx_var_names[1])
        else:
            lit_match = re.search(r"""[><]=?\\s*(?:Number\\()?\\s*([0-9.]+)\\s*\\)?""", expr)
            right_raw = lit_match.group(1) if lit_match else "0"
        right_clean = re.sub(r"""[^0-9.-]+""", "", str(right_raw or ""))
        if not left_clean or not right_clean:
            return False
        try:
            num_left = float(left_clean)
            num_right = float(right_clean)
            if op == ">": return num_left > num_right
            if op == ">=": return num_left >= num_right
            if op == "<": return num_left < num_right
            if op == "<=": return num_left <= num_right
            if op in ("==", "==="): return num_left == num_right
            if op in ("!=", "!=="): return num_left != num_right
        except Exception:
            return False
    inc_neg = re.search(r"""!\\s*(?:String\\([^)]*\\)|[a-zA-Z0-9_.]+)\\.includes\\((['"])(.+)\\1\\)""", expr)
    if inc_neg:
        return inc_neg.group(2) not in def_text
    inc_pos = re.search(r"""(?:String\\([^)]*\\)|[a-zA-Z0-9_.]+)\\.includes\\((['"])(.+)\\1\\)""", expr)
    if inc_pos:
        return inc_pos.group(2) in def_text
    eq_match = re.search(r"""===\\s*(['"])(.+)\\1""", expr)
    if eq_match:
        return def_text == eq_match.group(2)
    neq_match = re.search(r"""!==\\s*(['"])(.+)\\1""", expr)
    if neq_match:
        return def_text != neq_match.group(2)
    return False

cond_less = "(ctx) => Number(ctx.grossMargin || 0) < Number(ctx.grossMarginThreshold || 20)"
cond_gte = "(ctx) => Number(ctx.grossMargin || 0) >= Number(ctx.grossMarginThreshold || 20)"

assert _eval_cond(cond_less, {"grossMargin": "17.8", "grossMarginThreshold": "20"}, "") == True
assert _eval_cond(cond_less, {"grossMargin": "25.5", "grossMarginThreshold": "20"}, "") == False
assert _eval_cond(cond_gte, {"grossMargin": "20", "grossMarginThreshold": "20"}, "") == True
# Fail-closed check: missing/empty grossMargin must return False (triggers takeover)
assert _eval_cond(cond_less, {"grossMargin": "", "grossMarginThreshold": "20"}, "") == False
print("OK")
`;
      const out = execSync(`python3 -c '${pythonScript.replace(/'/g, "'\\''")}'`, { encoding: 'utf-8' });
      expect(out.trim()).toBe('OK');
    });
  });

  describe('Fix 2: Lock Timeout Retains Execution Ownership to Prevent Concurrency Leak', () => {
    it('keeps lock held until slow background action completes so next task never runs concurrently', async () => {
      const lockService = new RecorderSessionLockService();
      const events: string[] = [];

      const slowTask = lockService.acquire(
        'session-leak-test',
        async () => {
          events.push('slow-start');
          await new Promise((resolve) => setTimeout(resolve, 80));
          events.push('slow-end');
          return 'slow-res';
        },
        30
      );

      await expect(slowTask).rejects.toThrow(/Session execution lock timed out after 30ms/);

      const nextTask = lockService.acquire('session-leak-test', async () => {
        events.push('next-start');
        return 'next-res';
      });

      const nextRes = await nextTask;
      expect(nextRes).toBe('next-res');
      // next-start MUST occur after slow-end!
      expect(events).toEqual(['slow-start', 'slow-end', 'next-start']);
    });
  });

  describe('Fix 3: Session Reload Inside Lock to Prevent History Overwrite', () => {
    it('serializes requests and loads session inside lock so concurrent turns do not overwrite history', async () => {
      const lockService = new RecorderSessionLockService();
      // Mock persistent session store
      const mockStore = new Map<string, any>();
      mockStore.set('sess-1', {
        sessionId: 'sess-1',
        runtimeSessionId: 'rt-1',
        history: [],
      });

      const loadOrCreateSession = async (id: string) => {
        const existing = mockStore.get(id);
        // Deep copy simulating Redis JSON parse
        return JSON.parse(JSON.stringify(existing));
      };

      const saveSession = async (session: any) => {
        mockStore.set(session.sessionId, JSON.parse(JSON.stringify(session)));
      };

      const chatTurn = async (message: string) => {
        const sessionId = 'sess-1';
        return lockService.acquire('rt-1', async () => {
          const session = await loadOrCreateSession(sessionId);
          session.history.push({ role: 'user', content: message });
          await new Promise((resolve) => setTimeout(resolve, 20));
          await saveSession(session);
          return session;
        });
      };

      // Launch two concurrent chat turns
      const [t1, t2] = await Promise.all([
        chatTurn('first-message'),
        chatTurn('second-message'),
      ]);

      const finalSession = mockStore.get('sess-1');
      expect(finalSession.history.length).toBe(2);
      expect(finalSession.history[0].content).toBe('first-message');
      expect(finalSession.history[1].content).toBe('second-message');
    });
  });

  describe('Fix 4: Execution vs Observation Consistency Verification', () => {
    it('fails verification and penalizes confidence when tool opens new page but observation stayed on old page', () => {
      const commands = [
        { tool: 'click_result' as const, params: { index: 3 }, description: '点击第 3 条' },
      ];

      const outcome = buildRecorderVerification({
        kind: 'action',
        status: 'executed',
        intent: {
          userGoal: '打开第三条检索结果',
          normalizedGoal: '打开第三条检索结果',
          actionType: 'click',
        },
        commands,
        beforeObservation: {
          currentPageUrl: 'https://www.baidu.com/s?wd=mcp',
          pageTitle: 'mcp_百度搜索',
          text: '百度搜索结果',
          inputs: [],
          buttons: [],
        },
        observation: {
          currentPageUrl: 'https://www.baidu.com/s?wd=mcp',
          pageTitle: 'mcp_百度搜索',
          text: '百度搜索结果',
          inputs: [],
          buttons: [],
        },
        diff: {
          urlChanged: false,
          titleChanged: false,
        },
        execution: {
          success: true,
          results: [
            {
              command: 'click_result',
              data: {
                openedNewPage: true,
                landedUrl: 'https://mcp.pkulaw.com/',
                title: '北大法宝 - MCP智能法律服务平台',
              },
            },
          ],
          executedCommands: commands,
        },
      });

      expect(outcome.verifier).toBe('search-result-open');
      expect(outcome.success).toBe(false);
      expect(outcome.confidence).toBeLessThan(0.5);
      expect(outcome.failureReason).toContain('执行与观察不一致');
    });

    it('passes verification with high confidence when observation matches the opened page', () => {
      const commands = [
        { tool: 'click_result' as const, params: { index: 3 }, description: '点击第 3 条' },
      ];

      const outcome = buildRecorderVerification({
        kind: 'action',
        status: 'executed',
        intent: {
          userGoal: '打开第三条检索结果',
          normalizedGoal: '打开第三条检索结果',
          actionType: 'click',
        },
        commands,
        beforeObservation: {
          currentPageUrl: 'https://www.baidu.com/s?wd=mcp',
          pageTitle: 'mcp_百度搜索',
          text: '百度搜索结果',
          inputs: [],
          buttons: [],
        },
        observation: {
          currentPageUrl: 'https://mcp.pkulaw.com/',
          pageTitle: '北大法宝 - MCP智能法律服务平台',
          text: '法宝详情',
          inputs: [],
          buttons: [],
        },
        diff: {
          urlChanged: true,
          titleChanged: true,
        },
        execution: {
          success: true,
          results: [
            {
              command: 'click_result',
              data: {
                openedNewPage: true,
                landedUrl: 'https://mcp.pkulaw.com/',
                title: '北大法宝 - MCP智能法律服务平台',
              },
            },
          ],
          executedCommands: commands,
        },
      });

      expect(outcome.verifier).toBe('search-result-open');
      expect(outcome.success).toBe(true);
      expect(outcome.confidence).toBeGreaterThan(0.8);
    });
  });
});
