/**
 * Standard Error Codes for Enterprise Skill Platform v4
 */
export declare const ERROR_CODES: {
  readonly EXECUTION_NOT_FOUND: 'EXECUTION_NOT_FOUND';
  readonly EXECUTION_INVALID_STATUS: 'EXECUTION_INVALID_STATUS';
  readonly EXECUTION_APPROVAL_REQUIRED: 'EXECUTION_APPROVAL_REQUIRED';
  readonly EXECUTION_HUMAN_CONTROL_REQUIRED: 'EXECUTION_HUMAN_CONTROL_REQUIRED';
  readonly EXECUTION_INPUT_REQUIRED: 'EXECUTION_INPUT_REQUIRED';

  readonly SKILL_NOT_FOUND: 'SKILL_NOT_FOUND';
  readonly SKILL_NOT_PUBLISHED: 'SKILL_NOT_PUBLISHED';
  readonly SKILL_PERMISSION_DENIED: 'SKILL_PERMISSION_DENIED';
  readonly SKILL_TOOL_VALIDATION_FAILED: 'SKILL_TOOL_VALIDATION_FAILED';

  readonly TOOL_NOT_FOUND: 'TOOL_NOT_FOUND';
  readonly TOOL_DISABLED: 'TOOL_DISABLED';
  readonly TOOL_NOT_VISIBLE: 'TOOL_NOT_VISIBLE';
  readonly TOOL_NOT_BOUND_TO_SKILL: 'TOOL_NOT_BOUND_TO_SKILL';
  readonly TOOL_PROMPT_ONLY: 'TOOL_PROMPT_ONLY';
  readonly TOOL_REQUIRES_APPROVAL: 'TOOL_REQUIRES_APPROVAL';
  readonly TOOL_NOT_ALLOWED: 'TOOL_NOT_ALLOWED';

  readonly RUNTIME_SESSION_NOT_FOUND: 'RUNTIME_SESSION_NOT_FOUND';
  readonly RUNTIME_UNAVAILABLE: 'RUNTIME_UNAVAILABLE';
  readonly RUNTIME_STEP_EXECUTION_FAILED: 'RUNTIME_STEP_EXECUTION_FAILED';
  readonly RUNTIME_TAKEOVER_REQUIRED: 'RUNTIME_TAKEOVER_REQUIRED';
};

export type ErrorCode = keyof typeof ERROR_CODES;
