/**
 * Standard Error Codes for Enterprise Skill Platform v4
 */
const ERROR_CODES = {
  // Execution Domain
  EXECUTION_NOT_FOUND: 'EXECUTION_NOT_FOUND',
  EXECUTION_INVALID_STATUS: 'EXECUTION_INVALID_STATUS',
  EXECUTION_APPROVAL_REQUIRED: 'EXECUTION_APPROVAL_REQUIRED',
  EXECUTION_HUMAN_CONTROL_REQUIRED: 'EXECUTION_HUMAN_CONTROL_REQUIRED',
  EXECUTION_INPUT_REQUIRED: 'EXECUTION_INPUT_REQUIRED',

  // Skill Domain
  SKILL_NOT_FOUND: 'SKILL_NOT_FOUND',
  SKILL_NOT_PUBLISHED: 'SKILL_NOT_PUBLISHED',
  SKILL_PERMISSION_DENIED: 'SKILL_PERMISSION_DENIED',
  SKILL_TOOL_VALIDATION_FAILED: 'SKILL_TOOL_VALIDATION_FAILED',

  // Tool Domain
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_DISABLED: 'TOOL_DISABLED',
  TOOL_NOT_VISIBLE: 'TOOL_NOT_VISIBLE',
  TOOL_NOT_BOUND_TO_SKILL: 'TOOL_NOT_BOUND_TO_SKILL',
  TOOL_PROMPT_ONLY: 'TOOL_PROMPT_ONLY',
  TOOL_REQUIRES_APPROVAL: 'TOOL_REQUIRES_APPROVAL',
  TOOL_NOT_ALLOWED: 'TOOL_NOT_ALLOWED',

  // Runtime Domain
  RUNTIME_SESSION_NOT_FOUND: 'RUNTIME_SESSION_NOT_FOUND',
  RUNTIME_UNAVAILABLE: 'RUNTIME_UNAVAILABLE',
  RUNTIME_STEP_EXECUTION_FAILED: 'RUNTIME_STEP_EXECUTION_FAILED',
  RUNTIME_TAKEOVER_REQUIRED: 'RUNTIME_TAKEOVER_REQUIRED',
};

module.exports = {
  ERROR_CODES,
};
