import type {
  BuiltinRuleCheckpoint,
  ContractTypeKey,
  UserCustomRule,
} from './contractReviewRules.types';

export interface BuiltinContractTypeData {
  name: string;
  description: string;
  partyAName: string;
  partyBName: string;
  checkpoints: BuiltinRuleCheckpoint[];
}

export const BUILTIN_RULES_DATA: Record<ContractTypeKey, BuiltinContractTypeData> = {
  software_development: {
    name: '软件定制研发与系统集成协议',
    description: '涵盖敏捷开发、外包定制与系统集成。重点审查工期口径顺延、验收客观性、知识产权权属归属与违约金封顶。',
    partyAName: '甲方 (委托开发方)',
    partyBName: '乙方 (受托开发方)',
    checkpoints: [
      {
        title: '工期计算口径被变更为自然日/日历日',
        category: '工期交付',
        severity: 'HIGH',
        position: 'party_b',
        rationale: '工期按日历日/自然日计算剥夺了法定节假日与周末研发时间，大幅压缩实际研发工期，增加延期违约风险。',
        recommendation: '建议坚持采用“工作日”口径计算，或增加因相对方确认延迟、需求变更引起的工期对等顺延条款。',
      },
      {
        title: '验收标准设定主观满意度或严苛无限期试运行',
        category: '验收交付',
        severity: 'HIGH',
        position: 'party_b',
        rationale: '约定以甲方“单方满意度”或集团内部主观审查作为验收条件，导致乙方验收回款被无限期拖延。',
        recommendation: '应坚持以量化的《技术规格说明书》为客观标准，并约定试运行期满 5 个工作日内未提出书面异议即视为验收合格。',
      },
      {
        title: '交付源码及知识产权未约定全资归属甲方',
        category: '知识产权',
        severity: 'HIGH',
        position: 'party_a',
        rationale: '甲方出资委托定制研发，若未约定全部知识产权（含源代码、设计文档）归甲方独占，乙方可能转售给竞争对手。',
        recommendation: '明确约定：本协议项下所有定制开发成果（包括但不限于源代码、算法模型、技术文档）的全部知识产权自产生之日起独家归甲方所有。',
      },
      {
        title: '逾期违约金过高且未设封顶上限',
        category: '违约赔偿',
        severity: 'HIGH',
        position: 'party_b',
        rationale: '日违约金比例超过千分之五，或未约定违约金累计封顶上限，违约敞口风险无限扩大。',
        recommendation: '建议约定每日违约金不超过未交付部分金额的 0.05%，且累计总额不得超过合同总价款的 5%~10%。',
      },
      {
        title: '开源软件安全与无限连带责任陷阱',
        category: '开源合规',
        severity: 'MEDIUM',
        position: 'party_b',
        rationale: '要求开发方对系统内所有第三方/开源组件承担无限连带赔偿责任，超出正常研发责任边界。',
        recommendation: '仅担保合理审慎选择合规商业开源许可（如 MIT/Apache-2.0），排除不可控的传染性许可（如 GPL）连带兜底。',
      },
      {
        title: '缺少不可抗力免责与顺延约定',
        category: '必备缺失',
        severity: 'HIGH',
        position: 'both',
        rationale: '合同未约定不可抗力定义及责任免除机制，遇到重大突发事件时可能无法依法免除违约责任。',
        recommendation: '补充订立标准不可抗力条款，约定事件发生后法定免责并相应顺延交付工期。',
      },
      {
        title: '关键人员离场惩罚与知识转移保障',
        category: '人员保障',
        severity: 'MEDIUM',
        position: 'party_a',
        rationale: '乙方擅自更换核心架构师或项目经理，可能导致项目交付质量急剧下滑或工期延误。',
        recommendation: '约定核心开发人员名单未经甲方书面许可不得擅自更换；若因特殊原因离职须提前 15 日通知并安排同等资历人员交接。',
      },
    ],
  },
  procurement: {
    name: '商业采购买卖与供应协议',
    description: '重点防范账期垫资拖延、货物交付不合格退换货维权、到货检验期与产品质量连带保证责任。',
    partyAName: '买方 (采购方)',
    partyBName: '卖方 (供货方)',
    checkpoints: [
      {
        title: '超长付款账期与前置审批垫资风险',
        category: '付款账期',
        severity: 'HIGH',
        position: 'party_b',
        rationale: '约定开票后 90~180 天才支付货款，或者以“买方最终客户回款”为付款前提（背靠背支付），供货方现金流极度受损。',
        recommendation: '删除背靠背条款，坚持到货验收后 30 日内付款，明确买方逾期付款须按 LPR 利率上浮支付逾期利息。',
      },
      {
        title: '隐蔽瑕疵检验期过短',
        category: '质量验收',
        severity: 'HIGH',
        position: 'party_a',
        rationale: '检验期仅约定为到货后 3~7 天内，对于复杂设备或系统隐蔽瑕疵根本无法充分检验，超期将丧失索赔权利。',
        recommendation: '表面瑕疵检验期约定为到货后 7 天，隐蔽质量瑕疵及性能指标异议期应延长至质保期届满前（或至少 12 个月）。',
      },
      {
        title: '缺少价格调整与通胀对冲机制',
        category: '价格结算',
        severity: 'MEDIUM',
        position: 'both',
        rationale: '在长期框架供货合同中未约定原材料重大波动调整规则，导致单方承担严重成本亏损。',
        recommendation: '补充约定：主要原材料市场基准价格波动超过 ±10% 时，双方应启动价格友好协商复核机制。',
      },
      {
        title: '未约定增值税专用发票开具时限与防伪合规',
        category: '税务合规',
        severity: 'MEDIUM',
        position: 'party_a',
        rationale: '供货方延迟开具增值税发票可能导致采购方无法及时进项抵扣或产生税务稽查风险。',
        recommendation: '明确卖方须在收到每笔款项后 5 个工作日内向买方开具符合税法要求的全额增值税专用发票。',
      },
    ],
  },
  employment: {
    name: '劳动用工与高管聘用协议',
    description: '涵盖竞业限制、试用期约定合法性、商业秘密保护、知识产权职务发明归属与解雇赔偿合法合规。',
    partyAName: '用人单位 (公司方)',
    partyBName: '劳动者 (员工方)',
    checkpoints: [
      {
        title: '职务发明与知识产权归属约定不明',
        category: '知识产权',
        severity: 'HIGH',
        position: 'party_a',
        rationale: '员工在职期间利用公司资源完成的软件、专利、设计若未约定归属，离职后可能主张个人权利。',
        recommendation: '明文约定：员工在职期间执行工作任务或主要利用公司物质技术条件完成的发明创造与智力成果，全部知识产权均归公司独占所有。',
      },
      {
        title: '竞业限制补偿金未约定或比例过低',
        category: '竞业限制',
        severity: 'HIGH',
        position: 'both',
        rationale: '未约定竞业限制经济补偿金或低于法定标准（月平均工资 30%），可能导致竞业限制条款无效或被劳动仲裁追索。',
        recommendation: '约定竞业限制期限不超过 2 年，并明确离职后按月支付不低于在职前 12 个月月平均工资 30% 的经济补偿金。',
      },
      {
        title: '试用期期限超过法定强制上限',
        category: '合规用工',
        severity: 'HIGH',
        position: 'party_b',
        rationale: '劳动合同法规定：一年以上三年以下合同试用期不得超过二个月，三年以上合同不得超过六个月。超期约定将引发双倍赔偿金。',
        recommendation: '严格核对劳动合同期限与试用期对应法定标准，依法合规订立试用期。',
      },
    ],
  },
  lease: {
    name: '房屋建筑与经营场地租赁协议',
    description: '重点防范房屋权属瑕疵、转租限制、押金退还条件、提前解约违约金与装修改造恢复原状争议。',
    partyAName: '出租方 (房东方)',
    partyBName: '承租方 (租户方)',
    checkpoints: [
      {
        title: '房屋所有权证明及抵押查封权属隐患',
        category: '权属合规',
        severity: 'HIGH',
        position: 'party_b',
        rationale: '出租方并非房屋产权人且无转租授权，或房屋已被法院查封，导致租户承租后被强制清场。',
        recommendation: '查验不动产权证书原件并作为附件留存，在合同中明确出租方担保房屋权属无争议、未受司法查封。',
      },
      {
        title: '租期届满装修改造残值与恢复原状分歧',
        category: '装修归属',
        severity: 'MEDIUM',
        position: 'both',
        rationale: '退租时房东苛求“恢复毛坯原状”，或者租户擅自拆除固定附着物导致房屋受损。',
        recommendation: '明确约定：退租时承租方完成的不可移动附着装修归出租方所有，无需拆除恢复原状，出租方不得据此扣押租房押金。',
      },
      {
        title: '押金退还前置严苛扣款条件',
        category: '押金保障',
        severity: 'HIGH',
        position: 'party_b',
        rationale: '出租方以“自然老化磨损”或各种非客观维修名目任意扣留巨额租赁押金。',
        recommendation: '明确正常使用造成的自然老化磨损不属于赔偿范围，出租方须在交接完毕并结清水电费后 5 个工作日内全额无息退还押金。',
      },
    ],
  },
  nda: {
    name: '商业保密与反泄密协议 (NDA)',
    description: '重点防范保密义务期限陷阱、保密信息定义范围过宽、第三方披露责任与法定例外情形排除。',
    partyAName: '披露方',
    partyBName: '接收方',
    checkpoints: [
      {
        title: '永久保密义务期限陷阱',
        category: '保密期限',
        severity: 'HIGH',
        position: 'party_b',
        rationale: '约定永久或无期限的保密义务，将导致接收方未来自主研发业务与技术团队面临长期法律诉讼威胁。',
        recommendation: '建议修订为：除涉及核心商业秘密源代码外，普通商务保密信息的保密期限自披露之日起 3 年届满后终止。',
      },
      {
        title: '保密信息范围定义过宽且未作标记',
        category: '信息定义',
        severity: 'MEDIUM',
        position: 'party_b',
        rationale: '将“披露方以任何形式披露的所有信息”均列为保密信息，未要求书面标记，接收方极易因不知情而误触违约。',
        recommendation: '明确保密信息须以书面形式并明显标注“保密”字样；口头披露的信息须在 10 个工作日内出具书面纪要确认。',
      },
      {
        title: '缺失司法行政与法律强制披露例外条款',
        category: '必备缺失',
        severity: 'HIGH',
        position: 'both',
        rationale: '未约定司法机关、证监监管部门依法调查强制披露时的豁免权，可能面临遵守法律却违反合同的两难。',
        recommendation: '补充订立标准例外条款：依法令、司法裁定或监管机关强制要求披露的，接收方在合理通知披露方后免于承担违约责任。',
      },
    ],
  },
  general: {
    name: '通用商业合作与框架协议',
    description: '涵盖各类商务合作、代理销售与战略合作通用审查。核心关注对等违约责任、争议管辖与不可抗力。',
    partyAName: '甲方',
    partyBName: '乙方',
    checkpoints: [
      {
        title: '争议管辖偏远增加异地维权诉讼成本',
        category: '争议管辖',
        severity: 'HIGH',
        position: 'both',
        rationale: '约定由相对方所在地甚至第三方法院管辖，导致我方维权时承担高额差旅、异地聘请律师与地方保护风险。',
        recommendation: '坚持约定由【原告所在地人民法院】管辖，或双方所在地北京仲裁委员会进行仲裁，实现诉讼对等。',
      },
      {
        title: '单方任意解除权造成沉没成本巨大',
        category: '合同解除',
        severity: 'HIGH',
        position: 'both',
        rationale: '赋予相对方“无需任何理由随时通知解除合同”的权利，导致我方已投入的前期资源无法获得有效补偿。',
        recommendation: '删除单方无因解除权；仅在相对方构成根本性违约且经书面催告满 15 日仍未纠正时，守约方享有合同法定解除权。',
      },
    ],
  },
};

/**
 * Pre-seeded Enterprise Organization-Level Mandatory Rules (Admin-level)
 */
export const DEFAULT_ORG_RULES: UserCustomRule[] = [
  {
    id: 'org-rule-01',
    scope: 'org',
    applicablePosition: 'party_b',
    title: '【企业级红线】乙方违约金总额累计封顶 10%',
    category: '违约赔偿',
    contractType: 'all',
    severity: 'HIGH',
    rule: '我方作为乙方签署任何采购、研发或服务合同时，违约金日比例不得超过千分之零点五，且累计赔偿上限必须封顶合同总额的 10%。',
    recommendedRevision: '双方在此明确约定：因乙方原因发生交付迟延的，违约金每日按未交付部分价款的 0.05% 计算，累计违约赔偿总额最高不得超过本合同有效总金额的 10%。',
    enabled: true,
    creator: '法务合规部 (管理员)',
    createdAt: '2026-01-01',
  },
  {
    id: 'org-rule-02',
    scope: 'org',
    applicablePosition: 'party_b',
    title: '【企业级红线】付款账期不得超过 45 个自然日',
    category: '付款账期',
    contractType: 'all',
    severity: 'HIGH',
    rule: '禁止在合同中约定背靠背支付或超过 45 个自然日的长账期，保护企业现金流安全。',
    recommendedRevision: '买方在收到发票及合格验收回执后 30 个工作日（最长不超过 45 个自然日）内，将相应款项全额电汇至卖方指定银行账户。',
    enabled: true,
    creator: '财务审计部 (管理员)',
    createdAt: '2026-01-01',
  },
  {
    id: 'org-rule-03',
    scope: 'org',
    applicablePosition: 'party_a',
    title: '【企业级红线】甲方出资定制研发成果 100% 知识产权归我司',
    category: '知识产权',
    contractType: 'software_development',
    severity: 'HIGH',
    rule: '我司出资定制委托开发的任何软件、算法及配套文档，全部著作权与专利申请权必须完全由我司独占，严禁受托方保留任何可商用知识产权。',
    recommendedRevision: '本协议项下由乙方为甲方定制开发的所有技术成果、文档、源代码及衍生软件资产，其完整的专利申请权、软件著作权及商业秘密独占权自创作完成之日起全部归甲方独家所有。',
    enabled: true,
    creator: '知识产权管理委员会',
    createdAt: '2026-01-01',
  },
  {
    id: 'org-rule-04',
    scope: 'org',
    applicablePosition: 'both',
    title: '【企业级红线】诉讼争议管辖必须优先约定我方住所地法院',
    category: '争议管辖',
    contractType: 'all',
    severity: 'HIGH',
    rule: '因本合同引起的任何争议，必须约定由我司住所地人民法院管辖，或退而求其次选择原告所在地管辖，严禁直接约定为对方所在地。',
    recommendedRevision: '因本合同引起的或与本合同有关的任何争议，双方应友好协商解决；协商不成的，任何一方均应向我方住所地有管辖权的人民法院提起诉讼。',
    enabled: true,
    creator: '法务合规部 (管理员)',
    createdAt: '2026-01-01',
  },
];
