import { BuiltinWorkflowRuntimeAdapter } from '../src/modules/execution/adapters/builtin-workflow-runtime.adapter';
import { BuiltinHandlerRegistryService } from '../src/modules/execution/adapters/builtin-handler-registry.service';

describe('BuiltinWorkflowRuntimeAdapter Unit Tests', () => {
  let adapter: BuiltinWorkflowRuntimeAdapter;
  let registry: BuiltinHandlerRegistryService;

  beforeEach(() => {
    process.env.NODE_ENV = 'test';
    registry = new BuiltinHandlerRegistryService();
    registry.onModuleInit();
    adapter = new BuiltinWorkflowRuntimeAdapter(registry);
  });

  it('should identify supported requests for platform built-in skills', () => {
    const isSupported = adapter.supports({
      requestId: 'req-1',
      executionId: 'exec-1',
      stepId: 'step-1',
      runtimeType: 'workflow',
      capabilityType: 'builtin',
      action: 'write',
      skillId: 'platform.document.markdown-artifact-writer',
      input: {},
    });

    expect(isSupported).toBe(true);
  });

  it('should reject execution if definitionVersion is missing', async () => {
    const result = await adapter.invokeStep({
      requestId: 'req-1',
      executionId: 'exec-1',
      stepId: 'step-1',
      runtimeType: 'workflow',
      capabilityType: 'builtin',
      action: 'execute',
      skillId: 'platform.document.markdown-artifact-writer',
      input: {},
    });

    expect(result.success).toBe(false);
    expect(result.errorCode).toBe('BUILTIN_SKILL_VERSION_MISSING');
  });

  it('should dispatch step invocation via registered handler successfully', async () => {
    registry.registerHandler('document.markdown-artifact-writer', async (req, idempotencyKey) => {
      return {
        success: true,
        output: {
          artifact: {
            type: 'artifact',
            id: 'art-1',
            name: 'test_artifact.md',
            url: 'http://localhost:3009/renders/test_artifact.md',
            mimeType: 'text/markdown; charset=utf-8',
            sizeBytes: 120,
          },
        },
        artifacts: [
          {
            type: 'artifact',
            id: 'art-1',
            name: 'test_artifact.md',
            url: 'http://localhost:3009/renders/test_artifact.md',
            mimeType: 'text/markdown; charset=utf-8',
            sizeBytes: 120,
          },
        ],
      };
    });

    const result = await adapter.invokeStep({
      requestId: 'req-1',
      executionId: 'exec-100',
      stepId: 'step-3',
      runtimeType: 'workflow',
      capabilityType: 'builtin',
      action: 'execute',
      skillId: 'platform.document.markdown-artifact-writer',
      metadata: {
        definitionVersion: '1.0.1',
      },
      input: {
        content: '# Unit Test Markdown\n\nGenerated by BuiltinWorkflowRuntimeAdapter',
        fileName: 'test_artifact.md',
      },
    });

    expect(result.success).toBe(true);
    expect(result.status).toBe('completed');
    expect(result.output).toBeDefined();
    expect(result.output?.artifact).toBeDefined();
    expect((result.output?.artifact as any).mimeType).toBe('text/markdown; charset=utf-8');
    expect(result.artifacts).toHaveLength(1);
  });

  it('dispatches PDF extraction through the manifest handler key', async () => {
    registry.registerHandler('document.content-extractor.pdf', async () => ({
      success: true,
      output: { text: 'extracted', pageCount: 1, pages: [] },
    }));

    const result = await adapter.invokeStep({
      requestId: 'req-pdf',
      executionId: 'exec-pdf',
      stepId: 'extract-pdf',
      runtimeType: 'workflow',
      capabilityType: 'builtin',
      action: 'extract',
      skillId: 'platform.document.pdf-content-extractor',
      metadata: { definitionVersion: '1.0.0', handlerKey: 'document.content-extractor.pdf' },
      input: { fileBase64: 'pdf-bytes' },
    });

    expect(result).toMatchObject({ success: true, status: 'completed' });
    expect(result.output?.text).toBe('extracted');
  });
});
