export const BROWSER_WARNING_CODES = [
  'NAVIGATION_TIMEOUT_RECOVERED',
  'POST_STATE_OBSERVATION_FAILED',
  'SCREENSHOT_CAPTURE_FAILED',
  'HTML_CAPTURE_FAILED',
  'SNAPSHOT_CAPTURE_FAILED',
  'DECLARED_OUTPUT_MISSING',
  'ARTIFACT_NORMALIZATION_FAILED',
  'BROWSER_RUN_OUTPUT_INVALID',
] as const;

export type BrowserWarningCode = (typeof BROWSER_WARNING_CODES)[number];
