import { EXECUTION_STATUS, ExecutionStatus } from './contracts/execution-status';

export const EXECUTION_STATUS_TRANSITIONS: Record<ExecutionStatus, ExecutionStatus[]> = {
  [EXECUTION_STATUS.DRAFT]: [EXECUTION_STATUS.QUEUED, EXECUTION_STATUS.CANCELLED],
  [EXECUTION_STATUS.QUEUED]: [
    EXECUTION_STATUS.RUNNING,
    EXECUTION_STATUS.WAITING_INPUT,
    EXECUTION_STATUS.PENDING_APPROVAL,
    EXECUTION_STATUS.CANCELLED,
  ],
  [EXECUTION_STATUS.RUNNING]: [
    EXECUTION_STATUS.WAITING_INPUT,
    EXECUTION_STATUS.PENDING_APPROVAL,
    EXECUTION_STATUS.HUMAN_CONTROL,
    EXECUTION_STATUS.PAUSED,
    EXECUTION_STATUS.SUCCEEDED,
    EXECUTION_STATUS.FAILED,
    EXECUTION_STATUS.CANCELLED,
  ],
  [EXECUTION_STATUS.WAITING_INPUT]: [
    EXECUTION_STATUS.QUEUED,
    EXECUTION_STATUS.RUNNING,
    EXECUTION_STATUS.CANCELLED,
  ],
  [EXECUTION_STATUS.PENDING_APPROVAL]: [
    EXECUTION_STATUS.QUEUED,
    EXECUTION_STATUS.RUNNING,
    EXECUTION_STATUS.CANCELLED,
  ],
  [EXECUTION_STATUS.HUMAN_CONTROL]: [EXECUTION_STATUS.RUNNING, EXECUTION_STATUS.CANCELLED],
  [EXECUTION_STATUS.PAUSED]: [EXECUTION_STATUS.RUNNING, EXECUTION_STATUS.CANCELLED],
  [EXECUTION_STATUS.SUCCEEDED]: [],
  [EXECUTION_STATUS.FAILED]: [],
  [EXECUTION_STATUS.CANCELLED]: [],
  [EXECUTION_STATUS.ROLLED_BACK]: [],
};

export const canTransitionExecutionStatus = (
  currentStatus: ExecutionStatus,
  nextStatus: ExecutionStatus
): boolean => EXECUTION_STATUS_TRANSITIONS[currentStatus].includes(nextStatus);

export { isTerminalExecutionStatus } from '@ops/contracts';
