export const IDENTITY_ACCESS_USER_READER = Symbol('IDENTITY_ACCESS_USER_READER');
export const RBAC_PERMISSION_READER = Symbol('RBAC_PERMISSION_READER');
export const IDENTITY_ACCESS_AUTH_REPOSITORY = Symbol('IDENTITY_ACCESS_AUTH_REPOSITORY');
export const IDENTITY_ACCESS_USER_MANAGEMENT_REPOSITORY = Symbol(
  'IDENTITY_ACCESS_USER_MANAGEMENT_REPOSITORY'
);
